# Experimente für SemEval 2026 Task 11

## Konfigurationen laden

In [3]:
import sys
import os
import importlib
import shutil

def setup_environment():
    """Löscht das Repo, klont neu und lädt die Module frisch."""
    # Check if we are running in Google Colab
    IN_COLAB = 'google.colab' in sys.modules

    if not IN_COLAB:
        print("Detected: Local Environment. Enabling autoreload...")
        try:
            from IPython import get_ipython
            ip = get_ipython()
            if ip:
                ip.run_line_magic('load_ext', 'autoreload')
                ip.run_line_magic('autoreload', '2')
        except Exception as e:
            print(f"Could not load autoreload: {e}")
    else:
        print("Refreshing Colab Environment...")
        from google.colab import userdata
        from huggingface_hub import login

        token = userdata.get('GITHUB_TOKEN')
        username = "WiebkePetersen"
        repo = "SemEval2026_task11_Reasoning"

        # 1. Zurück zum Root (/content)
        os.chdir('/content')

        # 2. Altes Repo löschen mit reinem Python
        repo_path_full = os.path.join('/content', repo)
        if os.path.exists(repo_path_full):
            shutil.rmtree(repo_path_full)
            print(f"Removed old repo at {repo_path_full}")

        # 3. Cache säubern
        for mod in list(sys.modules.keys()):
            if 'reasoning' in mod:
                del sys.modules[mod]

        # 4. Neu klonen (Shell-Befehl ohne get_ipython Referenz)
        clone_url = f"https://{token}@github.com/{username}/{repo}.git"
        os.system(f"git clone -q {clone_url}")

        # 5. In den Ordner wechseln
        if os.path.exists(repo_path_full):
            os.chdir(repo_path_full)
        else:
            print(f"❌ Error: Repo could not be cloned to {repo_path_full}")
            return

        # 6. Packages installieren
        os.system("pip install -q transformers datasets accelerate pyyaml tqdm bitsandbytes sentencepiece")

        # 7. Pfad setzen
        repo_root = os.path.abspath(".")
        if repo_root in sys.path:
            sys.path.remove(repo_root)
        sys.path.insert(0, repo_root)

        # 8. HF Login
        hf_token = userdata.get('Semeval2026Read')
        if hf_token:
            login(token=hf_token, add_to_git_credential=True)

        print(f"✅ Environment refreshed. Current Dir: {os.getcwd()}")

# Aufruf
setup_environment()

Detected: Local Environment. Enabling autoreload...

In [4]:
import yaml
import requests
import pandas as pd
from datasets import Dataset
import gc

from reasoning.io_utils import load_config, load_data, save_data, create_predictions_file
from reasoning.io_utils import list_apply, get_experiment_config, merge_datasets_by_id
from reasoning.generate_utils import format_to_prompt, generate_with_prompt
from reasoning.evaluation_utils import evaluate_subtask_1_3, evaluate_subtask_2_4, my_evaluate_subtask_1_3#, my_evaluate_subtask_2_4
from reasoning.fol_prover_utils import evaluate_dataset_with_otter, process_dataset_to_fol
import json


# if something is changed in github on a later point,
# call setup_environment() and
# importlib.reload(reasoning.generate_utils)

CONFIG_PATH = "experiments.yaml"

data_type ="test_subtask1"  # Options: "train", "train_all", "train200", "test_subtask1", "test_subtask2", "test_subtask3", "test_subtask4"

if "train" in data_type:
    FILE_PATH = "https://raw.githubusercontent.com/neuro-symbolic-ai/semeval_2026_task_11/refs/heads/main/train_data/subtask%201/train_data.json"
elif data_type == "train_all":
    FILE_PATH = "https://raw.githubusercontent.com/neuro-symbolic-ai/semeval_2026_task_11/refs/heads/main/train_data/subtask%201/train_data.json"
elif data_type == "test_subtask1":
    FILE_PATH = "https://raw.githubusercontent.com/neuro-symbolic-ai/semeval_2026_task_11/refs/heads/main/test_data/subtask%201/test_data_subtask_1.json"
    subtask = "subtask1"
elif data_type == "test_subtask2":
    FILE_PATH = "https://raw.githubusercontent.com/neuro-symbolic-ai/semeval_2026_task_11/refs/heads/main/test_data/subtask%202/test_data_subtask_2.json"
    subtask = "subtask2"
elif data_type == "test_subtask3":
    FILE_PATH = "https://raw.githubusercontent.com/neuro-symbolic-ai/semeval_2026_task_11/refs/heads/main/test_data/subtask%203/test_data_subtask_3.json"
    FILE_PATH = "output/translated_subtask_3.json"
    subtask = "subtask3"
elif data_type == "test_subtask4":
    FILE_PATH = "https://raw.githubusercontent.com/neuro-symbolic-ai/semeval_2026_task_11/refs/heads/main/test_data/subtask%204/test_data_subtask_4.json"
    FILE_PATH = "output/translated_subtask_4.json"
    subtask = "subtask4"


configs = load_config(CONFIG_PATH)

if data_type == "test_subtask3":
    with open(FILE_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)
    dataset = Dataset.from_pandas(pd.DataFrame(data), preserve_index=False)
    dataset = dataset.map(lambda x: {"syllogism": x["english_translated_syllogism"]})
    dataset = dataset.remove_columns(["english_translated_syllogism"])
    del data
    gc.collect()
elif data_type == "test_subtask4":
    with open(FILE_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)
    dataset = Dataset.from_pandas(pd.DataFrame(data), preserve_index=False)
    dataset = dataset.map(lambda x: {"syllogism": x["english_translated_syllogism"]})
    dataset = dataset.remove_columns(["english_translated_syllogism"])
    del data
    gc.collect()
else:
    # Fetch JSON from URL and convert to Dataset
    response = requests.get(FILE_PATH)
    response.raise_for_status()
    dataset = Dataset.from_pandas(pd.DataFrame(response.json()), preserve_index=False)
    del response
    gc.collect()

if data_type == "train":
  dataset = dataset.select(range(100)) # für Testzwecke wird der Datensatz auf die ersten 100 verkleinert

if data_type == "train200":
    dataset = dataset.shuffle(seed=42).select(range(200))
    print(f"Selected 200 stable random items (Seed 42). Size: {len(dataset)}")


file_name_generations = "output/" + data_type +"_data_with_generations.parquet"

if os.path.exists(file_name_generations):
    # If the file exists, load the progress from the previous run
    print(f"🔄 Found existing file '{file_name_generations}'. Loading local data...")
    dataset = load_data(file_name_generations)
else:
    # If it's the first run, save the initial dataset to create the local copy manualle
    print(f"🆕 No local copy found. Save current dataset as '{file_name_generations}'if it is the first time using the data_type")


#save_data(dataset, file_name_generations) # only uncomment if it is the first time using the data_type

print(f"✅ Loaded {len(dataset)} data points")

🔄 Found existing file 'output/test_subtask1_data_with_generations.parquet'. Loading local data...
✅ Loaded 191 data points

In [219]:
configs

{'experiments': {'Simp1': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'syllogism_simplified_Simp1',
   'output_type': 'list',
   'task_description': 'Translate original sentences to logical pseudo English.  Restrict vocabulary to  "all ... is ...", "some ... is ...", "no ... is ...", ""some ... is not ...".  Use only singular. Write predicates and subjects capitalized.  No fill words. Multi-word expressions are aggregated with _ \n',
   'system_prompt': 'LogSimp',
   'examples': 'LogSimpEx',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Simp2': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'syllogism_simplified_Simp2',
   'output_type': 'list',
   'task_description': 'Translate original sentences to logical pseudo English.  Restrict vocabulary to  "all ... is ...", "some ... is ...", "no ... is ...", ""some ... is not ...".  Use only singular. Write predicates and subjects capitalized.  No fill words. Multi-word expressions are aggregated with _ Shorter prompt \n',
   'system_prompt': 'LogSimpShortPrompt',
   'examples': 'LogSimpEx',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2SyllogismProlog': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'aristotelian_output_Eng2SyllogismProlog',
   'output_type': 'list',
   'task_description': 'Given a list of English sentences translate them to Aristotelian syllogistic notation. \n',
   'system_prompt': 'SyllTrip',
   'examples': 'SyllTripEx',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'SimpEng2SyllogismProlog': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism_simplified_Simp1',
   'output_key': 'aristotelian_output_SimpEng2SyllogismProlog',
   'output_type': 'list',
   'task_description': 'Given a list of simplified logical English sentences translate them to Aristotelian syllogistic notation. \n',
   'system_prompt': 'SyllTrip',
   'examples': 'SimpSyllTripEx',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2FOL': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOL',
   'examples': 'Eng2FOLex',
   'params': {'temperature': 0.0, 'max_new_tokens': 512, 'batch_size': 16}},
  'SimpEng2FOL1': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism_simplified_Simp1',
   'output_key': 'fol_otter_output_SimpEng2FOL1',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOL',
   'examples': 'Eng2FOLex',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'SimpEng2FOL2': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism_simplified_Simp2',
   'output_key': 'fol_otter_output_SimpEng2FOL2',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOL',
   'examples': 'Eng2FOLex',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL2': {'model': 'meta-llama/Llama-3.2-3B-Instruct',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL2',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLimproved',
   'examples': 'Eng2FOLexImproved',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL3': {'model': 'meta-llama/Llama-3.2-3B-Instruct',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL3',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'temperature': 0.0, 'max_new_tokens': 512, 'batch_size': 16}},
  'Eng2FOL4': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL4',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLimproved',
   'examples': 'Eng2FOLexImproved',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL6': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL6',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImproved',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL7': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL7',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOL',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5multilingual': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5multilingual',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5small': {'model': 'HuggingFaceTB/SmolLM2-1.7B-Instruct',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5small',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5tiny': {'model': 'HuggingFaceTB/SmolLM2-135M-Instruct',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5tiny',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5Gemma2B': {'model': 'google/gemma-2-2b-it',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5Gemma2B',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5Qwen1.7B': {'model': 'Qwen/Qwen3-1.7B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5Qwen1.7B',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2FOL5Qwen0.6B': {'model': 'Qwen/Qwen3-0.6B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5Qwen0.6B',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2FOL5Qwen4B': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5Qwen4B',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2FOL8': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL8',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImproved2',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOLmultilingualNew': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_Eng2FOLmultilingualNew',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingFOL',
   'examples': 'MultiLingexImproved',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOLmultilingualNewShort': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_Eng2FOLmultilingualNewShort',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingFOL',
   'examples': 'MultiLingexImprovedShort',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5multilingualNew': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5multilingualNew',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingEng2FOLUltrashort',
   'examples': 'MultiLingexImproved',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL5multilingualNewShort': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_Eng2FOL5multilingualNewShort',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingEng2FOLUltrashort',
   'examples': 'MultiLingexImprovedShort',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'QwenEng2FOL1': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL1',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImproved2',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL2': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL2',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImproved',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL3': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL3',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLex',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL4': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL4',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLimproved',
   'examples': 'Eng2FOLexImproved',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL5': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL5',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOL',
   'examples': 'Eng2FOLexImproved',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL6': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL6',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLimproved',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL5multilingual': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL5multilingual',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexImprovedX',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOLmultilingualNew': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOLmultilingualNew',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingFOL',
   'examples': 'MultiLingexImproved',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOLmultilingualNewShort': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOLmultilingualNewShort',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingFOL',
   'examples': 'MultiLingexImprovedShort',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL5multilingualNew': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL5multilingualNew',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingEng2FOLUltrashort',
   'examples': 'MultiLingexImproved',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'QwenEng2FOL5multilingualNewShort': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_QwenEng2FOL5multilingualNewShort',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingEng2FOLUltrashort',
   'examples': 'MultiLingexImprovedShort',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2FOL9': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL9',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexVaried',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL9Qwen4B': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL9Qwen4B',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLUltrashort',
   'examples': 'Eng2FOLexVaried',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'Eng2FOL10': {'model': 'HuggingFaceTB/SmolLM3-3B',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL10',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLimproved',
   'examples': 'Eng2FOLexVaried',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'Eng2FOL10Qwen4B': {'model': 'Qwen/Qwen3-4B-Instruct-2507',
   'input_key': 'syllogism',
   'output_key': 'fol_otter_output_Eng2FOL10Qwen4B',
   'output_type': 'list',
   'task_description': 'Translate English sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'Eng2FOLimproved',
   'examples': 'Eng2FOLexVaried',
   'params': {'do_sample': True,
    'temperature': 0.1,
    'top_p': 0.9,
    'repetition_penalty': 1.1,
    'max_new_tokens': 256,
    'batch_size': 8}},
  'GemmaEng2FOL5multilingualNewShort': {'model': 'google/gemma-2-2b-it',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_GemmaEng2FOL5multilingualNewShort',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingEng2FOLUltrashort',
   'examples': 'MultiLingexImprovedShort',
   'params': {'do_sample': False,
    'temperature': 0.0,
    'max_new_tokens': 512,
    'batch_size': 16}},
  'GemmaEng2FOLmultilingualNewShort': {'model': 'google/gemma-2-2b-it',
   'input_key': 'original_syllogism',
   'output_key': 'fol_otter_output_GemmaEng2FOLmultilingualNewShort',
   'output_type': 'list',
   'task_description': 'Translate multilingual sentences to First-Order Logic (Otter Syntax)',
   'system_prompt': 'MultiLingFOL',

In [220]:
exp = configs["experiments"]
models= []
for ex in exp.keys():
    models.append(exp[ex]["model"])

# models to set
models = set(models)
models

{'HuggingFaceTB/SmolLM2-1.7B-Instruct',
 'HuggingFaceTB/SmolLM2-135M-Instruct',
 'HuggingFaceTB/SmolLM3-3B',
 'Qwen/Qwen3-0.6B',
 'Qwen/Qwen3-1.7B',
 'Qwen/Qwen3-4B-Instruct-2507',
 'google/gemma-2-2b-it',
 'google/gemma-3-4b-it',
 'meta-llama/Llama-3.2-3B-Instruct'}

In [221]:
dataset

Dataset({
    features: ['id', 'syllogism', 'fol_otter_output_Eng2FOL', 'fol_otter_output_Eng2FOL10Qwen4B', 'fol_otter_output_Eng2FOL10', 'fol_otter_output_Eng2FOL11', 'fol_otter_output_Eng2FOL2', 'fol_otter_output_Eng2FOL3', 'fol_otter_output_Eng2FOL4', 'fol_otter_output_Eng2FOL5Gemma2B', 'fol_otter_output_Eng2FOL5Qwen0.6B', 'fol_otter_output_Eng2FOL5Qwen1.7B', 'fol_otter_output_Eng2FOL5Qwen4B', 'fol_otter_output_Eng2FOL5', 'fol_otter_output_Eng2FOL5small', 'fol_otter_output_Eng2FOL5tiny', 'fol_otter_output_Eng2FOL6', 'fol_otter_output_Eng2FOL7', 'fol_otter_output_Eng2FOL8', 'fol_otter_output_Eng2FOL9Qwen4B', 'fol_otter_output_Eng2FOL9', 'aristotelian_output_Eng2SyllogismProlog', 'fol_otter_output_QwenEng2FOL1', 'fol_otter_output_QwenEng2FOL2', 'fol_otter_output_QwenEng2FOL3', 'fol_otter_output_QwenEng2FOL5', 'fol_otter_output_QwenEng2FOL6', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2', 'fol_otter_output_SimpEng2FOL1', 'fol_otter_output_SimpEng2FOL2', 'aristotelian_output_SimpEng2SyllogismProlog', 'fol_output_from_syllogism', 'fol_output_from_syllogism_simplified_Simp1', 'fol_output_from_syllogism_simplified_Simp2', 'otter_used_clauses_fol_otter_output_Eng2FOL', 'otter_answer_fol_otter_output_Eng2FOL', 'otter_error_fol_otter_output_Eng2FOL', 'otter_input_cleaned_fol_otter_output_Eng2FOL', 'otter_proof_fol_otter_output_Eng2FOL', 'otter_used_clauses_fol_otter_output_Eng2FOL10Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL10Qwen4B', 'otter_error_fol_otter_output_Eng2FOL10Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL10Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL10Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL10', 'otter_answer_fol_otter_output_Eng2FOL10', 'otter_error_fol_otter_output_Eng2FOL10', 'otter_input_cleaned_fol_otter_output_Eng2FOL10', 'otter_proof_fol_otter_output_Eng2FOL10', 'otter_used_clauses_fol_otter_output_Eng2FOL11', 'otter_answer_fol_otter_output_Eng2FOL11', 'otter_error_fol_otter_output_Eng2FOL11', 'otter_input_cleaned_fol_otter_output_Eng2FOL11', 'otter_proof_fol_otter_output_Eng2FOL11', 'otter_used_clauses_fol_otter_output_Eng2FOL2', 'otter_answer_fol_otter_output_Eng2FOL2', 'otter_error_fol_otter_output_Eng2FOL2', 'otter_input_cleaned_fol_otter_output_Eng2FOL2', 'otter_proof_fol_otter_output_Eng2FOL2', 'otter_used_clauses_fol_otter_output_Eng2FOL3', 'otter_answer_fol_otter_output_Eng2FOL3', 'otter_error_fol_otter_output_Eng2FOL3', 'otter_input_cleaned_fol_otter_output_Eng2FOL3', 'otter_proof_fol_otter_output_Eng2FOL3', 'otter_used_clauses_fol_otter_output_Eng2FOL4', 'otter_answer_fol_otter_output_Eng2FOL4', 'otter_error_fol_otter_output_Eng2FOL4', 'otter_input_cleaned_fol_otter_output_Eng2FOL4', 'otter_proof_fol_otter_output_Eng2FOL4', 'otter_used_clauses_fol_otter_output_Eng2FOL5Gemma2B', 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B', 'otter_error_fol_otter_output_Eng2FOL5Gemma2B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Gemma2B', 'otter_proof_fol_otter_output_Eng2FOL5Gemma2B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_error_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_error_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen4B', 'otter_error_fol_otter_output_Eng2FOL5Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL5', 'otter_answer_fol_otter_output_Eng2FOL5', 'otter_error_fol_otter_output_Eng2FOL5', 'otter_input_cleaned_fol_otter_output_Eng2FOL5', 'otter_proof_fol_otter_output_Eng2FOL5', 'otter_used_clauses_fol_otter_output_Eng2FOL5small', 'otter_answer_fol_otter_output_Eng2FOL5small', 'otter_error_fol_otter_output_Eng2FOL5small', 'otter_input_cleaned_fol_otter_output_Eng2FOL5small', 'otter_proof_fol_otter_output_Eng2FOL5small', 'otter_used_clauses_fol_otter_output_Eng2FOL5tiny', 'otter_answer_fol_otter_output_Eng2FOL5tiny', 'otter_error_fol_otter_output_Eng2FOL5tiny', 'otter_input_cleaned_fol_otter_output_Eng2FOL5tiny', 'otter_proof_fol_otter_output_Eng2FOL5tiny', 'otter_used_clauses_fol_otter_output_Eng2FOL6', 'otter_answer_fol_otter_output_Eng2FOL6', 'otter_error_fol_otter_output_Eng2FOL6', 'otter_input_cleaned_fol_otter_output_Eng2FOL6', 'otter_proof_fol_otter_output_Eng2FOL6', 'otter_used_clauses_fol_otter_output_Eng2FOL7', 'otter_answer_fol_otter_output_Eng2FOL7', 'otter_error_fol_otter_output_Eng2FOL7', 'otter_input_cleaned_fol_otter_output_Eng2FOL7', 'otter_proof_fol_otter_output_Eng2FOL7', 'otter_used_clauses_fol_otter_output_Eng2FOL8', 'otter_answer_fol_otter_output_Eng2FOL8', 'otter_error_fol_otter_output_Eng2FOL8', 'otter_input_cleaned_fol_otter_output_Eng2FOL8', 'otter_proof_fol_otter_output_Eng2FOL8', 'otter_used_clauses_fol_otter_output_Eng2FOL9Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL9Qwen4B', 'otter_error_fol_otter_output_Eng2FOL9Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL9Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL9Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL9', 'otter_answer_fol_otter_output_Eng2FOL9', 'otter_error_fol_otter_output_Eng2FOL9', 'otter_input_cleaned_fol_otter_output_Eng2FOL9', 'otter_proof_fol_otter_output_Eng2FOL9', 'otter_used_clauses_fol_otter_output_QwenEng2FOL1', 'otter_answer_fol_otter_output_QwenEng2FOL1', 'otter_error_fol_otter_output_QwenEng2FOL1', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL1', 'otter_proof_fol_otter_output_QwenEng2FOL1', 'otter_used_clauses_fol_otter_output_QwenEng2FOL2', 'otter_answer_fol_otter_output_QwenEng2FOL2', 'otter_error_fol_otter_output_QwenEng2FOL2', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL2', 'otter_proof_fol_otter_output_QwenEng2FOL2', 'otter_used_clauses_fol_otter_output_QwenEng2FOL3', 'otter_answer_fol_otter_output_QwenEng2FOL3', 'otter_error_fol_otter_output_QwenEng2FOL3', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL3', 'otter_proof_fol_otter_output_QwenEng2FOL3', 'otter_used_clauses_fol_otter_output_QwenEng2FOL5', 'otter_answer_fol_otter_output_QwenEng2FOL5', 'otter_error_fol_otter_output_QwenEng2FOL5', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL5', 'otter_proof_fol_otter_output_QwenEng2FOL5', 'otter_used_clauses_fol_otter_output_QwenEng2FOL6', 'otter_answer_fol_otter_output_QwenEng2FOL6', 'otter_error_fol_otter_output_QwenEng2FOL6', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL6', 'otter_proof_fol_otter_output_QwenEng2FOL6', 'otter_used_clauses_fol_otter_output_SimpEng2FOL1', 'otter_answer_fol_otter_output_SimpEng2FOL1', 'otter_error_fol_otter_output_SimpEng2FOL1', 'otter_input_cleaned_fol_otter_output_SimpEng2FOL1', 'otter_proof_fol_otter_output_SimpEng2FOL1', 'otter_used_clauses_fol_otter_output_SimpEng2FOL2', 'otter_answer_fol_otter_output_SimpEng2FOL2', 'otter_error_fol_otter_output_SimpEng2FOL2', 'otter_input_cleaned_fol_otter_output_SimpEng2FOL2', 'otter_proof_fol_otter_output_SimpEng2FOL2', 'otter_used_clauses_fol_output_from_syllogism', 'otter_answer_fol_output_from_syllogism', 'otter_error_fol_output_from_syllogism', 'otter_input_cleaned_fol_output_from_syllogism', 'otter_proof_fol_output_from_syllogism', 'otter_used_clauses_fol_output_from_syllogism_simplified_Simp1', 'otter_answer_fol_output_from_syllogism_simplified_Simp1', 'otter_error_fol_output_from_syllogism_simplified_Simp1', 'otter_input_cleaned_fol_output_from_syllogism_simplified_Simp1', 'otter_proof_fol_output_from_syllogism_simplified_Simp1', 'otter_used_clauses_fol_output_from_syllogism_simplified_Simp2', 'otter_answer_fol_output_from_syllogism_simplified_Simp2', 'otter_error_fol_output_from_syllogism_simplified_Simp2', 'otter_input_cleaned_fol_output_from_syllogism_simplified_Simp2', 'otter_proof_fol_output_from_syllogism_simplified_Simp2', 'aristotelian_output_from_syllogism', 'aristotelian_output_from_syllogism_simplified_Simp1', 'aristotelian_output_from_syllogism_simplified_Simp2', 'Eng2SyllogismProlog_aristotelian_truth', 'Eng2SyllogismProlog_aristotelian_type', 'SimpEng2SyllogismProlog_aristotelian_truth', 'SimpEng2SyllogismProlog_aristotelian_type', 'from_syllogism_aristotelian_truth', 'from_syllogism_aristotelian_type', 'from_syllogism_simplified_Simp1_aristotelian_truth', 'from_syllogism_simplified_Simp1_aristotelian_type', 'from_syllogism_simplified_Simp2_aristotelian_truth', 'from_syllogism_simplified_Simp2_aristotelian_type', 'validity', 'plausibility'],
    num_rows: 191
})

## Generate simplified version (only on GPU)

In [1071]:
configs['experiments'].keys()

dict_keys(['Simp1', 'Simp2', 'Eng2SyllogismProlog', 'SimpEng2SyllogismProlog', 'Eng2FOL', 'SimpEng2FOL1', 'SimpEng2FOL2', 'Eng2FOL2', 'Eng2FOL3', 'Eng2FOL4', 'Eng2FOL5', 'Eng2FOL6', 'Eng2FOL7', 'Eng2FOL5multilingual', 'Eng2FOL5small', 'Eng2FOL5tiny', 'Eng2FOL5Gemma2B', 'Eng2FOL5Qwen1.7B', 'Eng2FOL5Qwen0.6B', 'Eng2FOL5Qwen4B', 'Eng2FOL8', 'Eng2FOLmultilingualNew', 'Eng2FOLmultilingualNewShort', 'Eng2FOL5multilingualNew', 'Eng2FOL5multilingualNewShort', 'QwenEng2FOL1', 'QwenEng2FOL2', 'QwenEng2FOL3', 'QwenEng2FOL4', 'QwenEng2FOL5', 'QwenEng2FOL6', 'QwenEng2FOL5multilingual', 'QwenEng2FOLmultilingualNew', 'QwenEng2FOLmultilingualNewShort', 'QwenEng2FOL5multilingualNew', 'QwenEng2FOL5multilingualNewShort', 'Eng2FOL9', 'Eng2FOL9Qwen4B', 'Eng2FOL10', 'Eng2FOL10Qwen4B', 'GemmaEng2FOL5multilingualNewShort', 'GemmaEng2FOLmultilingualNewShort', 'Gemma3Eng2FOL5multilingualNewShort', 'Gemma3Eng2FOLmultilingualNewShort', 'Gemma3Eng2FOLmultilingualNew', 'NEWQwenEng2FOL8', 'NEWEng2FOL9', 'NEWEng2FOL10'])

In [409]:
import inspect
#from reasoning.generate_utils import format_to_prompt

#print(inspect.getsource(format_to_prompt))

In [410]:
import torch
from google.colab import files
from transformers import AutoTokenizer


# All comments in English
import torch
from google.colab import files
from transformers import AutoTokenizer

# list of experiments to run
experiment_ids_list = ['Simp1', 'Simp2', 'Eng2SyllogismProlog', 'SimpEng2SyllogismProlog', 'Eng2FOL', 'SimpEng2FOL1', 'SimpEng2FOL2', 'Eng2FOL2', 'Eng2FOL3', 'Eng2FOL4', 'Eng2FOL5', 'Eng2FOL6', 'Eng2FOL7', 'Eng2FOL5multilingual', 'Eng2FOL5small', 'Eng2FOL5tiny', 'Eng2FOL5Gemma2B', 'Eng2FOL5Qwen1.7B', 'Eng2FOL5Qwen0.6B', 'Eng2FOL5Qwen4B', 'Eng2FOL8', 'Eng2FOLmultilingualNew', 'Eng2FOLmultilingualNewShort', 'Eng2FOL5multilingualNew', 'Eng2FOL5multilingualNewShort', 'QwenEng2FOL1', 'QwenEng2FOL2', 'QwenEng2FOL3', 'QwenEng2FOL4', 'QwenEng2FOL5', 'QwenEng2FOL6']
experiment_ids_list = ['QwenEng2FOL6','QwenEng2FOL5','Eng2FOL5Qwen4B'] # subtask 1
experiment_ids_list = ['QwenEng2FOL1','QwenEng2FOL6','QwenEng2FOL5','Eng2FOL5Qwen4B'] # subtask 2
#experiment_ids_list = ['QwenEng2FOL5multilingual','QwenEng2FOLmultilingualNew', 'QwenEng2FOLmultilingualNewShort', 'QwenEng2FOL5multilingualNew', 'QwenEng2FOL5multilingualNewShort','Eng2FOL5multilingual','Eng2FOLmultilingualNew','QwenEng2FOL6','QwenEng2FOL5','Eng2FOL5Qwen4B'] # subtask 3
#experiment_ids_list = ['QwenEng2FOL5multilingual','QwenEng2FOLmultilingualNew', 'QwenEng2FOLmultilingualNewShort', 'QwenEng2FOL5multilingualNew', 'QwenEng2FOL5multilingualNewShort','Eng2FOL5multilingual','Eng2FOLmultilingualNew','QwenEng2FOL6','QwenEng2FOL5','Eng2FOL5Qwen4B'] # subtask 4
#experiment_ids_list = ['Eng2FOL6', 'Eng2FOL7', 'Eng2FOL5small', 'Eng2FOL5Gemma2B', 'Eng2FOL8','QwenEng2FOL1', 'QwenEng2FOL2', 'QwenEng2FOL3', 'QwenEng2FOL4'] # subtask 1 fehlende

if "subtask3" in data_type or "subtask4" in data_type:
    # do nothing, keep all experiments
    experiments_ids_list = experiment_ids_list
else:
    # remove multilanguage experiments for other data types
    experiment_ids_list = [x for x in experiment_ids_list if "multil" not in x]

# IMPORTANT: 'dataset' must be loaded before this loop starts.
# It will accumulate new columns in each iteration.

import gc
import torch
import os

for i, experiment_id in enumerate(experiment_ids_list, start=1):
    out_name = f"/content/{data_type}_{experiment_id}_results.parquet"

    # Check if this experiment was already completed (Resume-Logic)
    if os.path.exists(out_name):
        print(f"⏭️ Skipping {experiment_id}, file already exists: {out_name}")
        # Optionally: reload dataset from last file to ensure we have all columns
        # dataset = load_data(out_name)
        continue

    print(f"\n{'='*60}")
    print(f"🚀 Starting Experiment {i}/{len(experiment_ids_list)}: {experiment_id}")
    print(f"{'='*60}")

    # 1. Load specific config
    cfg = get_experiment_config(experiment_id)

    # 2. Setup Tokenizer inside the loop
    tokenizer = AutoTokenizer.from_pretrained(cfg['model'])

    # 3. Format prompts
    dataset = dataset.map(
        lambda x: format_to_prompt(x, cfg, tokenizer=tokenizer),
        batched=False,
        load_from_cache_file=False
    )

    # 4. Clear CUDA before generation
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # 5. Run Generation
    print(f"🤖 Generating results for {len(dataset)} items...")
    dataset = generate_with_prompt(dataset, cfg)

    # 6. Save and Download
    save_data(dataset, out_name)
    print(f"💾 Saved cumulative results to {out_name}")

    try:
        files.download(out_name)
    except:
        print(f"ℹ️ Manual download required for {out_name}")

    # --- NEW: EXPLICIT MEMORY CLEANUP ---
    # Delete temporary objects that are re-created in the next iteration
    del tokenizer
    if 'prompt' in dataset.column_names:
        # Optional: remove the prompt column to save RAM, as it's regenerated anyway
        dataset = dataset.remove_columns(['prompt'])

    # Force Garbage Collection
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    gc.collect()

    print(f"✨ Finished Experiment: {experiment_id} | RAM cleared.")

print("\n✅ All experiments in the list have been processed.")

ModuleNotFoundError: No module named 'google.colab'

In [411]:
dataset[4]

{'id': '6e672b31-84e2-4b83-92ca-30f90e27bd00',
 'syllogism': 'There are no mammals that are fish. Among the fish, a few are canines. Not all canines are mammals.',
 'validity': True,
 'plausibility': False,
 'syllogism_simplified_Simp1': ['no Mammal is Fish',
  'some Fish is Canine',
  'not_all Canine is Mammal'],
 'syllogism_simplified_Simp2': ['no Mammal is Fish',
  'some Fish is Canine',
  'not all Canine is Mammal'],
 'aristotelian_output_Eng2SyllogismProlog': ["('e', 'Mammal', 'Fish')",
  "('i', 'Fish', 'Canine')",
  "('o', 'Canine', 'Mammal')"],
 'aristotelian_output_SimpEng2SyllogismProlog': ["('e', 'Mammal', 'Fish')",
  "('i', 'Fish', 'Canine')",
  "('o', 'Canine', 'Mammal')"],
 'fol_otter_output_Eng2FOL': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_Eng2FOL2': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> Mammal(x) )',
  'all x ( Canine(x) -> -Fish(x) )'],
 'fol_otter_output_Eng2FOL3': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_Eng2FOL4': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_Eng2FOL5Gemma2B': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_Eng2FOL5Qwen0.6B': ['exists x ( Fish(x) & Canine(x) )',
  'all x ( Fish(x) -> -Mammal(x) )',
  'all x ( Canine(x) -> Mammal(x) )'],
 'fol_otter_output_Eng2FOL5Qwen1.7B': ['all x ( Mammal(x) <-> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'not all x ( Canine(x) -> Mammal(x) )'],
 'fol_otter_output_Eng2FOL5Qwen4B': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'exists x ( Canine(x) & -Mammal(x) )'],
 'fol_otter_output_Eng2FOL5': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'exists x ( Canine(x) & -Mammal(x) )'],
 'fol_otter_output_Eng2FOL5small': ['all x ( Fish(x) -> -Mammal(x) )',
  'exists x ( Fish(x) & -Mammal(x) )',
  'exists x ( Canine(x) & -Mammal(x) )',
  'all x ( Canine(x) -> Mammal(x) )'],
 'fol_otter_output_Eng2FOL5tiny': ['exists x ( Canine(x) & -Fish(x) )',
  'exists x ( Canine(x) & -Fish(x) | -Mammal(x) )',
  'exists x ( Mammal(x) & -Fish(x) | -Canine(x) )'],
 'fol_otter_output_Eng2FOL6': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_Eng2FOL7': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'exists x ( Canine(x) & -Mammal(x) )'],
 'fol_otter_output_Eng2FOL8': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_QwenEng2FOL1': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_QwenEng2FOL2': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'exists x ( Canine(x) & -Mammal(x) )'],
 'fol_otter_output_QwenEng2FOL3': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'exists x ( Canine(x) & -Mammal(x) )'],
 'fol_otter_output_QwenEng2FOL4': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_QwenEng2FOL5': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_QwenEng2FOL6': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'exists x ( Canine(x) & -Mammal(x) )'],
 'fol_otter_output_SimpEng2FOL1': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'all x ( Canine(x) -> -Mammal(x) )'],
 'fol_otter_output_SimpEng2FOL2': ['all x ( Mammal(x) -> -Fish(x) )',
  'exists x ( Fish(x) & Canine(x) )',
  'not all x ( Canine(x) -> Mammal(x) )'],
 'fol_output_from_syllogism': ['ERROR_UNPARSABLE: There are no mammals that are fish. Among the fish, a few are canines. Not all canines are mammals.'],
 'fol_output_from_syllogism_simplified_Simp1': ['all x (Mammal(x) -> -Fish(x))',
  'exists x (Fish(x) & Canine(x))',
  'all x (Canine(x) -> Mammal(x))'],
 'fol_output_from_syllogism_simplified_Simp2': ['all x (Mammal(x) -> -Fish(x))',
  'exists x (Fish(x) & Canine(x))',
  'exists x (Canine(x) & -Mammal(x))'],
 'otter_answer_fol_otter_output_Eng2FOL': False,
 'otter_error_fol_otter_output_Eng2FOL': None,
 'otter_input_cleaned_fol_otter_output_Eng2FOL': 'set(auto).\nset(formula_history).\nassign(max_seconds, 15).\n\nformula_list(usable).\nall a (Mammal(a) -> -Fish(a)).\nexists a (Fish(a) & Canine(a)).\n% separation marker: end of original premises.\nexists a (Mammal(a)).\n-(all a (Canine(a) -> -Mammal(a))).\nend_of_list.\n',
 'otter_proof_fol_otter_output_Eng2FOL': '----- Otter 3.3, August 2003 -----\r\nThe process was started by a Windows user on a Windows machine,\r\nSat Jan 31 18:51:52 2026\r\nThe command was "otter".\r\n\r\nset(auto).\r\n   dependent: set(auto1).\r\n   dependent: set(process_input).\r\n   dependent: clear(print_kept).\r\n   dependent: clear(print_new_demod).\r\n   dependent: clear(print_back_demod).\r\n   dependent: clear(print_back_sub).\r\n   dependent: set(control_memory).\r\n   dependent: assign(max_mem, 12000).\r\n   dependent: assign(pick_given_ratio, 4).\r\n   dependent: assign(stats_level, 1).\r\n   dependent: assign(max_seconds, 10800).\r\nset(formula_history).\r\nassign(max_seconds,15).\r\n\r\nformula_list(usable).\r\nall a (Mammal(a)-> -Fish(a)).\r\nexists a (Fish(a)&Canine(a)).\r\nexists a Mammal(a).\r\n-(all a (Canine(a)-> -Mammal(a))).\r\nend_of_list.\r\n\r\n-------> usable clausifies to:\r\n\r\nlist(usable).\r\n0 [clausify,1] -Mammal(x1)| -Fish(x1).\r\n0 [clausify,2] Fish($c1).\r\n0 [clausify,2] Canine($c1).\r\n0 [clausify,3] Mammal($c2).\r\n0 [clausify,4] Canine($c3).\r\n0 [clausify,4] Mammal($c3).\r\nend_of_list.\r\n\r\nSCAN INPUT: prop=0, horn=1, equality=0, symmetry=0, max_lits=2.\r\n\r\nThis is a Horn set without equality.  The strategy will\r\nbe hyperresolution, with satellites in sos and nuclei\r\nin usable.\r\n\r\n   dependent: set(hyper_res).\r\n   dependent: clear(order_hyper).\r\n\r\n------------> process usable:\r\n** KEPT (pick-wt=4): 5 [clausify,1] -Mammal(x)| -Fish(x).\r\n\r\n------------> process sos:\r\n** KEPT (pick-wt=2): 6 [clausify,2] Fish($c1).\r\n** KEPT (pick-wt=2): 7 [clausify,2] Canine($c1).\r\n** KEPT (pick-wt=2): 8 [clausify,3] Mammal($c2).\r\n** KEPT (pick-wt=2): 9 [clausify,4] Canine($c3).\r\n** KEPT (pick-wt=2): 10 [clausify,4] Mammal($c3).\r\n\r\n======= end of input processing =======\r\n\r\n=========== start of search ===========\r\n\r\ngiven clause #1: (wt=2) 6 [clausify,2] Fish($c1).\r\n\r\ngiven clause #2: (wt=2) 7 [clausify,2] Canine($c1).\r\n\r\ngiven clause #3: (wt=2) 8 [clausify,3] Mammal($c2).\r\n\r\ngiven clause #4: (wt=2) 9 [clausify,4] Canine($c3).\r\n\r\ngiven clause #5: (wt=2) 10 [clausify,4] Mammal($c3).\r\n\r\nSearch stopped because sos empty.\r\n\r\n============ end of search ============\r\n\r\n-------------- statistics -------------\r\nclauses given                  5\r\nclauses generated              0\r\nclauses kept                   6\r\nclauses forward subsumed       0\r\nclauses back subsumed          0\r\nKbytes malloced              159\r\n\r\n----------- times (seconds) -----------\r\nuser CPU time          0.00          (0 hr, 0 min, 0 sec)\r\nsystem CPU time        0.00          (0 hr, 0 min, 0 sec)\r\nwall-clock time        0             (0 hr, 0 min, 0 sec)\r\nhyper_res time         0.00\r\nfor_sub time           0.00\r\nback_sub time          0.00\r\nconflict time          0.00\r\n\r\nProcess 0 finished Sat Jan 31 18:51:52 2026\r\n',
 'otter_used_clauses_fol_otter_output_Eng2FOL': [],
 'otter_answer_fol_otter_output_Eng2FOL2': True,
 'otter_error_fol_otter_output_Eng2FOL2': None,
 'otter_input_cleaned_fol_otter_output_Eng2FOL2': 'set(auto).\nset(formula_history).\nassign(max_seconds, 15).\n\nformula_list(usable).\nall a (Mammal(a) -> -Fish(a)).\nexists a (Fish(a) & Canine(a)).\nall a (Canine(a) -> Mammal(a)).\n% separation marker: end of original premises.\nexists a (Mammal(a)).\n-(all a (Canine(a) -> -Fish(a))).\nend_of_list.\n',
 'otter_proof_fol_otter_output_Eng2FOL2': '----- Otter 3.3, August 2003 -----\r\nThe process was started by a Windows user on a Windows machine,\r\nSat Jan 31 18:51:53 2026\r\nThe command was "otter".\r\n\r\nset(auto).\r\n   dependent: set(auto1).\r\n   dependent: set(process_input).\r\n   dependent: clear(print_kept).\r\n   dependent: clear(print_new_demod).\r\n   dependent: clear(print_back_demod).\r\n   dependent: clear(print_back_sub).\r\n   dependent: set(control_memory).\r\n   dependent: assign(max_mem, 12000).\r\n   dependent: assign(pick_given_ratio, 4).\r\n   dependent: assign(stats_level, 1).\r\n   dependent: assign(max_seconds, 10800).\r\nset(formula_history).\r\nassign(max_seconds,15).\r\n\r\nformula_list(usable).\r\nall a (Mammal(a)-> -Fish(a)).\r\nexists a (Fish(a)&Canine(a)).\r\nall a (Canine(a)->Mammal(a)).\r\nexists a Mammal(a).\r\n-(all a (Canine(a)-> -Fish(a))).\r\nend_of_list.\r\n\r\n-------> usable clausifies to:\r\n\r\nlist(usable).\r\n0 [clausify,1] -Mammal(x1)| -Fish(x1).\r\n0 [clausify,2] Fish($c1).\r\n0 [clausify,2] Canine($c1).\r\n0 [clausify,3] -Canine(x2)|Mammal(x2).\r\n0 [clausify,4] Mammal($c2).\r\n0 [clausify,5] Canine($c3).\r\n0 [clausify,5] Fish($c3).\r\nend_of_list.\r\n\r\nSCAN INPUT: prop=0, horn=1, equality=0, symmetry=0, max_lits=2.\r\n\r\nThis is a Horn set without equality.  The strategy will\r\nbe hyperresolution, with satellites in sos and nuclei\r\nin usable.\r\n\r\n   dependent: set(hyper_res).\r\n   dependent: clear(order_hyper).\r\n\r\n------------> process usable:\r\n** KEPT (pick-wt=4): 6 [clausify,1] -Mammal(x)| -Fish(x).\r\n** KEPT (pick-wt=4): 7 [clausify,3] -Canine(x)|Mammal(x).\r\n\r\n------------> process sos:\r\n** KEPT (pick-wt=2): 8 [clausify,2] Fish($c1).\r\n** KEPT (pick-wt=2): 9 [clausify,2] Canine($c1).\r\n** KEPT (pick-wt=2): 10 [clausify,4] Mammal($c2).\r\n** KEPT (pick-wt=2): 11 [clausify,5] Canine($c3).\r\n** KEPT (pick-wt=2): 12 [clausify,5] Fish($c3).\r\n\r\n======= end of input processing =======\r\n\r\n=========== start of search ===========\r\n\r\ngiven clause #1: (wt=2) 8 [clausify,2] Fish($c1).\r\n\r\ngiven clause #2: (wt=2) 9 [clausify,2] Canine($c1).\r\n\r\ngiven clause #3: (wt=2) 10 [clausify,4] Mammal($c2).\r\n\r\ngiven clause #4: (wt=2) 11 [clausify,5] Canine($c3).\r\n\r\ngiven clause #5: (wt=2) 12 [clausify,5] Fish($c3).\r\n\r\ngiven clause #6: (wt=2) 13 [hyper,9,7] Mammal($c1).\r\n\r\n-----> EMPTY CLAUSE at   0.00 sec ----> 15 [hyper,13,6,8] $F.\r\n\r\nLength of proof is 5.  Level of proof is 2.\r\n\r\n---------------- PROOF ----------------\r\n\r\n1 [] all a (Mammal(a)-> -Fish(a)).\r\n2 [] exists a (Fish(a)&Canine(a)).\r\n3 [] all a (Canine(a)->Mammal(a)).\r\n6 [clausify,1] -Mammal(x)| -Fish(x).\r\n7 [clausify,3] -Canine(x)|Mammal(x).\r\n8 [clausify,2] Fish($c1).\r\n9 [clausify,2] Canine($c1).\r\n13 [hyper,9,7] Mammal($c1).\r\n15 [hyper,13,6,8] $F.\r\n\r\n------------ end of proof -------------\r\n\r\n\r\nSearch stopped by max_proofs option.\r\n\r\n============ end of search ============\r\n\r\n-------------- statistics -------------\r\nclauses given                  6\r\nclauses generated              3\r\nclauses kept                   9\r\nclauses forward subsumed       0\r\nclauses back subsumed          0\r\nKbytes malloced              191\r\n\r\n----------- times (seconds) -----------\r\nuser CPU time          0.00          (0 hr, 0 min, 0 sec)\r\nsystem CPU time        0.00          (0 hr, 0 min, 0 sec)\r\nwall-clock time        0             (0 hr, 0 min, 0 sec)\r\nhyper_res time         0.00\r\nfor_sub time           0.00\r\nback_sub time          0.00\r\nconflict time          0.00\r\ndemod time             0.00\r\n\r\nThat finishes the proof of the theorem.\r\n\r\nProcess 0 finished Sat Jan 31 18:51:53 2026\r\n',
 'otter_used_clauses_fol_otter_output_Eng2FOL2': [0, 1, 2],
 'otter_answer_fol_otter_output_Eng2FOL3': False,
 'otter_error_fol_otter_output_Eng2FOL3': None,
 'otter_input_cleaned_fol_otter_output_Eng2FOL3': 'set(auto).\nset(formula_history).\nassign(max_seconds, 15).\n\nformula_list(usable).\nall a (Mammal(a) -> -Fish(a)).\nexists a (Fish(a) & Canine(a)).\n% separation marker: end of original premises.\nexists a (Mammal(a)).\n-(all a (Canine(a) -> -Mammal(a))).\nend_of_list.\n',
 'otter_proof_fol_otter_output_Eng2FOL3': '----- Otter 3.3, August 2003 -----\r\nThe process was started by a Windows user on a Windows machine,\r\nSat Jan 31 18:51:55 2026\r\nThe command was "otter".\r\n\r\nset(auto).\r\n   dependent: set(auto1).\r\n   dependent: set(process_input).\r\n   dependent: clear(print_kept).\r\n   dependent: clear(print_new_demod).\r\n   dependent: clear(print_back_demod).\r\n   dependent: clear(print_back_sub).\r\n   dependent: set(control_memory).\r\n   dependent: assign(max_mem, 12000).\r\n   dependent: assign(pick_given_ratio, 4).\r\n   dependent: assign(stats_level, 1).\r\n   dependent: assign(max_seconds, 10800).\r\nset(formula_history).\r\nassign(max_seconds,15).\r\n\r\nformula_list(usable).\r\nall a (Mammal(a)-> -Fish(a)).\r\nexists a (Fish(a)&Canine(a)).\r\nexists a Mammal(a).\r\n-(all a (Canine(a)-> -Mammal(a))).\r\nend_of_list.\r\n\r\n-------> usable clausifies to:\r\n\r\nlist(usable).\r\n0 [clausify,1] -Mammal(x1)| -Fish(x1).\r\n0 [clausify,2] Fish($c1).\r\n0 [clausify,2] Canine($c1).\r\n0 [clausify,3] Mammal($c2).\r\n0 [clausify,4] Canine($c3).\r\n0 [clausify,4] Mammal($c3).\r\nend_of_list.\r\n\r\nSCAN INPUT: prop=0, horn=1, equality=0, symmetry=0, max_lits=2.\r\n\r\nThis is a Horn set without equality.  The strategy will\r\nbe hyperresolution, with satellites in sos and nuclei\r\nin usable.\r\n\r\n   dependent: set(hyper_res).\r\n   dependent: clear(order_hyper).\r\n\r\n------------> process usable:\r\n** KEPT (pick-wt=4): 5 [clausify,1] -Mammal(x)| -Fish(x).\r\n\r\n------------> process sos:\r\n** KEPT (pick-wt=2): 6 [clausify,2] Fish($c1).\r\n** KEPT (pick-wt=2): 7 [clausify,2] Canine($c1).\r\n** KEPT (pick-wt=2): 8 [clausify,3] Mammal($c2).\r\n** KEPT (pick-wt=2): 9 [clausify,4] Canine($c3).\r\n** KEPT (pick-wt=2): 10 [clausify,4] Mammal($c3).\r\n\r\n======= end of input processing =======\r\n\r\n=========== start of search ===========\r\n\r\ngiven clause #1: (wt=2) 6 [clausify,2] Fish($c1).\r\n\r\ngiven clause #2: (wt=2) 7 [clausify,2] Canine($c1).\r\n\r\ngiven clause #3: (wt=2) 8 [clausify,3] Mammal($c2).\r\n\r\ngiven clause #4: (wt=2) 9 [clausify,4] Canine($c3).\r\n\r\ngiven clause #5: (wt=2) 10 [clausify,4] Mammal($c3).\r\n\r\nSearch stopped because sos empty.\r\n\r\n============ end of search ============\r\n\r\n-------------- statistics -------------\r\nclauses given                  5\r\nclauses generated              0\r\nclauses kept                   6\r\nclauses forward subsumed       0\r\nclauses back subsumed          0\r\nKbytes malloced              159\r\n\r\n----------- times (seconds) -----------\r\nuser CPU time          0.00          (0 hr, 0 min, 0 sec)\r\nsystem CPU time        0.00          (0 hr, 0 min, 0 sec)\r\nwall-clock time        0             (0 hr, 0 min, 0 sec)\r\nhyper_res time         0.00\r\nfor_sub time           0.00\r\nback_sub time          0.00\r\nconflict time          0.00\r\n\r\nProcess 0 finished Sat Jan 31 18:51:55 2026\r\n',
 'otter_used_clauses_fol_otter_output_Eng2FOL3': [],
 'otter_answer_fol_otter_output_Eng2FOL4': False,
 'otter_error_fol_otter_output_Eng2FOL4': None,
 'otter_input_cleaned_fol_otter_output_Eng2FOL4': 'set(auto).\nset(formula_history).\nassign(max_seconds, 15).\n\nformula_list(usable).\nall a (Mammal(a) -> -Fish(a)).\nexists a (Fish(a) & Canine(a)).\n% separation marker: end of original premises.\nexists a (Mammal(a)).\n-(all a (Canine(a) -> -Mammal(a))).\nend_of_list.\n',
 'otter_proof_fol_otter_output_Eng2FOL4': '----- Otter 3.3, August 2003 -----\r\nThe process was started by a Windows user on a Windows machine,\r\nSat Jan 31 18:51:57 2026\r\nThe command was "otter".\r\n\r\nset(auto).\r\n   dependent: set(auto1).\r\n   dependent: set(process_input).\r\n   dependent: clear(print_kept).\r\n   dependent: clear(print_new_demod).\r\n   dependent: clear(print_back_demod).\r\n   dependent: clear(print_back_sub).\r\n   dependent: set(control_memory).\r\n   dependent: assign(max_mem, 12000).\r\n   dependent: assign(pick_given_ratio, 4).\r\n   dependent: assign(stats_level, 1).\r\n   dependent: assign(max_seconds, 10800).\r\nset(formula_history).\r\nassign(max_seconds,15).\r\n\r\nformula_list(usable).\r\nall a (Mammal(a)-> -Fish(a)).\r\nexists a (Fish(a)&Canine(a)).\r\nexists a Mammal(a).\r\n-(all a (Canine(a)-> -Mammal(a))).\r\nend_of_list.\r\n\r\n-------> usable clausifies to:\r\n\r\nlist(usable).\r\n0 [clausify,1] -Mammal(x1)| -Fish(x1).\r\n0 [clausify,2] Fish($c1).\r\n0 [clausify,2] Canine($c1).\r\n0 [clausify,3] Mammal($c2).\r\n0 [clausify,4] Canine($c3).\r\n0 [clausify,4] Mammal($c3).\r\nend_of_list.\r\n\r\nSCAN INPUT: prop=0, horn=1, equality=0, symmetry=0, max_lits=2.\r\n\r\nThis is a Horn set without equality.  The strategy will\r\nbe hyperresolution, with satellites in sos and nuclei\r\nin usable.\r\n\r\n   dependent: set(hyper_res).\r\n   dependent: clear(order_hyper).\r\n\r\n------------> process usable:\r\n** KEPT (pick-wt=4): 5 [clausify,1] -Mammal(x)| -Fish(x).\r\n\r\n------------> process sos:\r\n** KEPT (pick-wt=2): 6 [clausify,2] Fish($c1).\r\n** KEPT (pick-wt=2): 7 [clausify,2] Canine($c1).\r\n** KEPT (pick-wt=2): 8 [clausify,3] Mammal($c2).\r\n** KEPT (pick-wt=2): 9 [clausify,4] Canine($c3).\r\n** KEPT (pick-wt=2): 10 [clausify,4] Mammal($c3).\r\n\r\n======= end of input processing =======\r\n\r\n=========== start of search ===========\r\n\r\ngiven clause #1: (wt=2) 6 [clausify,2] Fish($c1).\r\n\r\ngiven clause #2: (wt=2) 7 [clausify,2] Canine($c1).\r\n\r\ngiven clause #3: (wt=2) 8 [clausify,3] Mammal($c2).\r\n\r\ngiven clause #4: (wt=2) 9 [clausify,4] Canine($c3).\r\n\r\ngiven clause #5: (wt=2) 10 [clausify,4] Mammal($c3).\r\n\r\nSearch stopped because sos empty.\r\n\r\n============ end of search ============\r\n\r\n-------------- statistics -------------\r\nclauses given                  5\r\nclauses generated              0\r\nclauses kept                   6\r\nclauses forward subsumed       0\r\nclauses back subsumed          0\r\nKbytes malloced              159\r\n\r\n----------- times (seconds) -----------\r\nuser CPU time          0.00          (0 hr, 0 min, 0 sec)\r\nsystem CPU time        0.00          (0 hr, 0 min, 0 sec)\r\nwall-clock time        0             (0 hr, 0 min, 0 sec)\r\nhyper_res time         0.00\r\nfor_sub time           0.00\r\nback_sub time          0.00\r\nconflict time          0.00\r\n\r\nProcess 0 finished Sat Jan 31 18:51:57 2026\r\n',
 'otter_used_clauses_fol_otter_output_Eng2FOL4': [],
 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B': False,
 'otter_error_fol_otter_output_Eng2FOL5Gemma2B': None,
 'otter_input_cleaned_fol_otter_output_Eng2FOL5Gemma2B': 'set(auto).\nset(formula_history).\nassign(max_seconds, 15).\n\nformula_list(usable).\nall a (Mammal(a) -> -Fish(a)).\nexists a (Fish(a) & Canine(a)).\n% separation marker: end of original premises.\nexists a (Mammal(a)).\n-(all a (Canine(a) -> -Mammal(a))).\nend_of_list.\n',

In [ ]:
#DNI

import torch
import json
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset
from tqdm import tqdm

# 1. Setup Model and Tokenizer
model_id = "HuggingFaceTB/SmolLM3-3B" # Ensure this is the 3B path
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id, 
    torch_dtype=torch.bfloat16 if device == "cuda" else torch.float32,
    device_map="auto"
)

def run_dni_session(hf_dataset, data_type_name):
    results = []
    
    print(f"Running DNI inference for {data_type_name}...")
    
    for example in tqdm(hf_dataset):
        # Enhanced Prompt focusing on logic over plausibility
        prompt = (
            "Instruction: Analyze the following syllogism. Determine if the conclusion logically follows "
            "from the given premises. \n"
            "CRITICAL: Base your decision ONLY on logical validity. Ignore the plausibility or "
            "factual truth of the statements. Even if a statement sounds unrealistic, check only if "
            "it is logically derived.\n\n"
            "Respond ONLY with 'True' or 'False'.\n\n"
            f"Syllogism: {example['syllogism']}\n\n"
            "Result:"
        )
        
        inputs = tokenizer(prompt, return_tensors="pt").to(device)
        
        with torch.no_grad():
            outputs = model.generate(
                **inputs, 
                max_new_tokens=5, 
                do_sample=False,
                temperature = 0.0
            )
        
        # Decode and clean
        response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
        if not response:
            prediction = "Error"
        else:
            # Check if 'true' or 'false' is anywhere in the first few words
            clean_response = response.lower()
            if "true" in clean_response:
                prediction = True
            elif "false" in clean_response:
                prediction = False
            else:
                # Fallback: take the first word if neither 'true' nor 'false' was found
                words = response.split()
                prediction = words[0].replace('.', '').replace(',', '') if words else "Error_Unknown"        
        # Store with ID and Prediction
        results.append({
            "id": example["id"],
            "dni_validity": prediction
        })
    return results

# Beispielaufruf:
results =run_dni_session(dataset, data_type)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

OSError: Die Auslagerungsdatei ist zu klein, um diesen Vorgang durchzuführen. (os error 1455)

In [ ]:

filename = f"{data_type}_dni_predictions.json"
with open(filename, "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)
    
print(f"Results saved to {filename}")

## Read in generated data locally

In [5]:
# All comments in English
import os
import re
from pathlib import Path
from datasets import load_dataset, concatenate_datasets
import yaml



def collect_all_results(base_file_path, data_type, folder_path=None, config_path="experiments.yaml"):
    """
    Sammelt Ergebnisse und merget sie in den Master-Datensatz.
    - Metadaten (z.B. prompt, validity) werden ignoriert, wenn sie schon da sind.
    - NUR die Spalte des aktuellen Experiments (output_key) wird im Master überschrieben.
    """
    if folder_path is None:
        folder_path = f"output/generated_output/{data_type}"

    # 1. Basis-Datensatz laden
    print(f"📦 Loading base dataset: {base_file_path}")
    master_ds = load_dataset("parquet", data_files=base_file_path, split="train")

    with open(config_path, 'r') as f:
        full_config = yaml.safe_load(f)['experiments']

    folder = Path(folder_path)
    result_files = sorted(list(folder.glob("*.parquet")), key=lambda x: x.name)
    base_name = Path(base_file_path).name

    overwritten_experiments = []

    for file in result_files:
        if file.name == base_name or not file.name.startswith(f"{data_type}_"):
            continue

        # Experiment ID extrahieren (z.B. Eng2FOL5Gemma2B)
        pattern = rf"^{re.escape(data_type)}_(.*)_results\.parquet"
        match = re.search(pattern, file.name)
        if not match: continue
        
        exp_id = match.group(1)
        if exp_id not in full_config:
            print(f"⚠️ Skipping {file.name}: Experiment ID '{exp_id}' not in YAML.")
            continue

        # Das ist die einzige Spalte, die wir aus DIESER Datei schreiben/überschreiben wollen
        output_key = full_config[exp_id]['output_key']

        try:
            source_ds = load_dataset("parquet", data_files=str(file), split="train")
            
            # --- GEZIELTES FILTERING ---

            # A. Was wir aus der Quelldatei IGNORIEREN:
            # Alles, was schon im Master ist, ABER NICHT unsere aktuelle Zielspalte ist.
            # (So schützen wir Metadaten und andere, bereits geladene Experimente)
            to_ignore = [
                col for col in source_ds.column_names 
                if col in master_ds.column_names and col != "id" and col != output_key
            ]
            source_ds = source_ds.remove_columns(to_ignore)

            # B. Was wir im Master ÜBERSCHREIBEN:
            # NUR den output_key dieser spezifischen Datei.
            if output_key in master_ds.column_names:
                print(f"♻️  Overwriting current experiment: '{output_key}' (from {file.name})")
                master_ds = master_ds.remove_columns(output_key)
                overwritten_experiments.append(output_key)
            else:
                print(f"➕ Adding new experiment: '{output_key}'")

            # C. Merge
            master_ds = merge_datasets_by_id(
                target_ds=master_ds,
                source_data=source_ds,
                merge_key=output_key,
                id_key="id"
            )

        except Exception as e:
            print(f"❌ Failed to merge {file.name}: {e}")

    print("\n✅ Merge process completed.")
    if overwritten_experiments:
        print(f"   Note: {len(overwritten_experiments)} experiment columns were updated/overwritten.")

    return master_ds


# 1. Collect all results

base_file_path = "output/generated_output/" + data_type + "/"
master_dataset = collect_all_results(base_file_path + data_type + "_Eng2FOL_results.parquet", data_type)

# 2. Remove the prompt column if it exists
if "prompt" in master_dataset.column_names:
    master_dataset = master_dataset.remove_columns("prompt")
    print("🗑️ Removed 'prompt' column for a cleaner final file.")

# 3. Save to disk
master_dataset.to_parquet(file_name_generations)
print(f"✅ Final dataset saved to: {file_name_generations}")

📦 Loading base dataset: output/generated_output/test_subtask1/test_subtask1_Eng2FOL_results.parquet
➕ Adding new experiment: 'fol_otter_output_Eng2FOL10Qwen4B'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL10'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL11'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'fol_otter_output_Eng2FOL2' (from test_subtask1_Eng2FOL2_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'fol_otter_output_Eng2FOL3' (from test_subtask1_Eng2FOL3_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL4'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5Gemma2B'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5Qwen0.6B'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5Qwen1.7B'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5Qwen4B'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5small'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL5tiny'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL6'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL7'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL8'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL9Qwen4B'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_Eng2FOL9'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'aristotelian_output_Eng2SyllogismProlog' (from test_subtask1_Eng2SyllogismProlog_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_QwenEng2FOL1'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_QwenEng2FOL2'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_QwenEng2FOL3'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_QwenEng2FOL4'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_QwenEng2FOL5'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'fol_otter_output_QwenEng2FOL6'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'syllogism_simplified_Simp1' (from test_subtask1_Simp1_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'syllogism_simplified_Simp2' (from test_subtask1_Simp2_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'fol_otter_output_SimpEng2FOL1' (from test_subtask1_SimpEng2FOL1_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

♻️  Overwriting current experiment: 'fol_otter_output_SimpEng2FOL2' (from test_subtask1_SimpEng2FOL2_results.parquet)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

➕ Adding new experiment: 'aristotelian_output_SimpEng2SyllogismProlog'

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Merge process completed.
   Note: 7 experiment columns were updated/overwritten.
🗑️ Removed 'prompt' column for a cleaner final file.

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

✅ Final dataset saved to: output/test_subtask1_data_with_generations.parquet

In [6]:
dataset = load_data(file_name_generations)
dataset_df = pd.DataFrame(dataset)
dataset_df.head(3)

,id,syllogism,fol_otter_output_Eng2FOL,fol_otter_output_Eng2FOL10Qwen4B,fol_otter_output_Eng2FOL10,fol_otter_output_Eng2FOL11,fol_otter_output_Eng2FOL2,fol_otter_output_Eng2FOL3,fol_otter_output_Eng2FOL4,fol_otter_output_Eng2FOL5Gemma2B,...,fol_otter_output_QwenEng2FOL2,fol_otter_output_QwenEng2FOL3,fol_otter_output_QwenEng2FOL4,fol_otter_output_QwenEng2FOL5,fol_otter_output_QwenEng2FOL6,syllogism_simplified_Simp1,syllogism_simplified_Simp2,fol_otter_output_SimpEng2FOL1,fol_otter_output_SimpEng2FOL2,aristotelian_output_SimpEng2SyllogismProlog
0,bff2af61-d4b0-4147-8a5b-ff4fe1892559,There are no bikes that can be called cars. It...,"[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","['all x ( Bike(x) -> -Car(x) )', 'all x ( Bike...","[all x ( Bike(x) -> Car(x) ), all x ( Bike(x) ...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...",...,"[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[no Bike is Car, all Bike is Vehicle, some Veh...","[no Bike is Car, all Bike is Vehicle, some Veh...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[all x ( Bike(x) -> -Car(x) ), all x ( Bike(x)...","[('e', 'Bike', 'Car'), ('a', 'Bike', 'Vehicle'..."
1,f36a4ca3-3b69-4869-a152-deaa7e0fdad4,There exist some objects that are books which ...,"[exists x ( Book(x) & -DigitalFile(x) ), all x...",[exists x ( (Object(x) & Book(x)) & -DigitalFi...,[exists x ( (Object(x) & Book(x)) & -DigitalFi...,"[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...",...,[],[],"[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[some Object is Book is not Digital_File, all ...","[some Object is Book is not Digital_File, all ...",[exists x ( Object(x) & Book(x) & -Digital_Fil...,[exists x ( Object(x) & Book(x) & -Digital_Fil...,"[('i', 'Object', 'Book'), ('a', 'Book', 'Item_..."
2,e773bd8c-fa53-4e9c-8ec6-7d978e0601ac,Every single object can fly. It is known that ...,"[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...",...,"[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all Object is Can_Fly, some Boat is Not_Object]","[all Object is Capable_of_Flight, some Boat is...","[all x ( Object(x) -> Can_Fly(x) ), exists x (...","[all x ( Object(x) -> Capable_of_Flight(x) ), ...","[('a', 'Object', 'Can_Fly'), ('o', 'Boat', 'Ob..."

## Rule-based translation to FOL

In [7]:
dataset = load_data(file_name_generations)
len(dataset.features), dataset

(33,
 Dataset({
     features: ['id', 'syllogism', 'fol_otter_output_Eng2FOL', 'fol_otter_output_Eng2FOL10Qwen4B', 'fol_otter_output_Eng2FOL10', 'fol_otter_output_Eng2FOL11', 'fol_otter_output_Eng2FOL2', 'fol_otter_output_Eng2FOL3', 'fol_otter_output_Eng2FOL4', 'fol_otter_output_Eng2FOL5Gemma2B', 'fol_otter_output_Eng2FOL5Qwen0.6B', 'fol_otter_output_Eng2FOL5Qwen1.7B', 'fol_otter_output_Eng2FOL5Qwen4B', 'fol_otter_output_Eng2FOL5', 'fol_otter_output_Eng2FOL5small', 'fol_otter_output_Eng2FOL5tiny', 'fol_otter_output_Eng2FOL6', 'fol_otter_output_Eng2FOL7', 'fol_otter_output_Eng2FOL8', 'fol_otter_output_Eng2FOL9Qwen4B', 'fol_otter_output_Eng2FOL9', 'aristotelian_output_Eng2SyllogismProlog', 'fol_otter_output_QwenEng2FOL1', 'fol_otter_output_QwenEng2FOL2', 'fol_otter_output_QwenEng2FOL3', 'fol_otter_output_QwenEng2FOL4', 'fol_otter_output_QwenEng2FOL5', 'fol_otter_output_QwenEng2FOL6', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2', 'fol_otter_output_SimpEng2FOL1', 'fol_otter_output_SimpEng2FOL2', 'aristotelian_output_SimpEng2SyllogismProlog'],
     num_rows: 191
 }))

In [8]:
keys_with_nl_English = [x for x in dataset.features if x.startswith("syllogism")]
keys_with_nl_English

['syllogism', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2']

In [9]:
for input_key in keys_with_nl_English:
    input_filename = file_name_generations
    output_filename = file_name_generations
    output_key = "fol_output_from_" + input_key
    dataset = process_dataset_to_fol(input_filename, input_key, output_file =  output_filename, output_key=output_key)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

In [10]:
len(dataset.features), dataset[4].keys()

(36,
 dict_keys(['id', 'syllogism', 'fol_otter_output_Eng2FOL', 'fol_otter_output_Eng2FOL10Qwen4B', 'fol_otter_output_Eng2FOL10', 'fol_otter_output_Eng2FOL11', 'fol_otter_output_Eng2FOL2', 'fol_otter_output_Eng2FOL3', 'fol_otter_output_Eng2FOL4', 'fol_otter_output_Eng2FOL5Gemma2B', 'fol_otter_output_Eng2FOL5Qwen0.6B', 'fol_otter_output_Eng2FOL5Qwen1.7B', 'fol_otter_output_Eng2FOL5Qwen4B', 'fol_otter_output_Eng2FOL5', 'fol_otter_output_Eng2FOL5small', 'fol_otter_output_Eng2FOL5tiny', 'fol_otter_output_Eng2FOL6', 'fol_otter_output_Eng2FOL7', 'fol_otter_output_Eng2FOL8', 'fol_otter_output_Eng2FOL9Qwen4B', 'fol_otter_output_Eng2FOL9', 'aristotelian_output_Eng2SyllogismProlog', 'fol_otter_output_QwenEng2FOL1', 'fol_otter_output_QwenEng2FOL2', 'fol_otter_output_QwenEng2FOL3', 'fol_otter_output_QwenEng2FOL4', 'fol_otter_output_QwenEng2FOL5', 'fol_otter_output_QwenEng2FOL6', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2', 'fol_otter_output_SimpEng2FOL1', 'fol_otter_output_SimpEng2FOL2', 'aristotelian_output_SimpEng2SyllogismProlog', 'fol_output_from_syllogism', 'fol_output_from_syllogism_simplified_Simp1', 'fol_output_from_syllogism_simplified_Simp2']))

## Apply theorem prover

In [11]:
dataset = load_data(file_name_generations)
fol_input_keys = [col for col in dataset[1].keys() if col.startswith("fol_otter_output") or col.startswith("fol_output") ]
fol_input_keys # columns with FOL outputs

['fol_otter_output_Eng2FOL',
 'fol_otter_output_Eng2FOL10Qwen4B',
 'fol_otter_output_Eng2FOL10',
 'fol_otter_output_Eng2FOL11',
 'fol_otter_output_Eng2FOL2',
 'fol_otter_output_Eng2FOL3',
 'fol_otter_output_Eng2FOL4',
 'fol_otter_output_Eng2FOL5Gemma2B',
 'fol_otter_output_Eng2FOL5Qwen0.6B',
 'fol_otter_output_Eng2FOL5Qwen1.7B',
 'fol_otter_output_Eng2FOL5Qwen4B',
 'fol_otter_output_Eng2FOL5',
 'fol_otter_output_Eng2FOL5small',
 'fol_otter_output_Eng2FOL5tiny',
 'fol_otter_output_Eng2FOL6',
 'fol_otter_output_Eng2FOL7',
 'fol_otter_output_Eng2FOL8',
 'fol_otter_output_Eng2FOL9Qwen4B',
 'fol_otter_output_Eng2FOL9',
 'fol_otter_output_QwenEng2FOL1',
 'fol_otter_output_QwenEng2FOL2',
 'fol_otter_output_QwenEng2FOL3',
 'fol_otter_output_QwenEng2FOL4',
 'fol_otter_output_QwenEng2FOL5',
 'fol_otter_output_QwenEng2FOL6',
 'fol_otter_output_SimpEng2FOL1',
 'fol_otter_output_SimpEng2FOL2',
 'fol_output_from_syllogism',
 'fol_output_from_syllogism_simplified_Simp1',
 'fol_output_from_syllogism_simplified_Simp2']

In [12]:



current_data = list(dataset)

for input_key in fol_input_keys:
    current_data = evaluate_dataset_with_otter(
        dataset=current_data,
        input_key=input_key,
        output_file=None, # Don't save every time inside the function
        max_workers=4
    )

save_data(current_data, file_name_generations)

🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 68.81it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL10Qwen4B' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 90.77it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL10' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 88.86it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL11' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 88.30it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL2' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 89.11it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL3' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 91.18it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL4' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 91.99it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5Gemma2B' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 90.14it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5Qwen0.6B' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 90.21it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5Qwen1.7B' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 86.60it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5Qwen4B' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 84.73it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 86.43it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5small' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 89.08it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL5tiny' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 86.01it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL6' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 86.12it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL7' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 87.61it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL8' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 81.93it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL9Qwen4B' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 75.58it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_Eng2FOL9' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 88.61it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_QwenEng2FOL1' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 83.68it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_QwenEng2FOL2' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 81.70it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_QwenEng2FOL3' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 91.13it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_QwenEng2FOL4' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 91.26it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_QwenEng2FOL5' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 89.55it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_QwenEng2FOL6' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 89.90it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_SimpEng2FOL1' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 93.60it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_otter_output_SimpEng2FOL2' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 90.36it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_output_from_syllogism' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 88.39it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_output_from_syllogism_simplified_Simp1' | Items: 191

Proving: 100%|██████████| 191/191 [00:01<00:00, 97.46it/s]

✅ Results saved to None
🚀 Starting parallel Otter proofs | Key: 'fol_output_from_syllogism_simplified_Simp2' | Items: 191

Proving: 100%|██████████| 191/191 [00:02<00:00, 89.09it/s]

✅ Results saved to None
✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

## Translate to Aristotelian notation

In [13]:
from pyswip import Prolog
prolog = Prolog()
prolog.consult("prolog_syllogism.pl")

In [14]:
dataset = load_data(file_name_generations)
keys_with_nl_English = [x for x in dataset.features if x.startswith("syllogism")]
keys_with_nl_English

['syllogism', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2']

In [15]:
from reasoning.aristotelean_utils import process_dataset_to_aristotelian, process_prolog_results
for input_key in keys_with_nl_English:
    input_filename = file_name_generations
    output_key = "aristotelian_output_from_" + input_key
    dataset = process_dataset_to_aristotelian(input_filename, input_key, output_file =  None, output_key=output_key)
    save_data(dataset, file_name_generations)

🔄 Prolog file 'prolog_syllogism.pl' reloaded.

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

💡 output_file is None: Results kept in RAM.
✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

💡 output_file is None: Results kept in RAM.
✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

💡 output_file is None: Results kept in RAM.
✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

## Apply Syllogism Prover

In [16]:
dataset = load_data(file_name_generations)
arist_input_keys = [col for col in dataset[1].keys() if col.startswith("aristotelian_output")]
arist_input_keys

['aristotelian_output_Eng2SyllogismProlog',
 'aristotelian_output_SimpEng2SyllogismProlog',
 'aristotelian_output_from_syllogism',
 'aristotelian_output_from_syllogism_simplified_Simp1',
 'aristotelian_output_from_syllogism_simplified_Simp2']

In [17]:

current_data = dataset

for input_key in arist_input_keys:
    output_prefix = input_key.split("_output_")[-1] + "_aristotelian"
    current_data = process_prolog_results(current_data, input_key, output_prefix)


save_data(current_data, file_name_generations)

--- Starting local Prolog inference on 'aristotelian_output_Eng2SyllogismProlog' ---

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

--- Starting local Prolog inference on 'aristotelian_output_SimpEng2SyllogismProlog' ---

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

--- Starting local Prolog inference on 'aristotelian_output_from_syllogism' ---

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

--- Starting local Prolog inference on 'aristotelian_output_from_syllogism_simplified_Simp1' ---

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

--- Starting local Prolog inference on 'aristotelian_output_from_syllogism_simplified_Simp2' ---

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

In [18]:
dataset_df = pd.DataFrame(dataset)
cols =  ["syllogism", 'syllogism_simplified_Simp1'] + [x for x in dataset_df.columns if "aristotelian" in x and "Simp1" in x]
dataset_df[cols].head(3)

,syllogism,syllogism_simplified_Simp1,aristotelian_output_from_syllogism_simplified_Simp1
0,There exist some objects that are books which ...,"[some Object is Book is not Digital_File, all ...","[('o', 'Object_is_book', 'Digital_file'), ('a'..."
1,Every single object can fly. It is known that ...,"[all Object is Can_Fly, some Boat is Not_Object]","[('a', 'Object', 'Can_fly'), ('i', 'Boat', 'No..."
2,No animal is a rock. Some rocks are plants. Fr...,"[no Animal is Rock, some Rock is Plant, some A...","[('e', 'Animal', 'Rock'), ('i', 'Rock', 'Plant..."

## Evaluation

In [19]:
dataset = load_data(file_name_generations)


if data_type =="test_subtask1":
    input_data = "data/semeval_2026_task_11-main/test_data/subtask 1/test_data_subtask_1.json"
if data_type =="test_subtask2":
    input_data = "data/semeval_2026_task_11-main/test_data/subtask 2/test_data_subtask_2.json"
if data_type =="test_subtask3":
    input_data = "data/semeval_2026_task_11-main/test_data/subtask 3/test_data_subtask_3.json"
if data_type =="test_subtask4":
    input_data = "data/semeval_2026_task_11-main/test_data/subtask 4/test_data_subtask_4.json"

if data_type.startswith("test_subtask"):
    # merge dataset with original input data to have the labels for evaluation
    # open json file and convert to dataset
    if "validity" not in dataset.features: 
        original_data = load_dataset("json", data_files=input_data, split="train")
        dataset = merge_datasets_by_id(dataset, original_data, id_key="id", merge_key= "validity")
        dataset = merge_datasets_by_id(dataset, original_data, id_key="id", merge_key= "plausibility")

save_data(dataset, file_name_generations)


dataset

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

Dataset({
    features: ['id', 'syllogism', 'fol_otter_output_Eng2FOL', 'fol_otter_output_Eng2FOL10Qwen4B', 'fol_otter_output_Eng2FOL10', 'fol_otter_output_Eng2FOL11', 'fol_otter_output_Eng2FOL2', 'fol_otter_output_Eng2FOL3', 'fol_otter_output_Eng2FOL4', 'fol_otter_output_Eng2FOL5Gemma2B', 'fol_otter_output_Eng2FOL5Qwen0.6B', 'fol_otter_output_Eng2FOL5Qwen1.7B', 'fol_otter_output_Eng2FOL5Qwen4B', 'fol_otter_output_Eng2FOL5', 'fol_otter_output_Eng2FOL5small', 'fol_otter_output_Eng2FOL5tiny', 'fol_otter_output_Eng2FOL6', 'fol_otter_output_Eng2FOL7', 'fol_otter_output_Eng2FOL8', 'fol_otter_output_Eng2FOL9Qwen4B', 'fol_otter_output_Eng2FOL9', 'aristotelian_output_Eng2SyllogismProlog', 'fol_otter_output_QwenEng2FOL1', 'fol_otter_output_QwenEng2FOL2', 'fol_otter_output_QwenEng2FOL3', 'fol_otter_output_QwenEng2FOL4', 'fol_otter_output_QwenEng2FOL5', 'fol_otter_output_QwenEng2FOL6', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2', 'fol_otter_output_SimpEng2FOL1', 'fol_otter_output_SimpEng2FOL2', 'aristotelian_output_SimpEng2SyllogismProlog', 'fol_output_from_syllogism', 'fol_output_from_syllogism_simplified_Simp1', 'fol_output_from_syllogism_simplified_Simp2', 'otter_used_clauses_fol_otter_output_Eng2FOL', 'otter_answer_fol_otter_output_Eng2FOL', 'otter_error_fol_otter_output_Eng2FOL', 'otter_input_cleaned_fol_otter_output_Eng2FOL', 'otter_proof_fol_otter_output_Eng2FOL', 'otter_used_clauses_fol_otter_output_Eng2FOL10Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL10Qwen4B', 'otter_error_fol_otter_output_Eng2FOL10Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL10Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL10Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL10', 'otter_answer_fol_otter_output_Eng2FOL10', 'otter_error_fol_otter_output_Eng2FOL10', 'otter_input_cleaned_fol_otter_output_Eng2FOL10', 'otter_proof_fol_otter_output_Eng2FOL10', 'otter_used_clauses_fol_otter_output_Eng2FOL11', 'otter_answer_fol_otter_output_Eng2FOL11', 'otter_error_fol_otter_output_Eng2FOL11', 'otter_input_cleaned_fol_otter_output_Eng2FOL11', 'otter_proof_fol_otter_output_Eng2FOL11', 'otter_used_clauses_fol_otter_output_Eng2FOL2', 'otter_answer_fol_otter_output_Eng2FOL2', 'otter_error_fol_otter_output_Eng2FOL2', 'otter_input_cleaned_fol_otter_output_Eng2FOL2', 'otter_proof_fol_otter_output_Eng2FOL2', 'otter_used_clauses_fol_otter_output_Eng2FOL3', 'otter_answer_fol_otter_output_Eng2FOL3', 'otter_error_fol_otter_output_Eng2FOL3', 'otter_input_cleaned_fol_otter_output_Eng2FOL3', 'otter_proof_fol_otter_output_Eng2FOL3', 'otter_used_clauses_fol_otter_output_Eng2FOL4', 'otter_answer_fol_otter_output_Eng2FOL4', 'otter_error_fol_otter_output_Eng2FOL4', 'otter_input_cleaned_fol_otter_output_Eng2FOL4', 'otter_proof_fol_otter_output_Eng2FOL4', 'otter_used_clauses_fol_otter_output_Eng2FOL5Gemma2B', 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B', 'otter_error_fol_otter_output_Eng2FOL5Gemma2B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Gemma2B', 'otter_proof_fol_otter_output_Eng2FOL5Gemma2B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_error_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_error_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen4B', 'otter_error_fol_otter_output_Eng2FOL5Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL5', 'otter_answer_fol_otter_output_Eng2FOL5', 'otter_error_fol_otter_output_Eng2FOL5', 'otter_input_cleaned_fol_otter_output_Eng2FOL5', 'otter_proof_fol_otter_output_Eng2FOL5', 'otter_used_clauses_fol_otter_output_Eng2FOL5small', 'otter_answer_fol_otter_output_Eng2FOL5small', 'otter_error_fol_otter_output_Eng2FOL5small', 'otter_input_cleaned_fol_otter_output_Eng2FOL5small', 'otter_proof_fol_otter_output_Eng2FOL5small', 'otter_used_clauses_fol_otter_output_Eng2FOL5tiny', 'otter_answer_fol_otter_output_Eng2FOL5tiny', 'otter_error_fol_otter_output_Eng2FOL5tiny', 'otter_input_cleaned_fol_otter_output_Eng2FOL5tiny', 'otter_proof_fol_otter_output_Eng2FOL5tiny', 'otter_used_clauses_fol_otter_output_Eng2FOL6', 'otter_answer_fol_otter_output_Eng2FOL6', 'otter_error_fol_otter_output_Eng2FOL6', 'otter_input_cleaned_fol_otter_output_Eng2FOL6', 'otter_proof_fol_otter_output_Eng2FOL6', 'otter_used_clauses_fol_otter_output_Eng2FOL7', 'otter_answer_fol_otter_output_Eng2FOL7', 'otter_error_fol_otter_output_Eng2FOL7', 'otter_input_cleaned_fol_otter_output_Eng2FOL7', 'otter_proof_fol_otter_output_Eng2FOL7', 'otter_used_clauses_fol_otter_output_Eng2FOL8', 'otter_answer_fol_otter_output_Eng2FOL8', 'otter_error_fol_otter_output_Eng2FOL8', 'otter_input_cleaned_fol_otter_output_Eng2FOL8', 'otter_proof_fol_otter_output_Eng2FOL8', 'otter_used_clauses_fol_otter_output_Eng2FOL9Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL9Qwen4B', 'otter_error_fol_otter_output_Eng2FOL9Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL9', 'otter_answer_fol_otter_output_Eng2FOL9', 'otter_error_fol_otter_output_Eng2FOL9', 'otter_input_cleaned_fol_otter_output_Eng2FOL9', 'otter_proof_fol_otter_output_Eng2FOL9', 'otter_used_clauses_fol_otter_output_QwenEng2FOL1', 'otter_answer_fol_otter_output_QwenEng2FOL1', 'otter_error_fol_otter_output_QwenEng2FOL1', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL1', 'otter_proof_fol_otter_output_QwenEng2FOL1', 'otter_used_clauses_fol_otter_output_QwenEng2FOL2', 'otter_answer_fol_otter_output_QwenEng2FOL2', 'otter_error_fol_otter_output_QwenEng2FOL2', 'otter_used_clauses_fol_otter_output_QwenEng2FOL3', 'otter_answer_fol_otter_output_QwenEng2FOL3', 'otter_error_fol_otter_output_QwenEng2FOL3', 'otter_used_clauses_fol_otter_output_QwenEng2FOL4', 'otter_answer_fol_otter_output_QwenEng2FOL4', 'otter_error_fol_otter_output_QwenEng2FOL4', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL4', 'otter_proof_fol_otter_output_QwenEng2FOL4', 'otter_used_clauses_fol_otter_output_QwenEng2FOL5', 'otter_answer_fol_otter_output_QwenEng2FOL5', 'otter_error_fol_otter_output_QwenEng2FOL5', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL5', 'otter_proof_fol_otter_output_QwenEng2FOL5', 'otter_used_clauses_fol_otter_output_QwenEng2FOL6', 'otter_answer_fol_otter_output_QwenEng2FOL6', 'otter_error_fol_otter_output_QwenEng2FOL6', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL6', 'otter_proof_fol_otter_output_QwenEng2FOL6', 'otter_used_clauses_fol_otter_output_SimpEng2FOL1', 'otter_answer_fol_otter_output_SimpEng2FOL1', 'otter_error_fol_otter_output_SimpEng2FOL1', 'otter_input_cleaned_fol_otter_output_SimpEng2FOL1', 'otter_proof_fol_otter_output_SimpEng2FOL1', 'otter_used_clauses_fol_otter_output_SimpEng2FOL2', 'otter_answer_fol_otter_output_SimpEng2FOL2', 'otter_error_fol_otter_output_SimpEng2FOL2', 'otter_input_cleaned_fol_otter_output_SimpEng2FOL2', 'otter_proof_fol_otter_output_SimpEng2FOL2', 'otter_used_clauses_fol_output_from_syllogism', 'otter_answer_fol_output_from_syllogism', 'otter_error_fol_output_from_syllogism', 'otter_input_cleaned_fol_output_from_syllogism', 'otter_proof_fol_output_from_syllogism', 'otter_used_clauses_fol_output_from_syllogism_simplified_Simp1', 'otter_answer_fol_output_from_syllogism_simplified_Simp1', 'otter_error_fol_output_from_syllogism_simplified_Simp1', 'otter_input_cleaned_fol_output_from_syllogism_simplified_Simp1', 'otter_proof_fol_output_from_syllogism_simplified_Simp1', 'otter_used_clauses_fol_output_from_syllogism_simplified_Simp2', 'otter_answer_fol_output_from_syllogism_simplified_Simp2', 'otter_error_fol_output_from_syllogism_simplified_Simp2', 'otter_input_cleaned_fol_output_from_syllogism_simplified_Simp2', 'otter_proof_fol_output_from_syllogism_simplified_Simp2', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL9Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL9Qwen4B', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL2', 'otter_proof_fol_otter_output_QwenEng2FOL2', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL3', 'otter_proof_fol_otter_output_QwenEng2FOL3', 'aristotelian_output_from_syllogism', 'aristotelian_output_from_syllogism_simplified_Simp1', 'aristotelian_output_from_syllogism_simplified_Simp2', 'Eng2SyllogismProlog_aristotelian_truth', 'Eng2SyllogismProlog_aristotelian_type', 'SimpEng2SyllogismProlog_aristotelian_truth', 'SimpEng2SyllogismProlog_aristotelian_type', 'from_syllogism_aristotelian_truth', 'from_syllogism_aristotelian_type', 'from_syllogism_simplified_Simp1_aristotelian_truth', 'from_syllogism_simplified_Simp1_aristotelian_type', 'from_syllogism_simplified_Simp2_aristotelian_truth', 'from_syllogism_simplified_Simp2_aristotelian_type', 'validity', 'plausibility'],
    num_rows: 191
})

In [20]:
dataset = load_data(file_name_generations)
# read json output/test_subtask1_dni_predictions.json
dni_json = json.load(open("output/test_subtask1_dni_predictions.json", "r"))
dni_json
# if dn_validity is True change to "True", if False change to "False" else "Error"
for item in dni_json:
    if item["dni_validity"] == True:
        item["dni_validity"] = "True"
    elif item["dni_validity"] == False:
        item["dni_validity"] = "False"
    else:
        item["dni_validity"] = "Error"



# make dataset from json
dni = Dataset.from_list(dni_json)

# remove dni_validity column from dataset if it already exists
if "dni_validity" in dataset.features:
    dataset = dataset.remove_columns("dni_validity")

dataset = merge_datasets_by_id(dataset, dni, id_key="id", merge_key= "dni_validity")

save_data(dataset, file_name_generations)

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

✅ Saved 191 rows to: output/test_subtask1_data_with_generations.parquet

### Aristotelian Proofs (only subtask 1  + 3)

In [21]:
answer_keys = [x for x in dataset.features if x.endswith("truth")]
answer_keys = [x.split("_truth")[0] for x in answer_keys]
answer_keys

['Eng2SyllogismProlog_aristotelian',
 'SimpEng2SyllogismProlog_aristotelian',
 'from_syllogism_aristotelian',
 'from_syllogism_simplified_Simp1_aristotelian',
 'from_syllogism_simplified_Simp2_aristotelian']

In [22]:
import zipfile
from reasoning.io_utils import create_predictions_file

for key in answer_keys:
    name = key
    create_predictions_file(dataset,  key + "_truth", subtask, used_clauses_key = None)
    out = name
    with zipfile.ZipFile("predictions/" + out + ".zip", 'w', compression=zipfile.ZIP_DEFLATED) as zipf:
        zipf.write("predictions.json")

✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)

### Otter proofs (all subtask)

In [23]:
dataset = load_data(file_name_generations)
print(file_name_generations)
dataset

output/test_subtask1_data_with_generations.parquet

Dataset({
    features: ['id', 'syllogism', 'fol_otter_output_Eng2FOL', 'fol_otter_output_Eng2FOL10Qwen4B', 'fol_otter_output_Eng2FOL10', 'fol_otter_output_Eng2FOL11', 'fol_otter_output_Eng2FOL2', 'fol_otter_output_Eng2FOL3', 'fol_otter_output_Eng2FOL4', 'fol_otter_output_Eng2FOL5Gemma2B', 'fol_otter_output_Eng2FOL5Qwen0.6B', 'fol_otter_output_Eng2FOL5Qwen1.7B', 'fol_otter_output_Eng2FOL5Qwen4B', 'fol_otter_output_Eng2FOL5', 'fol_otter_output_Eng2FOL5small', 'fol_otter_output_Eng2FOL5tiny', 'fol_otter_output_Eng2FOL6', 'fol_otter_output_Eng2FOL7', 'fol_otter_output_Eng2FOL8', 'fol_otter_output_Eng2FOL9Qwen4B', 'fol_otter_output_Eng2FOL9', 'aristotelian_output_Eng2SyllogismProlog', 'fol_otter_output_QwenEng2FOL1', 'fol_otter_output_QwenEng2FOL2', 'fol_otter_output_QwenEng2FOL3', 'fol_otter_output_QwenEng2FOL4', 'fol_otter_output_QwenEng2FOL5', 'fol_otter_output_QwenEng2FOL6', 'syllogism_simplified_Simp1', 'syllogism_simplified_Simp2', 'fol_otter_output_SimpEng2FOL1', 'fol_otter_output_SimpEng2FOL2', 'aristotelian_output_SimpEng2SyllogismProlog', 'fol_output_from_syllogism', 'fol_output_from_syllogism_simplified_Simp1', 'fol_output_from_syllogism_simplified_Simp2', 'otter_used_clauses_fol_otter_output_Eng2FOL', 'otter_answer_fol_otter_output_Eng2FOL', 'otter_error_fol_otter_output_Eng2FOL', 'otter_input_cleaned_fol_otter_output_Eng2FOL', 'otter_proof_fol_otter_output_Eng2FOL', 'otter_used_clauses_fol_otter_output_Eng2FOL10Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL10Qwen4B', 'otter_error_fol_otter_output_Eng2FOL10Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL10Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL10Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL10', 'otter_answer_fol_otter_output_Eng2FOL10', 'otter_error_fol_otter_output_Eng2FOL10', 'otter_input_cleaned_fol_otter_output_Eng2FOL10', 'otter_proof_fol_otter_output_Eng2FOL10', 'otter_used_clauses_fol_otter_output_Eng2FOL11', 'otter_answer_fol_otter_output_Eng2FOL11', 'otter_error_fol_otter_output_Eng2FOL11', 'otter_input_cleaned_fol_otter_output_Eng2FOL11', 'otter_proof_fol_otter_output_Eng2FOL11', 'otter_used_clauses_fol_otter_output_Eng2FOL2', 'otter_answer_fol_otter_output_Eng2FOL2', 'otter_error_fol_otter_output_Eng2FOL2', 'otter_input_cleaned_fol_otter_output_Eng2FOL2', 'otter_proof_fol_otter_output_Eng2FOL2', 'otter_used_clauses_fol_otter_output_Eng2FOL3', 'otter_answer_fol_otter_output_Eng2FOL3', 'otter_error_fol_otter_output_Eng2FOL3', 'otter_input_cleaned_fol_otter_output_Eng2FOL3', 'otter_proof_fol_otter_output_Eng2FOL3', 'otter_used_clauses_fol_otter_output_Eng2FOL4', 'otter_answer_fol_otter_output_Eng2FOL4', 'otter_error_fol_otter_output_Eng2FOL4', 'otter_input_cleaned_fol_otter_output_Eng2FOL4', 'otter_proof_fol_otter_output_Eng2FOL4', 'otter_used_clauses_fol_otter_output_Eng2FOL5Gemma2B', 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B', 'otter_error_fol_otter_output_Eng2FOL5Gemma2B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Gemma2B', 'otter_proof_fol_otter_output_Eng2FOL5Gemma2B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_error_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_error_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen4B', 'otter_error_fol_otter_output_Eng2FOL5Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL5', 'otter_answer_fol_otter_output_Eng2FOL5', 'otter_error_fol_otter_output_Eng2FOL5', 'otter_input_cleaned_fol_otter_output_Eng2FOL5', 'otter_proof_fol_otter_output_Eng2FOL5', 'otter_used_clauses_fol_otter_output_Eng2FOL5small', 'otter_answer_fol_otter_output_Eng2FOL5small', 'otter_error_fol_otter_output_Eng2FOL5small', 'otter_input_cleaned_fol_otter_output_Eng2FOL5small', 'otter_proof_fol_otter_output_Eng2FOL5small', 'otter_used_clauses_fol_otter_output_Eng2FOL5tiny', 'otter_answer_fol_otter_output_Eng2FOL5tiny', 'otter_error_fol_otter_output_Eng2FOL5tiny', 'otter_input_cleaned_fol_otter_output_Eng2FOL5tiny', 'otter_proof_fol_otter_output_Eng2FOL5tiny', 'otter_used_clauses_fol_otter_output_Eng2FOL6', 'otter_answer_fol_otter_output_Eng2FOL6', 'otter_error_fol_otter_output_Eng2FOL6', 'otter_input_cleaned_fol_otter_output_Eng2FOL6', 'otter_proof_fol_otter_output_Eng2FOL6', 'otter_used_clauses_fol_otter_output_Eng2FOL7', 'otter_answer_fol_otter_output_Eng2FOL7', 'otter_error_fol_otter_output_Eng2FOL7', 'otter_input_cleaned_fol_otter_output_Eng2FOL7', 'otter_proof_fol_otter_output_Eng2FOL7', 'otter_used_clauses_fol_otter_output_Eng2FOL8', 'otter_answer_fol_otter_output_Eng2FOL8', 'otter_error_fol_otter_output_Eng2FOL8', 'otter_input_cleaned_fol_otter_output_Eng2FOL8', 'otter_proof_fol_otter_output_Eng2FOL8', 'otter_used_clauses_fol_otter_output_Eng2FOL9Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL9Qwen4B', 'otter_error_fol_otter_output_Eng2FOL9Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL9', 'otter_answer_fol_otter_output_Eng2FOL9', 'otter_error_fol_otter_output_Eng2FOL9', 'otter_input_cleaned_fol_otter_output_Eng2FOL9', 'otter_proof_fol_otter_output_Eng2FOL9', 'otter_used_clauses_fol_otter_output_QwenEng2FOL1', 'otter_answer_fol_otter_output_QwenEng2FOL1', 'otter_error_fol_otter_output_QwenEng2FOL1', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL1', 'otter_proof_fol_otter_output_QwenEng2FOL1', 'otter_used_clauses_fol_otter_output_QwenEng2FOL2', 'otter_answer_fol_otter_output_QwenEng2FOL2', 'otter_error_fol_otter_output_QwenEng2FOL2', 'otter_used_clauses_fol_otter_output_QwenEng2FOL3', 'otter_answer_fol_otter_output_QwenEng2FOL3', 'otter_error_fol_otter_output_QwenEng2FOL3', 'otter_used_clauses_fol_otter_output_QwenEng2FOL4', 'otter_answer_fol_otter_output_QwenEng2FOL4', 'otter_error_fol_otter_output_QwenEng2FOL4', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL4', 'otter_proof_fol_otter_output_QwenEng2FOL4', 'otter_used_clauses_fol_otter_output_QwenEng2FOL5', 'otter_answer_fol_otter_output_QwenEng2FOL5', 'otter_error_fol_otter_output_QwenEng2FOL5', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL5', 'otter_proof_fol_otter_output_QwenEng2FOL5', 'otter_used_clauses_fol_otter_output_QwenEng2FOL6', 'otter_answer_fol_otter_output_QwenEng2FOL6', 'otter_error_fol_otter_output_QwenEng2FOL6', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL6', 'otter_proof_fol_otter_output_QwenEng2FOL6', 'otter_used_clauses_fol_otter_output_SimpEng2FOL1', 'otter_answer_fol_otter_output_SimpEng2FOL1', 'otter_error_fol_otter_output_SimpEng2FOL1', 'otter_input_cleaned_fol_otter_output_SimpEng2FOL1', 'otter_proof_fol_otter_output_SimpEng2FOL1', 'otter_used_clauses_fol_otter_output_SimpEng2FOL2', 'otter_answer_fol_otter_output_SimpEng2FOL2', 'otter_error_fol_otter_output_SimpEng2FOL2', 'otter_input_cleaned_fol_otter_output_SimpEng2FOL2', 'otter_proof_fol_otter_output_SimpEng2FOL2', 'otter_used_clauses_fol_output_from_syllogism', 'otter_answer_fol_output_from_syllogism', 'otter_error_fol_output_from_syllogism', 'otter_input_cleaned_fol_output_from_syllogism', 'otter_proof_fol_output_from_syllogism', 'otter_used_clauses_fol_output_from_syllogism_simplified_Simp1', 'otter_answer_fol_output_from_syllogism_simplified_Simp1', 'otter_error_fol_output_from_syllogism_simplified_Simp1', 'otter_input_cleaned_fol_output_from_syllogism_simplified_Simp1', 'otter_proof_fol_output_from_syllogism_simplified_Simp1', 'otter_used_clauses_fol_output_from_syllogism_simplified_Simp2', 'otter_answer_fol_output_from_syllogism_simplified_Simp2', 'otter_error_fol_output_from_syllogism_simplified_Simp2', 'otter_input_cleaned_fol_output_from_syllogism_simplified_Simp2', 'otter_proof_fol_output_from_syllogism_simplified_Simp2', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL9Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL9Qwen4B', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL2', 'otter_proof_fol_otter_output_QwenEng2FOL2', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL3', 'otter_proof_fol_otter_output_QwenEng2FOL3', 'aristotelian_output_from_syllogism', 'aristotelian_output_from_syllogism_simplified_Simp1', 'aristotelian_output_from_syllogism_simplified_Simp2', 'Eng2SyllogismProlog_aristotelian_truth', 'Eng2SyllogismProlog_aristotelian_type', 'SimpEng2SyllogismProlog_aristotelian_truth', 'SimpEng2SyllogismProlog_aristotelian_type', 'from_syllogism_aristotelian_truth', 'from_syllogism_aristotelian_type', 'from_syllogism_simplified_Simp1_aristotelian_truth', 'from_syllogism_simplified_Simp1_aristotelian_type', 'from_syllogism_simplified_Simp2_aristotelian_truth', 'from_syllogism_simplified_Simp2_aristotelian_type', 'validity', 'plausibility', 'dni_validity'],
    num_rows: 191
})

In [24]:
answer_keys = [x for x in dataset.features if 'otter_answer' in x]
used_keys = [x for x in dataset.features if 'used_clauses' in x]
answer_keys#, used_keys

['otter_answer_fol_otter_output_Eng2FOL',
 'otter_answer_fol_otter_output_Eng2FOL10Qwen4B',
 'otter_answer_fol_otter_output_Eng2FOL10',
 'otter_answer_fol_otter_output_Eng2FOL11',
 'otter_answer_fol_otter_output_Eng2FOL2',
 'otter_answer_fol_otter_output_Eng2FOL3',
 'otter_answer_fol_otter_output_Eng2FOL4',
 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B',
 'otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B',
 'otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B',
 'otter_answer_fol_otter_output_Eng2FOL5Qwen4B',
 'otter_answer_fol_otter_output_Eng2FOL5',
 'otter_answer_fol_otter_output_Eng2FOL5small',
 'otter_answer_fol_otter_output_Eng2FOL5tiny',
 'otter_answer_fol_otter_output_Eng2FOL6',
 'otter_answer_fol_otter_output_Eng2FOL7',
 'otter_answer_fol_otter_output_Eng2FOL8',
 'otter_answer_fol_otter_output_Eng2FOL9Qwen4B',
 'otter_answer_fol_otter_output_Eng2FOL9',
 'otter_answer_fol_otter_output_QwenEng2FOL1',
 'otter_answer_fol_otter_output_QwenEng2FOL2',
 'otter_answer_fol_otter_output_QwenEng2FOL3',
 'otter_answer_fol_otter_output_QwenEng2FOL4',
 'otter_answer_fol_otter_output_QwenEng2FOL5',
 'otter_answer_fol_otter_output_QwenEng2FOL6',
 'otter_answer_fol_otter_output_SimpEng2FOL1',
 'otter_answer_fol_otter_output_SimpEng2FOL2',
 'otter_answer_fol_output_from_syllogism',
 'otter_answer_fol_output_from_syllogism_simplified_Simp1',
 'otter_answer_fol_output_from_syllogism_simplified_Simp2']

In [25]:
import zipfile
from reasoning.io_utils import create_predictions_file

if "test" in data_type:
    subtask = data_type.replace("test_", "")
else:
    subtask = data_type


for key in answer_keys:
    name = "predictions/predictions_" + key
    key_suffix = key.split("output_", 1)[-1]
    used_key = [x for x in used_keys if x.endswith(key_suffix)][0]
    create_predictions_file(dataset,  key, subtask, used_clauses_key = used_key)
    out = name.split("output_", 1)[-1]
    with zipfile.ZipFile("predictions/"  + out + ".zip", 'w', compression=zipfile.ZIP_DEFLATED) as zipf:
        zipf.write("predictions.json")

✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)
✅ Prediction file created: predictions.json (Subtask: subtask1, Rows: 191)

In [26]:
data_type

'test_subtask1'

### Analyze data

In [27]:
out_keys = ['syllogism'] + [configs['experiments'][ex]['output_key'] for ex in configs['experiments'] ]


for key in out_keys:
    if key in dataset.features:
        print(f"Output Key: {key}")
        for i in range(15):
            print(f"Example {i+1}: {dataset[key][i]}")
        print('-' *40)

Output Key: syllogism
Example 1: There exist some objects that are books which are not digital files. Every single book is an item with pages. Consequently, some items with pages are digital files.
Example 2: Every single object can fly. It is known that some boats cannot fly. It follows that some boats are not objects.
Example 3: No animal is a rock. Some rocks are plants. From this, it can be concluded that some animals are plants.
Example 4: There are no cars that are not alive. It is the case that no horse is alive. At least some horses are cars.
Example 5: The entire set of fruits is composed of round objects with a citrus peel. At least one orange is not a round object with a citrus peel. Every single fruit is an orange.
Example 6: Every single vehicle can be considered an object. There are no cars that are objects. Therefore, no car is a vehicle.
Example 7: There is no piece of furniture that can be called a planet. Each and every chair is a piece of furniture. Consequently, no chair is a planet.
Example 8: Every single fruit is a food. Nothing that is a vegetable is a food. It follows from this that every vegetable is a fruit.
Example 9: There are no individuals who are elephants that are also people enrolled in kindergarten. All five-year-olds are people enrolled in kindergarten. It can be deduced that some five-year-olds are not elephants.
Example 10: There are no bikes that can be called cars. It is also true that every bike is a type of vehicle. This has led to the conclusion that a portion of vehicles are bikes.
Example 11: There exist some things that are books which do not have pages. Every single book is a living thing. Consequently, some living things have pages.
Example 12: There is no canine that is a feline. Everything that is a canine is also a dog. This makes it true that all dogs are cats.
Example 13: There are no birds that are triangles. Every triangle is, by definition, a shape. Thus, some shapes are birds.
Example 14: Every human is over 10 feet tall. Some basketball players are humans. It follows, then, that some basketball players are over 10 feet tall.
Example 15: Every single item that is a writing instrument is a tool. There are some pens which are writing instruments. Thus, some pens are tools.
----------------------------------------
Output Key: syllogism_simplified_Simp1
Example 1: ['some Object is Book is not Digital_File', 'all Book is Item_with_Pages', 'some Item_with_Pages is Digital_File']
Example 2: ['all Object is Can_Fly', 'some Boat is Not_Object']
Example 3: ['no Animal is Rock', 'some Rock is Plant', 'some Animal is Plant']
Example 4: ['all Car is Alive', 'no Horse is Alive', 'some Horse is Car']
Example 5: ['all Fruit is Round_Object_with_Citrus_Peel', 'no Orange is Round_Object_with_Citrus_Peel', 'all Fruit is Orange']
Example 6: ['all Vehicle is Object', 'no Car is Object', 'no Car is Vehicle']
Example 7: ['no Piece_of_Furniture is Planet', 'all Chair is Piece_of_Furniture', 'no Chair is Planet']
Example 8: ['all Fruit is Food', 'no Vegetable is Food', 'all Vegetable is Fruit']
Example 9: ['no Elephant is Person_enrolled_in_Kindergarten', 'all Five_Years_Age is Person_enrolled_in_Kindergarten', 'some Five_Years_Age is not Elephant']
Example 10: ['no Bike is Car', 'all Bike is Vehicle', 'some Vehicle is Bike']
Example 11: ['some Book is Not_Living_Thing', 'all Book is Living_Thing', 'some Living_Thing is Not_Book']
Example 12: ['no Canine is Feline', 'all Canine is Dog', 'all Dog is Cat']
Example 13: ['no Bird is Triangle', 'all Triangle is Shape', 'some Shape is Bird']
Example 14: ['all Human is Over_10_Feet_Tall', 'some Basketball_Player is Human', 'some Basketball_Player is Over_10_Feet_Tall']
Example 15: ['all Writing_Instrument is Tool', 'some Pen is Writing_Instrument', 'some Pen is Tool']
----------------------------------------
Output Key: syllogism_simplified_Simp2
Example 1: ['some Object is Book is not Digital_File', 'all Book is Item_with_Pages', 'some Item_with_Pages is Digital_File']
Example 2: ['all Object is Capable_of_Flight', 'some Boat is not Object']
Example 3: ['no Animal is Rock', 'some Rock is Plant', 'some Animal is Plant']
Example 4: ['all Car is Alive', 'no Horse is Alive', 'some Horse is Car']
Example 5: ['all Fruit is Round_Object_with_Citrus_Peel', 'some Orange is not Round_Object_with_Citrus_Peel', 'all Fruit is Orange']
Example 6: ['all Vehicle is Object', 'no Car is Object', 'no Car is Vehicle']
Example 7: ['no Piece_of_Furniture is Planet', 'all Chair is Piece_of_Furniture', 'no Chair is Planet']
Example 8: ['all Fruit is Food', 'no Vegetable is Food', 'every Vegetable is Fruit']
Example 9: ['no Elephant is Person_enrolled_in_Kindergarten', 'all Five_Years_Ago is Person_enrolled_in_Kindergarten', 'some Five_Years_Ago is not Elephant']
Example 10: ['no Bike is Car', 'all Bike is Vehicle', 'some Vehicle is Bike']
Example 11: ['some Book is not Thing_with_Pages', 'all Book is Living_Thing', 'some Living_Thing is Thing_with_Pages']
Example 12: ['no Canine is Feline', 'all Canine is Dog', 'all Dog is Cat']
Example 13: ['no Bird is Triangle', 'all Triangle is Shape', 'some Shape is Bird']
Example 14: ['all Human is Over_10_Feet_Tall', 'some Basketball_Player is Human', 'some Basketball_Player is Over_10_Feet_Tall']
Example 15: ['all Writing_Instrument is Tool', 'some Pen is Writing_Instrument', 'some Pen is Tool']
----------------------------------------
Output Key: aristotelian_output_Eng2SyllogismProlog
Example 1: ["('i', 'Object', 'Book')", "('a', 'Book', 'Item_With_Pages')", "('o', 'Item_With_Pages', 'Digital_File')"]
Example 2: ["('a', 'Object', 'Fly')", "('o', 'Boat', 'Fly')", "('o', 'Boat', 'Object')"]
Example 3: ["('e', 'Animal', 'Rock')", "('o', 'Rock', 'Plant')", "('o', 'Animal', 'Plant')"]
Example 4: ["('e', 'Car', 'Not_Alive')", "('e', 'Horse', 'Alive')", "('i', 'Horse', 'Car')"]
Example 5: ["('a', 'Fruit', 'Round_Object_With_A_Citrus_Peel')", "('o', 'Orange', 'Round_Object_With_A_Citrus_Peel')", "('a', 'Fruit', 'Orange')"]
Example 6: ["('a', 'Vehicle', 'Object')", "('e', 'Car', 'Object')", "('e', 'Car', 'Vehicle')"]
Example 7: ["('e', 'Piece_Of_Furniture', 'Planet')", "('a', 'Chair', 'Piece_Of_Furniture')", "('e', 'Chair', 'Planet')"]
Example 8: ["('e', 'Fruit', 'Food')", "('e', 'Vegetable', 'Food')", "('o', 'Vegetable', 'Fruit')"]
Example 9: ["('e', 'Elephant', 'Individual')", "('a', 'Individual', 'Elephant')", "('a', 'Individual', 'People_Enrolled_In_Kindergarten')", "('o', 'Five_Years_Old', 'Elephant')"]
Example 10: ["('e', 'Bike', 'Car')", "('a', 'Bike', 'Vehicle')", "('o', 'Vehicle', 'Bike')"]
Example 11: ["('i', 'Book', 'Not_Have_Pages')", "('a', 'Book', 'Living_Thing')", "('i', 'Living_Thing', 'Have_Pages')"]
Example 12: ["('e', 'Canine', 'Feline')", "('a', 'Canine', 'Dog')", "('a', 'Dog', 'Cat')"]
Example 13: ["('e', 'Bird', 'Triangle')", "('a', 'Triangle', 'Shape')", "('i', 'Shape', 'Bird')"]
Example 14: ["('a', 'Human', 'Over_10_Feet_Tall')", "('o', 'Basketball_Player', 'Human')", "('i', 'Basketball_Player', 'Over_10_Feet_Tall')"]
Example 15: ["('a', 'Writing_Instrument', 'Tool')", "('o', 'Pen', 'Writing_Instrument')", "('i', 'Pen', 'Tool')"]
----------------------------------------
Output Key: aristotelian_output_SimpEng2SyllogismProlog
Example 1: ["('i', 'Object', 'Book')", "('a', 'Book', 'Item_with_Pages')", "('o', 'Item_with_Pages', 'Digital_File')"]
Example 2: ["('a', 'Object', 'Can_Fly')", "('o', 'Boat', 'Object')"]
Example 3: ["('e', 'Animal', 'Rock')", "('o', 'Rock', 'Plant')", "('o', 'Animal', 'Plant')"]
Example 4: ["('a', 'Car', 'Alive')", "('e', 'Horse', 'Alive')", "('o', 'Horse', 'Car')"]
Example 5: ["('a', 'Fruit', 'Round_Object_with_Citrus_Peel')", "('e', 'Orange', 'Round_Object_with_Citrus_Peel')", "('a', 'Fruit', 'Orange')"]
Example 6: ["('a', 'Vehicle', 'Object')", "('e', 'Car', 'Object')", "('e', 'Car', 'Vehicle')"]
Example 7: ["('e', 'Piece_of_Furniture', 'Planet')", "('a', 'Chair', 'Piece_of_Furniture')", "('e', 'Chair', 'Planet')"]
Example 8: ["('a', 'Fruit', 'Food')", "('e', 'Vegetable', 'Food')", "('a', 'Vegetable', 'Fruit')"]
Example 9: ["('e', 'Elephant', 'Person_enrolled_in_Kindergarten')", "('a', 'Five_Years_Age', 'Person_enrolled_in_Kindergarten')", "('o', 'Five_Years_Age', 'Elephant')"]
Example 10: ["('e', 'Bike', 'Car')", "('a', 'Bike', 'Vehicle')", "('o', 'Vehicle', 'Bike')"]
Example 11: ["('i', 'Book', 'Not_Living_Thing')", "('a', 'Book', 'Living_Thing')", "('o', 'Living_Thing', 'Not_Book')"]
Example 12: ["('e', 'Canine', 'Feline')", "('a', 'Canine', 'Dog')", "('a', 'Dog', 'Cat')"]
Example 13: ["('e', 'Bird', 'Triangle')", "('a', 'Triangle', 'Shape')", "('o', 'Shape', 'Bird')"]
Example 14: ["('a', 'Human', 'Over_10_Feet_Tall')", "('a', 'Basketball_Player', 'Human')", "('o', 'Basketball_Player', 'Over_10_Feet_Tall')"]
Example 15: ["('a', 'Writing_Instrument', 'Tool')", "('o', 'Pen', 'Writing_Instrument')", "('o', 'Pen', 'Tool')"]
----------------------------------------
Output Key: fol_otter_output_Eng2FOL
Example 1: ['exists x ( Book(x) & -DigitalFile(x) )', 'all x ( Book(x) -> Has_Pages(x) )', 'exists x ( Has_Pages(x) & DigitalFile(x) )']
Example 2: ['all x ( Object(x) -> CanFly(x) )', 'exists x ( Boat(x) & -CanFly(x) )', 'exists x ( Boat(x) & -Object(x) )']
Example 3: ['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
Example 4: ['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
Example 5: ['all x ( Fruit(x) -> Round(x) & CitrusPeel(x) )', 'exists x ( Orange(x) & -Round(x) & -CitrusPeel(x) )', 'all x ( Fruit(x) -> Orange(x) )']
Example 6: ['all x ( Vehicle(x) -> Object(x) )', 'all x ( Car(x) -> -Object(x) )', 'all x ( Car(x) -> -Vehicle(x) )']
Example 7: ['all x ( Chair(x) -> PieceOfFurniture(x) )', 'all x ( Planet(x) -> -Chair(x) )', 'all x ( Chair(x) -> -Planet(x) )']
Example 8: ['all x ( Fruit(x) -> Food(x) )', 'all x ( Vegetable(x) -> -Food(x) )', 'all x ( Vegetable(x) -> Fruit(x) )']
Example 9: ['all x ( Elephant(x) & -Person(x) )', 'all x ( FiveYearOld(x) -> Person(x) & Kindergarten(x) )', 'exists x ( FiveYearOld(x) & -Elephant(x) )']
Example 10: ['all x ( Bike(x) -> -Car(x) )', 'all x ( Bike(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Bike(x) )']
Example 11: ['exists x ( Book(x) & -Has_Pages(x) )', 'all x ( Book(x) -> LivingThing(x) )', 'exists x ( LivingThing(x) & Has_Pages(x) )']
Example 12: ['all x ( Canine(x) -> -Feline(x) )', 'all x ( Canine(x) -> Dog(x) )', 'all x ( Dog(x) -> Cat(x) )']
Example 13: ['all x ( Bird(x) -> -Triangle(x) )', 'all x ( Triangle(x) -> Shape(x) )', 'exists x ( Shape(x) & Bird(x) )']
Example 14: ['all x ( Human(x) -> >10ft(x) )', 'exists x ( BasketballPlayer(x) & Human(x) )', 'exists x ( BasketballPlayer(x) & >10ft(x) )']
Example 15: ['all x ( Writing_Instrument(x) -> Tool(x) )', 'exists x ( Pen(x) & Writing_Instrument(x) )', 'exists x ( Pen(x) & Tool(x) )']
----------------------------------------
Output Key: fol_otter_output_SimpEng2FOL1
Example 1: ['exists x ( Object(x) & Book(x) & -Digital_File(x) )', 'all x ( Book(x) -> Item_with_Pages(x) )', 'exists x ( Item_with_Pages(x) & Digital_File(x) )']
Example 2: ['all x ( Object(x) -> Can_Fly(x) )', 'exists x ( Boat(x) & -Object(x) )']
Example 3: ['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
Example 4: ['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
Example 5: ['all x ( Fruit(x) -> Round_Object_with_Citrus_Peel(x) )', 'all x ( Orange(x) -> Round_Object_with_Citrus_Peel(x) )', 'all x ( Fruit(x) -> Orange(x) )']
Example 6: ['all x ( Vehicle(x) -> Object(x) )', 'no x ( Car(x) & Object(x) )', 'no x ( Car(x) & Vehicle(x) )']
Example 7: ['all x ( Chair(x) -> Piece_of_Furniture(x) )', 'all x ( Chair(x) -> -Planet(x) )', 'all x ( Piece_of_Furniture(x) -> -Planet(x) )']
Example 8: ['all x ( Fruit(x) -> Food(x) )', 'all x ( Vegetable(x) -> -Food(x) )', 'all x ( Vegetable(x) -> Fruit(x) )']
Example 9: ['all x ( Elephant(x) -> -Person_enrolled_in_Kindergarten(x) )', 'all x ( Five_Years_Age(x) -> Person_enrolled_in_Kindergarten(x) )', 'exists x ( Five_Years_Age(x) & -Elephant(x) )']
Example 10: ['all x ( Bike(x) -> -Car(x) )', 'all x ( Bike(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Bike(x) )']
Example 11: ['exists x ( Book(x) & -Living_Thing(x) )', 'all x ( Book(x) -> Living_Thing(x) )', 'exists x ( Living_Thing(x) & -Book(x) )']
Example 12: ['all x ( Canine(x) -> -Feline(x) )', 'all x ( Canine(x) -> Dog(x) )', 'all x ( Dog(x) -> Cat(x) )']
Example 13: ['-exists x ( Bird(x) & Triangle(x) )', 'all x ( Triangle(x) -> Shape(x) )', 'exists x ( Shape(x) & Bird(x) )']
Example 14: ['all x ( Human(x) -> Over_10_Feet_Tall(x) )', 'exists x ( Basketball_Player(x) & Human(x) )', 'exists x ( Basketball_Player(x) & Over_10_Feet_Tall(x) )']
Example 15: ['all x ( Writing_Instrument(x) -> Tool(x) )', 'exists x ( Pen(x) & Writing_Instrument(x) )', 'exists x ( Pen(x) & Tool(x) )']
----------------------------------------
Output Key: fol_otter_output_SimpEng2FOL2
Example 1: ['exists x ( Object(x) & Book(x) & -Digital_File(x) )', 'all x ( Book(x) -> Item_with_Pages(x) )', 'exists x ( Item_with_Pages(x) & Digital_File(x) )']
Example 2: ['all x ( Object(x) -> Capable_of_Flight(x) )', 'exists x ( Boat(x) & -Object(x) )']
Example 3: ['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
Example 4: ['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
Example 5: ['all x ( Fruit(x) -> Round_Object_with_Citrus_Peel(x) )', 'exists x ( Orange(x) & -Round_Object_with_Citrus_Peel(x) )', 'all x ( Fruit(x) -> Orange(x) )']
Example 6: ['all x ( Vehicle(x) -> Object(x) )', 'no x ( Car(x) & Object(x) )', 'no x ( Car(x) & Vehicle(x) )']
Example 7: ['all x ( Chair(x) -> Piece_of_Furniture(x) )', 'all x ( Chair(x) -> -Planet(x) )', 'all x ( Piece_of_Furniture(x) -> -Planet(x) )']
Example 8: ['all x ( Fruit(x) -> Food(x) )', 'all x ( Vegetable(x) -> -Food(x) )', 'all x ( Vegetable(x) -> Fruit(x) )']
Example 9: ['all x ( Elephant(x) -> -Person_enrolled_in_Kindergarten(x) )', 'all x ( Five_Years_Ago(x) -> Person_enrolled_in_Kindergarten(x) )', 'exists x ( Five_Years_Ago(x) & -Elephant(x) )']
Example 10: ['all x ( Bike(x) -> -Car(x) )', 'all x ( Bike(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Bike(x) )']
Example 11: ['exists x ( Book(x) & -Thing_with_Pages(x) )', 'all x ( Book(x) -> Living_Thing(x) )', 'exists x ( Living_Thing(x) & Thing_with_Pages(x) )']
Example 12: ['all x ( Canine(x) -> -Feline(x) )', 'all x ( Canine(x) -> Dog(x) )', 'all x ( Dog(x) -> Cat(x) )']
Example 13: ['-exists x ( Bird(x) & Triangle(x) )', 'all x ( Triangle(x) -> Shape(x) )', 'exists x ( Shape(x) & Bird(x) )']
Example 14: ['all x ( Human(x) -> Over_10_Feet_Tall(x) )', 'exists x ( Basketball_Player(x) & Human(x) )', 'exists x ( Basketball_Player(x) & Over_10_Feet_Tall(x) )']
Example 15: ['all x ( Writing_Instrument(x) -> Tool(x) )', 'exists x ( Pen(x) & Writing_Instrument(x) )', 'exists x ( Pen(x) & Tool(x) )']
----------------------------------------
Output Key: fol_otter_output_Eng2FOL2
Example 1: ['exists x ( Book(x) & -DigitalFile(x) )', 'all x ( Book(x) -> ItemWithPages(x) )', 'exists x ( ItemWithPages(x) & DigitalFile(x) )']
Example 2: ['all x ( Object(x) -> CanFly(x) )', 'exists x ( Boat(x) & -CanFly(x) )', 'all x ( Boat(x) -> NotObject(x) )']
Example 3: ['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
Example 4: ['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
Example 5: ['all x ( Fruit(x) -> Round(x) & CitrusPeel(x) )', 'exists x ( Fruit(x) & -Round(x) & -CitrusPeel(x) )', 'all x ( Fruit(x) -> Orange(x) )']
Example 6: ['all x ( Vehicle(x) -> Object(x) )', 'all x ( Car(x) -> Object(x) )', 'all x ( Car(x) -> Vehicle(x) )']
Example 7: ['all x ( Planet(x) -> -Furniture(x) )', 'all x ( Chair(x) -> Furniture(x) )', 'all x ( Chair(x) -> Planet(x) )', 'all x ( Planet(x) -> -Furniture(x) )']
Example 8: ['all x ( Fruit(x) -> Food(x) )', 'all x ( Vegetable(x) -> -Food(x) )', 'all x ( Vegetable(x) -> Fruit(x) )']
Example 9: ['all x ( Elephant(x) -> -Person(x) & KindergartenEnrolled(x) )', 'all x ( FiveYearOld(x) -> KindergartenEnrolled(x) )', 'exists x ( FiveYearOld(x) & -Elephant(x) )']
Example 10: ['all x ( Bike(x) -> Car(x) )', 'all x ( Bike(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Bike(x) )']
Example 11: ['exists x ( Book(x) & -Pages(x) )', 'all x ( Book(x) -> LivingThing(x) )', 'exists x ( LivingThing(x) & Pages(x) )']
Example 12: ['-exists x ( Canine(x) & Feline(x) )', 'all x ( Canine(x) -> Dog(x) )', 'all x ( Dog(x) -> Cat(x) )']
Example 13: ['all x ( Bird(x) -> Triangle(x) )', 'all x ( Triangle(x) -> Shape(x) )', 'exists x ( Shape(x) & Bird(x) )']
Example 14: ['all x ( Human(x) -> Height(x) > 10 )', 'exists x ( BasketballPlayer(x) & Human(x) )', 'exists x ( BasketballPlayer(x) & Height(x) > 10 )']
Example 15: ['all x ( WritingInstrument(x) -> Tool(x) )', 'exists x ( Pen(x) & WritingInstrument(x) )', 'exists x ( Pen(x) & Tool(x) )']
----------------------------------------
Output Key: fol_otter_output_Eng2FOL3
Example 1: ['exists x ( Book(x) & -DigitalFile(x) )', 'all x ( Book(x) -> ItemWithPages(x) )', 'exists x ( ItemWithPages(x) & DigitalFile(x) )']
Example 2: ['all x ( Object(x) -> Fly(x) )', 'exists x ( Boat(x) & -Fly(x) )', 'exists x ( Boat(x) & -Object(x) )']
Example 3: ['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
Example 4: ['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
Example 5: ['all x ( Fruit(x) -> Round(x) & CitrusPeel(x) )', 'exists x ( Fruit(x) & -Round(x) & -CitrusPeel(x) )', 'all x ( Fruit(x) -> Orange(x) )']
Example 6: ['all x ( Vehicle(x) -> Object(x) )', 'all x ( Car(x) -> -Vehicle(x) )', 'all x ( Car(x) -> -Object(x) )']
Example 7: ['all x ( Planet(x) -> -Furniture(x) )', 'all x ( Chair(x) -> Furniture(x) )', 'all x ( Chair(x) -> Planet(x) )']
Example 8: ['all x ( Fruit(x) -> Food(x) )', 'all x ( Vegetable(x) -> -Food(x) )', 'all x ( Vegetable(x) -> Fruit(x) )']
Example 9: ['exists x ( Elephant(x) & Person(x) & KindergartenEnrolled(x) )', 'all x ( FiveYearOld(x) -> KindergartenEnrolled(x) )', 'exists x ( FiveYearOld(x) & -Elephant(x) )']
Example 10: ['all x ( Bike(x) -> -Car(x) )', 'all x ( Bike(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Bike(x) )']
Example 11: ['exists x ( Book(x) & -Pages(x) )', 'all x ( Book(x) -> LivingThing(x) )', 'exists x ( LivingThing(x) & Pages(x) )']
Example 12: ['exists x ( Canine(x) & Feline(x) )', 'all x ( Canine(x) -> Dog(x) )', 'all x ( Dog(x) -> Cat(x) )']
Example 13: ['all x ( Bird(x) -> -Triangle(x) )', 'all x ( Triangle(x) -> Shape(x) )', 'exists x ( Shape(x) & Bird(x) )']
Example 14: ['all x ( Human(x) -> Height(x) > 10 )', 'exists x ( BasketballPlayer(x) & Human(x) )', 'exists x ( BasketballPlayer(x) & Height(x) > 10 )']
Example 15: ['all x ( WritingInstrument(x) -> Tool(x) )', 'exists x ( Pen(x) & WritingInstrument(x) )', 'exists x ( Pen(x) & Tool(x) )']
----------------------------------------
Output Key: fol_otter_output_Eng2FOL4
Example 1: ['exists x ( Book(x) & -DigitalFile(x) )', 'all x ( Book(x) -> HasPages(x) )', 'exists x ( HasPages(x) & DigitalFile(x) )']
Example 2: ['all x ( Object(x) -> Fly(x) )', 'exists x ( Boat(x) & -Fly(x) )', 'exists x ( Boat(x) & -Object(x) )']
Example 3: ['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
Example 4: ['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
Example 5: ['all x ( Fruit(x) -> Round(x) & CitrusPeel(x) )', 'exists x ( Orange(x) & -(Round(x) & CitrusPeel(x)) )', 'all x ( Fruit(x) -> Orange(x) )']

### Local Evaluation

In [28]:
dataset = load_data(file_name_generations)

In [29]:
data_type

'test_subtask1'

In [30]:
dataset_df = pd.DataFrame(dataset)
print(dataset_df.shape)
dataset_df.head(3)

(191, 202)

,id,syllogism,fol_otter_output_Eng2FOL,fol_otter_output_Eng2FOL10Qwen4B,fol_otter_output_Eng2FOL10,fol_otter_output_Eng2FOL11,fol_otter_output_Eng2FOL2,fol_otter_output_Eng2FOL3,fol_otter_output_Eng2FOL4,fol_otter_output_Eng2FOL5Gemma2B,...,SimpEng2SyllogismProlog_aristotelian_type,from_syllogism_aristotelian_truth,from_syllogism_aristotelian_type,from_syllogism_simplified_Simp1_aristotelian_truth,from_syllogism_simplified_Simp1_aristotelian_type,from_syllogism_simplified_Simp2_aristotelian_truth,from_syllogism_simplified_Simp2_aristotelian_type,validity,plausibility,dni_validity
0,f36a4ca3-3b69-4869-a152-deaa7e0fdad4,There exist some objects that are books which ...,"[exists x ( Book(x) & -DigitalFile(x) ), all x...",[exists x ( (Object(x) & Book(x)) & -DigitalFi...,[exists x ( (Object(x) & Book(x)) & -DigitalFi...,"[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...",...,unknown,None,none,False,unknown,False,unknown,False,True,False
1,e773bd8c-fa53-4e9c-8ec6-7d978e0601ac,Every single object can fly. It is known that ...,"[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...",...,error,False,error,False,error,False,error,True,False,False
2,b73d8e0e-782e-4e60-866b-595cf13a3421,No animal is a rock. Some rocks are plants. Fr...,"[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...","[all x ( Animal(x) -> -Rock(x) ), exists x ( R...",...,unknown,False,error,False,unknown,False,unknown,False,False,False

In [31]:
[col for col in dataset[1].keys() if "Eng2FOL10Qwen4B" in col]
dataset[1]["fol_otter_output_Eng2FOL10Qwen4B"], dataset[1]["otter_answer_fol_otter_output_Eng2FOL10Qwen4B"]

(['all x ( Object(x) -> CanFly(x) )',
  'exists x ( Boat(x) & -CanFly(x) )',
  'exists x ( Boat(x) & -Object(x) )'],
 True)

In [32]:
[col for col in dataset[1].keys() if "_from_" in col]
dataset[1]["fol_output_from_syllogism_simplified_Simp1"], dataset[1]["otter_answer_fol_output_from_syllogism_simplified_Simp1"]

(['all x (Object(x) -> Can_Fly(x))', 'exists x (Boat(x) & Not_Object(x))'],
 False)

##### Tabelle mit Ergebnissen

In [33]:
fol_prediction_keys = [col for col in dataset[1].keys() if col.startswith("fol_otter_output_") or col.startswith("fol_output_") ]
truth_keys = [x for x in dataset.features if "truth" in x]
all_predictions_keys = [key for key in dataset.features if key in truth_keys or key in fol_prediction_keys]
# append dni_validity to all_predictions_keys if it exists
if "dni_validity" in dataset.features:
    all_predictions_keys.append("dni_validity")
    # convert dni_validity to boolean
    dataset = dataset.map(lambda x: {"dni_validity": True if x["dni_validity"] == "True" else False if x["dni_validity"] == "False" else None})
all_predictions_keys

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

['fol_otter_output_Eng2FOL',
 'fol_otter_output_Eng2FOL10Qwen4B',
 'fol_otter_output_Eng2FOL10',
 'fol_otter_output_Eng2FOL11',
 'fol_otter_output_Eng2FOL2',
 'fol_otter_output_Eng2FOL3',
 'fol_otter_output_Eng2FOL4',
 'fol_otter_output_Eng2FOL5Gemma2B',
 'fol_otter_output_Eng2FOL5Qwen0.6B',
 'fol_otter_output_Eng2FOL5Qwen1.7B',
 'fol_otter_output_Eng2FOL5Qwen4B',
 'fol_otter_output_Eng2FOL5',
 'fol_otter_output_Eng2FOL5small',
 'fol_otter_output_Eng2FOL5tiny',
 'fol_otter_output_Eng2FOL6',
 'fol_otter_output_Eng2FOL7',
 'fol_otter_output_Eng2FOL8',
 'fol_otter_output_Eng2FOL9Qwen4B',
 'fol_otter_output_Eng2FOL9',
 'fol_otter_output_QwenEng2FOL1',
 'fol_otter_output_QwenEng2FOL2',
 'fol_otter_output_QwenEng2FOL3',
 'fol_otter_output_QwenEng2FOL4',
 'fol_otter_output_QwenEng2FOL5',
 'fol_otter_output_QwenEng2FOL6',
 'fol_otter_output_SimpEng2FOL1',
 'fol_otter_output_SimpEng2FOL2',
 'fol_output_from_syllogism',
 'fol_output_from_syllogism_simplified_Simp1',
 'fol_output_from_syllogism_simplified_Simp2',
 'Eng2SyllogismProlog_aristotelian_truth',
 'SimpEng2SyllogismProlog_aristotelian_truth',
 'from_syllogism_aristotelian_truth',
 'from_syllogism_simplified_Simp1_aristotelian_truth',
 'from_syllogism_simplified_Simp2_aristotelian_truth',
 'dni_validity']

In [34]:
truth_keys

['Eng2SyllogismProlog_aristotelian_truth',
 'SimpEng2SyllogismProlog_aristotelian_truth',
 'from_syllogism_aristotelian_truth',
 'from_syllogism_simplified_Simp1_aristotelian_truth',
 'from_syllogism_simplified_Simp2_aristotelian_truth']

In [35]:
dataset["dni_validity"][0:20]

[False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 None,
 None]

In [36]:
from reasoning.evaluation_utils import my_evaluate_subtask_1_3
# only for train data
def calculate_experiment_metrics(df, fol_input_keys):
    """
    Calculates proof statistics and confusion matrix for each FOL experiment
    compared to the ground truth 'validity' column.
    """
    metrics_list = []

    for key in fol_input_keys:
        if key in fol_prediction_keys:
            ans_col = f'otter_answer_{key}' ######
        else:
            ans_col = key
        if ans_col not in df.columns:
            print(f"⚠️ Column {ans_col} not found in dataset. Skipping.")
            continue
        print(ans_col)
        print(df[ans_col].value_counts())

        # Ground Truth: 'validity' (True/False)
        # Prediction: ans_col (True/False/None)

        total = len(df)
        # We handle None/Error as False for the sake of the confusion matrix
        # or treat them as separate 'Errors'
        preds = df[ans_col].fillna(False)
        actual = df['validity']

        print(preds.value_counts() )

        # Logic for Confusion Matrix
        tp = ((preds == True) & (actual == True)).sum()
        tn = ((preds == False) & (actual == False)).sum()
        fp = ((preds == True) & (actual == False)).sum()
        fn = ((preds == False) & (actual == True)).sum()

        # Count technical errors (None values)
        errors = df[ans_col].isna().sum()

        # Compile bias metrics
        df[ans_col] = df[ans_col].fillna(False)
        prediction_df = df[['id', ans_col, 'validity', 'plausibility']].rename(columns={ans_col: 'prediction'})
        bias_metrics = my_evaluate_subtask_1_3(prediction_df)
                            


        metrics_list.append({
            'Experiment': key,
            'Total': total,
#            'TP (Correct Proof)': tp,
#            'TN (Correct Disproof)': tn,
            'FP (False Proof)': fp,
            'FN (Missed Proof)': fn,
            'Errors': errors,
#            'Accuracy': (tp + tn) / total if total > 0 else 0,
            **bias_metrics
        })

    return pd.DataFrame(metrics_list)

# Usage:
df_results = pd.DataFrame(dataset)
summary_table = calculate_experiment_metrics(df_results, all_predictions_keys)
df_results = pd.DataFrame(summary_table)


df_results

otter_answer_fol_otter_output_Eng2FOL
False    99
True     90
Name: otter_answer_fol_otter_output_Eng2FOL, dtype: int64
False    101
True      90
Name: otter_answer_fol_otter_output_Eng2FOL, dtype: int64
otter_answer_fol_otter_output_Eng2FOL10Qwen4B
False    97
True     94
Name: otter_answer_fol_otter_output_Eng2FOL10Qwen4B, dtype: int64
False    97
True     94
Name: otter_answer_fol_otter_output_Eng2FOL10Qwen4B, dtype: int64
otter_answer_fol_otter_output_Eng2FOL10
False    109
True      80
Name: otter_answer_fol_otter_output_Eng2FOL10, dtype: int64
False    111
True      80
Name: otter_answer_fol_otter_output_Eng2FOL10, dtype: int64
otter_answer_fol_otter_output_Eng2FOL11
False    64
True     27
Name: otter_answer_fol_otter_output_Eng2FOL11, dtype: int64
False    164
True      27
Name: otter_answer_fol_otter_output_Eng2FOL11, dtype: int64
otter_answer_fol_otter_output_Eng2FOL2
False    107
True      79
Name: otter_answer_fol_otter_output_Eng2FOL2, dtype: int64
False    112
True      79
Name: otter_answer_fol_otter_output_Eng2FOL2, dtype: int64
otter_answer_fol_otter_output_Eng2FOL3
False    103
True      86
Name: otter_answer_fol_otter_output_Eng2FOL3, dtype: int64
False    105
True      86
Name: otter_answer_fol_otter_output_Eng2FOL3, dtype: int64
otter_answer_fol_otter_output_Eng2FOL4
False    100
True      90
Name: otter_answer_fol_otter_output_Eng2FOL4, dtype: int64
False    101
True      90
Name: otter_answer_fol_otter_output_Eng2FOL4, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5Gemma2B
False    108
True      77
Name: otter_answer_fol_otter_output_Eng2FOL5Gemma2B, dtype: int64
False    114
True      77
Name: otter_answer_fol_otter_output_Eng2FOL5Gemma2B, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B
False    102
True      70
Name: otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B, dtype: int64
False    121
True      70
Name: otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B
False    95
True     95
Name: otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B, dtype: int64
False    96
True     95
Name: otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5Qwen4B
True     96
False    94
Name: otter_answer_fol_otter_output_Eng2FOL5Qwen4B, dtype: int64
True     96
False    95
Name: otter_answer_fol_otter_output_Eng2FOL5Qwen4B, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5
False    96
True     95
Name: otter_answer_fol_otter_output_Eng2FOL5, dtype: int64
False    96
True     95
Name: otter_answer_fol_otter_output_Eng2FOL5, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5small
False    103
True      78
Name: otter_answer_fol_otter_output_Eng2FOL5small, dtype: int64
False    113
True      78
Name: otter_answer_fol_otter_output_Eng2FOL5small, dtype: int64
otter_answer_fol_otter_output_Eng2FOL5tiny
True     129
False     52
Name: otter_answer_fol_otter_output_Eng2FOL5tiny, dtype: int64
True     129
False     62
Name: otter_answer_fol_otter_output_Eng2FOL5tiny, dtype: int64
otter_answer_fol_otter_output_Eng2FOL6
True     96
False    94
Name: otter_answer_fol_otter_output_Eng2FOL6, dtype: int64
True     96
False    95
Name: otter_answer_fol_otter_output_Eng2FOL6, dtype: int64
otter_answer_fol_otter_output_Eng2FOL7
True     98
False    91
Name: otter_answer_fol_otter_output_Eng2FOL7, dtype: int64
True     98
False    93
Name: otter_answer_fol_otter_output_Eng2FOL7, dtype: int64
otter_answer_fol_otter_output_Eng2FOL8
False    101
True      89
Name: otter_answer_fol_otter_output_Eng2FOL8, dtype: int64
False    102
True      89
Name: otter_answer_fol_otter_output_Eng2FOL8, dtype: int64
otter_answer_fol_otter_output_Eng2FOL9Qwen4B
True     91
False    88
Name: otter_answer_fol_otter_output_Eng2FOL9Qwen4B, dtype: int64
False    100
True      91
Name: otter_answer_fol_otter_output_Eng2FOL9Qwen4B, dtype: int64
otter_answer_fol_otter_output_Eng2FOL9
False    108
True      80
Name: otter_answer_fol_otter_output_Eng2FOL9, dtype: int64
False    111
True      80
Name: otter_answer_fol_otter_output_Eng2FOL9, dtype: int64
otter_answer_fol_otter_output_QwenEng2FOL1
False    96
True     92
Name: otter_answer_fol_otter_output_QwenEng2FOL1, dtype: int64
False    99
True     92
Name: otter_answer_fol_otter_output_QwenEng2FOL1, dtype: int64
otter_answer_fol_otter_output_QwenEng2FOL2
True     93
False    93
Name: otter_answer_fol_otter_output_QwenEng2FOL2, dtype: int64
False    98
True     93
Name: otter_answer_fol_otter_output_QwenEng2FOL2, dtype: int64
otter_answer_fol_otter_output_QwenEng2FOL3
True     94
False    85
Name: otter_answer_fol_otter_output_QwenEng2FOL3, dtype: int64
False    97
True     94
Name: otter_answer_fol_otter_output_QwenEng2FOL3, dtype: int64
otter_answer_fol_otter_output_QwenEng2FOL4
True     97
False    93
Name: otter_answer_fol_otter_output_QwenEng2FOL4, dtype: int64
True     97
False    94
Name: otter_answer_fol_otter_output_QwenEng2FOL4, dtype: int64
otter_answer_fol_otter_output_QwenEng2FOL5
False    96
True     94
Name: otter_answer_fol_otter_output_QwenEng2FOL5, dtype: int64
False    97
True     94
Name: otter_answer_fol_otter_output_QwenEng2FOL5, dtype: int64
otter_answer_fol_otter_output_QwenEng2FOL6
False    97
True     94
Name: otter_answer_fol_otter_output_QwenEng2FOL6, dtype: int64
False    97
True     94
Name: otter_answer_fol_otter_output_QwenEng2FOL6, dtype: int64
otter_answer_fol_otter_output_SimpEng2FOL1
False    110
True      79
Name: otter_answer_fol_otter_output_SimpEng2FOL1, dtype: int64
False    112
True      79
Name: otter_answer_fol_otter_output_SimpEng2FOL1, dtype: int64
otter_answer_fol_otter_output_SimpEng2FOL2
False    113
True      77
Name: otter_answer_fol_otter_output_SimpEng2FOL2, dtype: int64
False    114
True      77
Name: otter_answer_fol_otter_output_SimpEng2FOL2, dtype: int64
otter_answer_fol_output_from_syllogism
False    70
Name: otter_answer_fol_output_from_syllogism, dtype: int64
False    191
Name: otter_answer_fol_output_from_syllogism, dtype: int64
otter_answer_fol_output_from_syllogism_simplified_Simp1
False    114
True      74
Name: otter_answer_fol_output_from_syllogism_simplified_Simp1, dtype: int64
False    117
True      74
Name: otter_answer_fol_output_from_syllogism_simplified_Simp1, dtype: int64
otter_answer_fol_output_from_syllogism_simplified_Simp2
False    110
True      78
Name: otter_answer_fol_output_from_syllogism_simplified_Simp2, dtype: int64
False    113
True      78
Name: otter_answer_fol_output_from_syllogism_simplified_Simp2, dtype: int64
Eng2SyllogismProlog_aristotelian_truth
False    122
True      69
Name: Eng2SyllogismProlog_aristotelian_truth, dtype: int64
False    122
True      69
Name: Eng2SyllogismProlog_aristotelian_truth, dtype: int64
SimpEng2SyllogismProlog_aristotelian_truth
False    121
True      70
Name: SimpEng2SyllogismProlog_aristotelian_truth, dtype: int64
False    121
True      70
Name: SimpEng2SyllogismProlog_aristotelian_truth, dtype: int64
from_syllogism_aristotelian_truth
False    65
Name: from_syllogism_aristotelian_truth, dtype: int64
False    191
Name: from_syllogism_aristotelian_truth, dtype: int64
from_syllogism_simplified_Simp1_aristotelian_truth
False    123
True      68
Name: from_syllogism_simplified_Simp1_aristotelian_truth, dtype: int64
False    123
True      68
Name: from_syllogism_simplified_Simp1_aristotelian_truth, dtype: int64
from_syllogism_simplified_Simp2_aristotelian_truth
False    120
True      71
Name: from_syllogism_simplified_Simp2_aristotelian_truth, dtype: int64
False    120
True      71
Name: from_syllogism_simplified_Simp2_aristotelian_truth, dtype: int64
dni_validity
True     103
False     63
Name: dni_validity, dtype: int64
True     103
False     88
Name: dni_validity, dtype: int64

,Experiment,Total,FP (False Proof),FN (Missed Proof),Errors,accuracy,content_effect,combined_score,intra_bias,inter_bias,acc_plausible_valid,acc_implausible_valid,acc_plausible_invalid,acc_implausible_invalid
0,fol_otter_output_Eng2FOL,191,5,11,2,91.6230,4.1667,34.6764,2.1498,6.1835,89.5833,87.5000,93.6170,95.8333
1,fol_otter_output_Eng2FOL10Qwen4B,191,3,5,0,95.8115,4.1667,36.2616,6.3165,2.0168,91.6667,97.9167,93.6170,100.0000
2,fol_otter_output_Eng2FOL10,191,4,20,2,87.4346,12.5000,24.2692,8.3998,16.6002,72.9167,85.4167,93.6170,97.9167
3,fol_otter_output_Eng2FOL11,191,0,69,100,63.8743,37.5000,13.7345,3.1250,71.8750,25.0000,31.2500,100.0000,100.0000
4,fol_otter_output_Eng2FOL2,191,14,31,5,76.4398,9.3750,22.8903,1.1968,17.5532,68.7500,66.6667,85.1064,85.4167
5,fol_otter_output_Eng2FOL3,191,9,19,2,85.3403,10.3502,24.8861,10.3502,10.3502,72.9167,87.5000,93.6170,87.5000
6,fol_otter_output_Eng2FOL4,191,5,11,1,91.6230,6.2500,30.7357,6.3387,6.1613,85.4167,91.6667,91.4894,97.9167
7,fol_otter_output_Eng2FOL5Gemma2B,191,14,33,6,75.3927,16.6667,19.4729,13.7855,19.5479,60.4167,70.8333,76.5957,93.7500
8,fol_otter_output_Eng2FOL5Qwen0.6B,191,17,43,19,68.5864,17.5754,17.4883,8.2004,26.9504,52.0833,58.3333,87.2340,77.0833
9,fol_otter_output_Eng2FOL5Qwen1.7B,191,3,4,1,96.3351,3.1915,39.5943,3.1915,3.1915,95.8333,95.8333,93.6170,100.0000
10,fol_otter_output_Eng2FOL5Qwen4B,191,3,3,1,96.8586,3.1915,39.8095,6.3165,0.0665,93.7500,100.0000,93.6170,100.0000
11,fol_otter_output_Eng2FOL5,191,4,5,0,95.2880,2.1498,44.3748,3.1915,1.1082,93.7500,95.8333,93.6170,97.9167
12,fol_otter_output_Eng2FOL5small,191,23,41,10,66.4921,14.5833,17.7492,10.7270,18.4397,62.5000,52.0833,70.2128,81.2500
13,fol_otter_output_Eng2FOL5tiny,191,62,29,10,52.3560,23.9583,12.4149,12.9876,34.9291,70.8333,68.7500,46.8085,22.9167
14,fol_otter_output_Eng2FOL6,191,5,5,1,94.7644,3.2137,38.8645,6.3387,0.0887,91.6667,97.9167,91.4894,97.9167
15,fol_otter_output_Eng2FOL7,191,4,2,2,96.8586,3.1915,39.8095,4.2332,2.1498,95.8333,100.0000,93.6170,97.9167
16,fol_otter_output_Eng2FOL8,191,5,12,1,91.0995,5.2083,32.2374,3.2137,7.2030,87.5000,87.5000,91.4894,97.9167
17,fol_otter_output_Eng2FOL9Qwen4B,191,3,8,12,94.2408,7.2917,30.2514,9.4415,5.1418,85.4167,97.9167,93.6170,100.0000
18,fol_otter_output_Eng2FOL9,191,5,21,3,86.3874,12.5000,23.9786,8.3998,16.6002,70.8333,85.4167,93.6170,95.8333
19,fol_otter_output_QwenEng2FOL1,191,3,7,3,94.7644,4.1667,35.8653,4.2332,4.1002,91.6667,93.7500,93.6170,100.0000
20,fol_otter_output_QwenEng2FOL2,191,3,6,5,95.2880,4.1667,36.0635,5.2748,3.0585,91.6667,95.8333,93.6170,100.0000
21,fol_otter_output_QwenEng2FOL3,191,5,7,12,93.7173,2.0833,44.0813,2.1498,2.0168,91.6667,93.7500,93.6170,95.8333
22,fol_otter_output_QwenEng2FOL4,191,3,2,1,97.3822,3.1915,40.0246,5.2748,1.1082,95.8333,100.0000,93.6170,100.0000
23,fol_otter_output_QwenEng2FOL5,191,3,5,1,95.8115,4.1667,36.2616,6.3165,2.0168,91.6667,97.9167,93.6170,100.0000
24,fol_otter_output_QwenEng2FOL6,191,3,5,0,95.8115,5.2083,33.9049,8.3998,2.0168,89.5833,100.0000,93.6170,100.0000
25,fol_otter_output_SimpEng2FOL1,191,5,22,2,85.8639,12.5000,23.8333,7.3582,17.6418,70.8333,83.3333,93.6170,95.8333
26,fol_otter_output_SimpEng2FOL2,191,6,25,1,83.7696,14.5833,22.3612,9.4858,19.6809,68.7500,79.1667,89.3617,97.9167
27,fol_output_from_syllogism,191,0,96,121,49.7382,50.0000,10.0852,0.0000,100.0000,0.0000,0.0000,100.0000,100.0000
28,fol_output_from_syllogism_simplified_Simp1,191,2,24,3,86.3874,14.5833,23.0600,6.2943,22.8723,70.8333,79.1667,95.7447,100.0000
29,fol_output_from_syllogism_simplified_Simp2,191,6,24,3,84.2932,13.5417,22.9243,8.4441,18.6392,70.8333,79.1667,89.3617,97.9167
30,Eng2SyllogismProlog_aristotelian_truth,191,13,40,0,72.2513,18.6613,18.1597,9.2863,28.0363,54.1667,62.5000,91.4894,81.2500
31,SimpEng2SyllogismProlog_aristotelian_truth,191,9,35,0,76.9634,14.4947,20.5757,1.9947,26.9947,64.5833,62.5000,91.4894,89.5833
32,from_syllogism_aristotelian_truth,191,0,96,126,49.7382,50.0000,10.0852,0.0000,100.0000,0.0000,0.0000,100.0000,100.0000
33,from_syllogism_simplified_Simp1_aristotelian_t...,191,0,28,0,85.3403,18.7500,21.4253,8.3333,29.1667,62.5000,79.1667,100.0000,100.0000
34,from_syllogism_simplified_Simp2_aristotelian_t...,191,4,29,0,82.7225,19.7917,20.5035,13.6082,25.9752,58.3333,81.2500,93.6170,97.9167
35,dni_validity,191,45,38,25,56.5445,24.5124,13.3386,24.5124,24.5124,79.1667,41.6667,46.8085,58.3333

In [37]:
def read_id(string):
    if string.startswith("fol_"):
        return string.split("_")[-1]
    elif string.startswith("from_syllogism_simplified_"):
        return string.split("from_syllogism_simplified_")[1].split("_")[0]
    elif string.endswith("_aristotelian_truth"):
        return string.split("_aristotelian_truth")[0]

In [38]:
# read examples from examples.json
examples = json.load(open("prompts/examples.json"))
# dataframe with example name and length
ex_ids =[]
ex_number = []
ex_lengths = []
max_len = []
min_len = []
av_len = []
for ex in examples:
    ex_ids.append(ex)
    ex_number.append(len(examples[ex]))
    lengths = []
    for e in examples[ex]:
        lengths.append(len(e[1]))
    ex_lengths.append([lengths])
    av_len.append(sum(lengths)/len(lengths))
    max_len.append(max(lengths))
    min_len.append(min(lengths))

examples_df = pd.DataFrame({'Example_ID': ex_ids, 'Number': ex_number, 'Max_Length': max_len, 'Min_Length': min_len, 'Average_Length': av_len, 'Lengths': ex_lengths})
examples_df

,Example_ID,Number,Max_Length,Min_Length,Average_Length,Lengths
0,LogSimpEx,5,4,3,3.400,"[[4, 4, 3, 3, 3]]"
1,SyllTripEx,4,4,3,3.750,"[[4, 4, 3, 4]]"
2,SimpSyllTripEx,4,4,3,3.750,"[[4, 4, 3, 4]]"
3,Eng2FOLex,3,3,3,3.000,"[[3, 3, 3]]"
4,Eng2FOLexImproved,5,4,3,3.200,"[[3, 3, 3, 4, 3]]"
5,Eng2FOLexImprovedX,8,4,3,3.125,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
6,Eng2FOLexImproved2,8,5,3,3.625,"[[5, 3, 4, 3, 3, 3, 3, 5]]"
7,Eng2FOLexVaried,8,3,3,3.000,"[[3, 3, 3, 3, 3, 3, 3, 3]]"
8,MultiLingexImproved,22,3,3,3.000,"[[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,..."
9,MultiLingexImprovedShort,6,3,3,3.000,"[[3, 3, 3, 3, 3, 3]]"
10,Eng2FOLexLong,4,8,7,7.500,"[[7, 7, 8, 8]]"

In [39]:
def get_length_prompt(prompt_name):
    # read md file prompt_name.md
    with open(f"prompts/{prompt_name}.md", "r") as f:
        prompt = f.read()
    return len(prompt)

In [40]:
df_config = pd.DataFrame(configs['experiments'])
df_results["ExpID"] = None
df_results["ExpID"] = df_results["Experiment"].apply(read_id)
# add model column with vaulues from df_config. Identify the model based on ExpID. ExpID is column in df_config

df_results["Model"] = df_results["ExpID"].apply(lambda x: df_config[x]["model"].split("/")[-1] if x in df_config else "Unknown")
df_results["Prompt"] = df_results["ExpID"].apply(lambda x: df_config[x]["system_prompt"] if x in df_config else "Unknown")
df_results["Prompt_Length"] = df_results["ExpID"].apply(lambda x: get_length_prompt(df_config[x]["system_prompt"]) if x in df_config else 0)
df_results["input_key"] = df_results["ExpID"].apply(lambda x: df_config[x]["input_key"] if x in df_config else "Unknown")
df_results["Examples"] = df_results["ExpID"].apply(lambda x: df_config[x]["examples"] if x in df_config else "Unknown")
# ad column "#examples" with number of examples from examples_df. Identify by Examples_Id column in examples_df and Examples column in df_results

df_results["#Examples"] = df_results["Examples"].apply(lambda x: examples_df[examples_df["Example_ID"] == x]["Number"].values[0] if x in examples_df["Example_ID"].values else 0)
df_results["Example_Lengths"] = df_results["Examples"].apply(lambda x: examples_df[examples_df["Example_ID"] == x]["Lengths"].values[0] if x in examples_df["Example_ID"].values else [])
display(df_results)

import csv
df_results.to_csv(data_type + "_experiment_summary_results.csv", index=False)

,Experiment,Total,FP (False Proof),FN (Missed Proof),Errors,accuracy,content_effect,combined_score,intra_bias,inter_bias,...,acc_plausible_invalid,acc_implausible_invalid,ExpID,Model,Prompt,Prompt_Length,input_key,Examples,#Examples,Example_Lengths
0,fol_otter_output_Eng2FOL,191,5,11,2,91.6230,4.1667,34.6764,2.1498,6.1835,...,93.6170,95.8333,Eng2FOL,SmolLM3-3B,Eng2FOL,1721,syllogism,Eng2FOLex,3,"[[3, 3, 3]]"
1,fol_otter_output_Eng2FOL10Qwen4B,191,3,5,0,95.8115,4.1667,36.2616,6.3165,2.0168,...,93.6170,100.0000,Eng2FOL10Qwen4B,Qwen3-4B-Instruct-2507,Eng2FOLimproved,1634,syllogism,Eng2FOLexVaried,8,"[[3, 3, 3, 3, 3, 3, 3, 3]]"
2,fol_otter_output_Eng2FOL10,191,4,20,2,87.4346,12.5000,24.2692,8.3998,16.6002,...,93.6170,97.9167,Eng2FOL10,SmolLM3-3B,Eng2FOLimproved,1634,syllogism,Eng2FOLexVaried,8,"[[3, 3, 3, 3, 3, 3, 3, 3]]"
3,fol_otter_output_Eng2FOL11,191,0,69,100,63.8743,37.5000,13.7345,3.1250,71.8750,...,100.0000,100.0000,Eng2FOL11,gemma-3-4b-it,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
4,fol_otter_output_Eng2FOL2,191,14,31,5,76.4398,9.3750,22.8903,1.1968,17.5532,...,85.1064,85.4167,Eng2FOL2,Llama-3.2-3B-Instruct,Eng2FOLimproved,1634,syllogism,Eng2FOLexImproved,5,"[[3, 3, 3, 4, 3]]"
5,fol_otter_output_Eng2FOL3,191,9,19,2,85.3403,10.3502,24.8861,10.3502,10.3502,...,93.6170,87.5000,Eng2FOL3,Llama-3.2-3B-Instruct,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
6,fol_otter_output_Eng2FOL4,191,5,11,1,91.6230,6.2500,30.7357,6.3387,6.1613,...,91.4894,97.9167,Eng2FOL4,SmolLM3-3B,Eng2FOLimproved,1634,syllogism,Eng2FOLexImproved,5,"[[3, 3, 3, 4, 3]]"
7,fol_otter_output_Eng2FOL5Gemma2B,191,14,33,6,75.3927,16.6667,19.4729,13.7855,19.5479,...,76.5957,93.7500,Eng2FOL5Gemma2B,gemma-2-2b-it,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
8,fol_otter_output_Eng2FOL5Qwen0.6B,191,17,43,19,68.5864,17.5754,17.4883,8.2004,26.9504,...,87.2340,77.0833,Eng2FOL5Qwen0.6B,Qwen3-0.6B,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
9,fol_otter_output_Eng2FOL5Qwen1.7B,191,3,4,1,96.3351,3.1915,39.5943,3.1915,3.1915,...,93.6170,100.0000,Eng2FOL5Qwen1.7B,Qwen3-1.7B,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
10,fol_otter_output_Eng2FOL5Qwen4B,191,3,3,1,96.8586,3.1915,39.8095,6.3165,0.0665,...,93.6170,100.0000,Eng2FOL5Qwen4B,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
11,fol_otter_output_Eng2FOL5,191,4,5,0,95.2880,2.1498,44.3748,3.1915,1.1082,...,93.6170,97.9167,Eng2FOL5,SmolLM3-3B,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
12,fol_otter_output_Eng2FOL5small,191,23,41,10,66.4921,14.5833,17.7492,10.7270,18.4397,...,70.2128,81.2500,Eng2FOL5small,SmolLM2-1.7B-Instruct,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
13,fol_otter_output_Eng2FOL5tiny,191,62,29,10,52.3560,23.9583,12.4149,12.9876,34.9291,...,46.8085,22.9167,Eng2FOL5tiny,SmolLM2-135M-Instruct,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
14,fol_otter_output_Eng2FOL6,191,5,5,1,94.7644,3.2137,38.8645,6.3387,0.0887,...,91.4894,97.9167,Eng2FOL6,SmolLM3-3B,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImproved,5,"[[3, 3, 3, 4, 3]]"
15,fol_otter_output_Eng2FOL7,191,4,2,2,96.8586,3.1915,39.8095,4.2332,2.1498,...,93.6170,97.9167,Eng2FOL7,SmolLM3-3B,Eng2FOL,1721,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
16,fol_otter_output_Eng2FOL8,191,5,12,1,91.0995,5.2083,32.2374,3.2137,7.2030,...,91.4894,97.9167,Eng2FOL8,SmolLM3-3B,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImproved2,8,"[[5, 3, 4, 3, 3, 3, 3, 5]]"
17,fol_otter_output_Eng2FOL9Qwen4B,191,3,8,12,94.2408,7.2917,30.2514,9.4415,5.1418,...,93.6170,100.0000,Eng2FOL9Qwen4B,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syllogism,Eng2FOLexVaried,8,"[[3, 3, 3, 3, 3, 3, 3, 3]]"
18,fol_otter_output_Eng2FOL9,191,5,21,3,86.3874,12.5000,23.9786,8.3998,16.6002,...,93.6170,95.8333,Eng2FOL9,SmolLM3-3B,Eng2FOLUltrashort,320,syllogism,Eng2FOLexVaried,8,"[[3, 3, 3, 3, 3, 3, 3, 3]]"
19,fol_otter_output_QwenEng2FOL1,191,3,7,3,94.7644,4.1667,35.8653,4.2332,4.1002,...,93.6170,100.0000,QwenEng2FOL1,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImproved2,8,"[[5, 3, 4, 3, 3, 3, 3, 5]]"
20,fol_otter_output_QwenEng2FOL2,191,3,6,5,95.2880,4.1667,36.0635,5.2748,3.0585,...,93.6170,100.0000,QwenEng2FOL2,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syllogism,Eng2FOLexImproved,5,"[[3, 3, 3, 4, 3]]"
21,fol_otter_output_QwenEng2FOL3,191,5,7,12,93.7173,2.0833,44.0813,2.1498,2.0168,...,93.6170,95.8333,QwenEng2FOL3,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syllogism,Eng2FOLex,3,"[[3, 3, 3]]"
22,fol_otter_output_QwenEng2FOL4,191,3,2,1,97.3822,3.1915,40.0246,5.2748,1.1082,...,93.6170,100.0000,QwenEng2FOL4,Qwen3-4B-Instruct-2507,Eng2FOLimproved,1634,syllogism,Eng2FOLexImproved,5,"[[3, 3, 3, 4, 3]]"
23,fol_otter_output_QwenEng2FOL5,191,3,5,1,95.8115,4.1667,36.2616,6.3165,2.0168,...,93.6170,100.0000,QwenEng2FOL5,Qwen3-4B-Instruct-2507,Eng2FOL,1721,syllogism,Eng2FOLexImproved,5,"[[3, 3, 3, 4, 3]]"
24,fol_otter_output_QwenEng2FOL6,191,3,5,0,95.8115,5.2083,33.9049,8.3998,2.0168,...,93.6170,100.0000,QwenEng2FOL6,Qwen3-4B-Instruct-2507,Eng2FOLimproved,1634,syllogism,Eng2FOLexImprovedX,8,"[[3, 3, 4, 3, 3, 3, 3, 3]]"
25,fol_otter_output_SimpEng2FOL1,191,5,22,2,85.8639,12.5000,23.8333,7.3582,17.6418,...,93.6170,95.8333,SimpEng2FOL1,SmolLM3-3B,Eng2FOL,1721,syllogism_simplified_Simp1,Eng2FOLex,3,"[[3, 3, 3]]"
26,fol_otter_output_SimpEng2FOL2,191,6,25,1,83.7696,14.5833,22.3612,9.4858,19.6809,...,89.3617,97.9167,SimpEng2FOL2,SmolLM3-3B,Eng2FOL,1721,syllogism_simplified_Simp2,Eng2FOLex,3,"[[3, 3, 3]]"
27,fol_output_from_syllogism,191,0,96,121,49.7382,50.0000,10.0852,0.0000,100.0000,...,100.0000,100.0000,syllogism,Unknown,Unknown,0,Unknown,Unknown,0,[]
28,fol_output_from_syllogism_simplified_Simp1,191,2,24,3,86.3874,14.5833,23.0600,6.2943,22.8723,...,95.7447,100.0000,Simp1,SmolLM3-3B,LogSimp,1572,syllogism,LogSimpEx,5,"[[4, 4, 3, 3, 3]]"
29,fol_output_from_syllogism_simplified_Simp2,191,6,24,3,84.2932,13.5417,22.9243,8.4441,18.6392,...,89.3617,97.9167,Simp2,SmolLM3-3B,LogSimpShortPrompt,1016,syllogism,LogSimpEx,5,"[[4, 4, 3, 3, 3]]"
30,Eng2SyllogismProlog_aristotelian_truth,191,13,40,0,72.2513,18.6613,18.1597,9.2863,28.0363,...,91.4894,81.2500,Eng2SyllogismProlog,SmolLM3-3B,SyllTrip,1254,syllogism,SyllTripEx,4,"[[4, 4, 3, 4]]"
31,SimpEng2SyllogismProlog_aristotelian_truth,191,9,35,0,76.9634,14.4947,20.5757,1.9947,26.9947,...,91.4894,89.5833,SimpEng2SyllogismProlog,SmolLM3-3B,SyllTrip,1254,syllogism_simplified_Simp1,SimpSyllTripEx,4,"[[4, 4, 3, 4]]"
32,from_syllogism_aristotelian_truth,191,0,96,126,49.7382,50.0000,10.0852,0.0000,100.0000,...,100.0000,100.0000,from_syllogism,Unknown,Unknown,0,Unknown,Unknown,0,[]
33,from_syllogism_simplified_Simp1_aristotelian_t...,191,0,28,0,85.3403,18.7500,21.4253,8.3333,29.1667,...,100.0000,100.0000,Simp1,SmolLM3-3B,LogSimp,1572,syllogism,LogSimpEx,5,"[[4, 4, 3, 3, 3]]"
34,from_syllogism_simplified_Simp2_aristotelian_t...,191,4,29,0,82.7225,19.7917,20.5035,13.6082,25.9752,...,93.6170,97.9167,Simp2,SmolLM3-3B,LogSimpShortPrompt,1016,syllogism,LogSimpEx,5,"[[4, 4, 3, 3, 3]]"
35,dni_validity,191,45,38,25,56.5445,24.5124,13.3386,24.5124,24.5124,...,46.8085,58.3333,None,Unknown,Unknown,0,Unknown,Unknown,0,[]

In [ ]:
all_paper = df_results[['ExpID',  'FP (False Proof)', 'FN (Missed Proof)',
       'Errors', 'accuracy', 'content_effect', 'combined_score', 'intra_bias',
       'inter_bias', 'acc_plausible_valid', 'acc_implausible_valid',
       'acc_plausible_invalid', 'acc_implausible_invalid',  'Model',
       'Prompt', 'Prompt_Length', 'input_key', 'Examples', '#Examples',
       'Example_Lengths','Experiment']]

In [ ]:
all_paper

In [57]:
a = [2,4,7,4]
sum(a)/len(a)

4.25

In [113]:
import numpy as np
# data for paper
paper_df = df_results[['ExpID',  'FP (False Proof)', 'FN (Missed Proof)',
       'Errors', 'accuracy', 'content_effect', 'combined_score', 'intra_bias',
       'inter_bias', 'acc_plausible_valid', 'acc_implausible_valid',
       'acc_plausible_invalid', 'acc_implausible_invalid',  'Model',
       'Prompt', 'Prompt_Length', 'input_key', 'Examples', '#Examples',
       'Example_Lengths','Experiment']]

# if experiment == "fol_output_from_syllogism" then ExpID = "Rule-TBI-FOL"
# if experiment == "from_syllogism_aristotelian_truth" then ExpID = "Rule-TBI-Syl"
# if experiment == "fol_output_from_syllogism_simplified_Simp1" then ExpID = "Simp1-Rule-TBI-FOL"
# if experiment == "fol_output_from_syllogism_simplified_Simp2" then ExpID = "Simp2-Rule-TBI-FOL"
# if experiment == "from_syllogism_simplified_Simp1" then ExpID = "Simp1-Rule-TBI-Syl"
# if experiment == "from_syllogism_simplified_Simp2" then ExpID = "Simp2-Rule-TBI-Syl"
# if experiment == "dni_validity" then ExpID = "DNI"

paper_df["ExpID"] = paper_df.apply(lambda row: "Rule-TBI-FOL" if row["Experiment"] == "fol_output_from_syllogism" 
                                   else ("Rule-TBI-Syl" if row["Experiment"] == "from_syllogism_aristotelian_truth" 
                                    else ("Simp1-Rule-TBI-FOL" if row["Experiment"] == "fol_output_from_syllogism_simplified_Simp1" 
                                     else ("Simp2-Rule-TBI-FOL" if row["Experiment"] == "fol_output_from_syllogism_simplified_Simp2"
                                      else ("Simp1-Rule-TBI-Syl" if row["Experiment"] == "from_syllogism_simplified_Simp1_aristotelian_truth" 
                                       else ("Simp2-Rule-TBI-Syl" if row["Experiment"] == "from_syllogism_simplified_Simp2_aristotelian_truth"
                                        else ("DNI" if row["Experiment"] == "dni_validity" else row["ExpID"])))))), axis=1)





# 'av. example length' column with average length of examples
paper_df["av_example_length"] = paper_df["Example_Lengths"].apply(
    lambda x: sum(x[0])/len(x[0]) if isinstance(x, list) and len(x) > 0 and len(x[0]) > 0 else np.nan
)
# drop "Experiments" and "Example_Lengths" column
paper_df = paper_df.drop(columns=["Experiment", "Example_Lengths"])

for col in ["#Examples", "Prompt_Length"]:
    # Erst zu numerisch, dann zu Int64 (um .0 zu vermeiden), dann zu String für den Export
    temp = pd.to_numeric(paper_df[col], errors='coerce').astype("Int64")
    paper_df[col] = temp.astype(str).replace("<NA>", "--").replace("0", "--")


# all 'Unknown' in Dataframe should be replaced with NaN
paper_df = paper_df.replace("Unknown", np.nan)



# if input_key is "syllogism_simplified_Simp1" then replace with "simplified_Simp1" and if "syllogism_simplified_Simp2" then replace with "simplified_Simp2" else keep the same
paper_df["input_key"] = paper_df["input_key"].apply(lambda x: "Simp1" if x == "syllogism_simplified_Simp1" else ("Simp2" if x == "syllogism_simplified_Simp2" else "syll" if x == "syllogism" else x))    



paper_df

C:\Users\Wiebke Petersen\AppData\Local\Temp\ipykernel_49064\3141179461.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  paper_df["ExpID"] = paper_df.apply(lambda row: "Rule-TBI-FOL" if row["Experiment"] == "fol_output_from_syllogism"

,ExpID,FP (False Proof),FN (Missed Proof),Errors,accuracy,content_effect,combined_score,intra_bias,inter_bias,acc_plausible_valid,acc_implausible_valid,acc_plausible_invalid,acc_implausible_invalid,Model,Prompt,Prompt_Length,input_key,Examples,#Examples,av_example_length
0,Eng2FOL,5,11,2,91.6230,4.1667,34.6764,2.1498,6.1835,89.5833,87.5000,93.6170,95.8333,SmolLM3-3B,Eng2FOL,1721,syll,Eng2FOLex,3,3.000
1,Eng2FOL10Qwen4B,3,5,0,95.8115,4.1667,36.2616,6.3165,2.0168,91.6667,97.9167,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLimproved,1634,syll,Eng2FOLexVaried,8,3.000
2,Eng2FOL10,4,20,2,87.4346,12.5000,24.2692,8.3998,16.6002,72.9167,85.4167,93.6170,97.9167,SmolLM3-3B,Eng2FOLimproved,1634,syll,Eng2FOLexVaried,8,3.000
3,Eng2FOL11,0,69,100,63.8743,37.5000,13.7345,3.1250,71.8750,25.0000,31.2500,100.0000,100.0000,gemma-3-4b-it,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
4,Eng2FOL2,14,31,5,76.4398,9.3750,22.8903,1.1968,17.5532,68.7500,66.6667,85.1064,85.4167,Llama-3.2-3B-Instruct,Eng2FOLimproved,1634,syll,Eng2FOLexImproved,5,3.200
5,Eng2FOL3,9,19,2,85.3403,10.3502,24.8861,10.3502,10.3502,72.9167,87.5000,93.6170,87.5000,Llama-3.2-3B-Instruct,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
6,Eng2FOL4,5,11,1,91.6230,6.2500,30.7357,6.3387,6.1613,85.4167,91.6667,91.4894,97.9167,SmolLM3-3B,Eng2FOLimproved,1634,syll,Eng2FOLexImproved,5,3.200
7,Eng2FOL5Gemma2B,14,33,6,75.3927,16.6667,19.4729,13.7855,19.5479,60.4167,70.8333,76.5957,93.7500,gemma-2-2b-it,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
8,Eng2FOL5Qwen0.6B,17,43,19,68.5864,17.5754,17.4883,8.2004,26.9504,52.0833,58.3333,87.2340,77.0833,Qwen3-0.6B,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
9,Eng2FOL5Qwen1.7B,3,4,1,96.3351,3.1915,39.5943,3.1915,3.1915,95.8333,95.8333,93.6170,100.0000,Qwen3-1.7B,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
10,Eng2FOL5Qwen4B,3,3,1,96.8586,3.1915,39.8095,6.3165,0.0665,93.7500,100.0000,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
11,Eng2FOL5,4,5,0,95.2880,2.1498,44.3748,3.1915,1.1082,93.7500,95.8333,93.6170,97.9167,SmolLM3-3B,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
12,Eng2FOL5small,23,41,10,66.4921,14.5833,17.7492,10.7270,18.4397,62.5000,52.0833,70.2128,81.2500,SmolLM2-1.7B-Instruct,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
13,Eng2FOL5tiny,62,29,10,52.3560,23.9583,12.4149,12.9876,34.9291,70.8333,68.7500,46.8085,22.9167,SmolLM2-135M-Instruct,Eng2FOLUltrashort,320,syll,Eng2FOLexImprovedX,8,3.125
14,Eng2FOL6,5,5,1,94.7644,3.2137,38.8645,6.3387,0.0887,91.6667,97.9167,91.4894,97.9167,SmolLM3-3B,Eng2FOLUltrashort,320,syll,Eng2FOLexImproved,5,3.200
15,Eng2FOL7,4,2,2,96.8586,3.1915,39.8095,4.2332,2.1498,95.8333,100.0000,93.6170,97.9167,SmolLM3-3B,Eng2FOL,1721,syll,Eng2FOLexImprovedX,8,3.125
16,Eng2FOL8,5,12,1,91.0995,5.2083,32.2374,3.2137,7.2030,87.5000,87.5000,91.4894,97.9167,SmolLM3-3B,Eng2FOLUltrashort,320,syll,Eng2FOLexImproved2,8,3.625
17,Eng2FOL9Qwen4B,3,8,12,94.2408,7.2917,30.2514,9.4415,5.1418,85.4167,97.9167,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syll,Eng2FOLexVaried,8,3.000
18,Eng2FOL9,5,21,3,86.3874,12.5000,23.9786,8.3998,16.6002,70.8333,85.4167,93.6170,95.8333,SmolLM3-3B,Eng2FOLUltrashort,320,syll,Eng2FOLexVaried,8,3.000
19,QwenEng2FOL1,3,7,3,94.7644,4.1667,35.8653,4.2332,4.1002,91.6667,93.7500,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syll,Eng2FOLexImproved2,8,3.625
20,QwenEng2FOL2,3,6,5,95.2880,4.1667,36.0635,5.2748,3.0585,91.6667,95.8333,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syll,Eng2FOLexImproved,5,3.200
21,QwenEng2FOL3,5,7,12,93.7173,2.0833,44.0813,2.1498,2.0168,91.6667,93.7500,93.6170,95.8333,Qwen3-4B-Instruct-2507,Eng2FOLUltrashort,320,syll,Eng2FOLex,3,3.000
22,QwenEng2FOL4,3,2,1,97.3822,3.1915,40.0246,5.2748,1.1082,95.8333,100.0000,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLimproved,1634,syll,Eng2FOLexImproved,5,3.200
23,QwenEng2FOL5,3,5,1,95.8115,4.1667,36.2616,6.3165,2.0168,91.6667,97.9167,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOL,1721,syll,Eng2FOLexImproved,5,3.200
24,QwenEng2FOL6,3,5,0,95.8115,5.2083,33.9049,8.3998,2.0168,89.5833,100.0000,93.6170,100.0000,Qwen3-4B-Instruct-2507,Eng2FOLimproved,1634,syll,Eng2FOLexImprovedX,8,3.125
25,SimpEng2FOL1,5,22,2,85.8639,12.5000,23.8333,7.3582,17.6418,70.8333,83.3333,93.6170,95.8333,SmolLM3-3B,Eng2FOL,1721,Simp1,Eng2FOLex,3,3.000
26,SimpEng2FOL2,6,25,1,83.7696,14.5833,22.3612,9.4858,19.6809,68.7500,79.1667,89.3617,97.9167,SmolLM3-3B,Eng2FOL,1721,Simp2,Eng2FOLex,3,3.000
27,Rule-TBI-FOL,0,96,121,49.7382,50.0000,10.0852,0.0000,100.0000,0.0000,0.0000,100.0000,100.0000,NaN,NaN,--,NaN,NaN,--,NaN
28,Simp1-Rule-TBI-FOL,2,24,3,86.3874,14.5833,23.0600,6.2943,22.8723,70.8333,79.1667,95.7447,100.0000,SmolLM3-3B,LogSimp,1572,syll,LogSimpEx,5,3.400
29,Simp2-Rule-TBI-FOL,6,24,3,84.2932,13.5417,22.9243,8.4441,18.6392,70.8333,79.1667,89.3617,97.9167,SmolLM3-3B,LogSimpShortPrompt,1016,syll,LogSimpEx,5,3.400
30,Eng2SyllogismProlog,13,40,0,72.2513,18.6613,18.1597,9.2863,28.0363,54.1667,62.5000,91.4894,81.2500,SmolLM3-3B,SyllTrip,1254,syll,SyllTripEx,4,3.750
31,SimpEng2SyllogismProlog,9,35,0,76.9634,14.4947,20.5757,1.9947,26.9947,64.5833,62.5000,91.4894,89.5833,SmolLM3-3B,SyllTrip,1254,Simp1,SimpSyllTripEx,4,3.750
32,Rule-TBI-Syl,0,96,126,49.7382,50.0000,10.0852,0.0000,100.0000,0.0000,0.0000,100.0000,100.0000,NaN,NaN,--,NaN,NaN,--,NaN
33,Simp1-Rule-TBI-Syl,0,28,0,85.3403,18.7500,21.4253,8.3333,29.1667,62.5000,79.1667,100.0000,100.0000,SmolLM3-3B,LogSimp,1572,syll,LogSimpEx,5,3.400
34,Simp2-Rule-TBI-Syl,4,29,0,82.7225,19.7917,20.5035,13.6082,25.9752,58.3333,81.2500,93.6170,97.9167,SmolLM3-3B,LogSimpShortPrompt,1016,syll,LogSimpEx,5,3.400
35,DNI,45,38,25,56.5445,24.5124,13.3386,24.5124,24.5124,79.1667,41.6667,46.8085,58.3333,NaN,NaN,--,NaN,NaN,--,NaN

In [ ]:
# 1. Kürzen der Modellnamen (entfernt 'google/', 'meta-llama/', etc.)
paper_df["Model"] = paper_df["Model"].str.split('/').str[-1]

# 2. Mapping definieren
column_mapping = {
    "ExpID": "ExpID",
    "FP (False Proof)": "FP",
    "FN (Missed Proof)": "FN",
    "accuracy": "Acc",
    "content_effect": "TCE",
    "combined_score": "Score",
    "intra_bias": "Intra",
    "inter_bias": "Inter",
    "acc_plausible_valid": "$Acc_{PV}$",
    "acc_implausible_valid": "$Acc_{IV}$",
    "acc_plausible_invalid": "$Acc_{PI}$",
    "acc_implausible_invalid": "$Acc_{II}$",
    "input_key": "Input",
    "Prompt_Length": "PromptLen",
    "Examples": "ExID",
    "#Examples": "\#Ex",
    "av_example_length": "$ \varnothing $ ExLen"
}
# 3. Mapping anwenden
paper_df = paper_df.rename(columns=column_mapping)
paper_df.drop(columns=["Intra","Inter"], inplace=True)


# in "Model" remove suffix -2507 und -Instruct
paper_df["Model"] = paper_df["Model"].str.replace("-2507", "", regex=False).str.replace("-Instruct", "", regex=False)

In [115]:
paper_df = paper_df.sort_values(by="Score", ascending=False, na_position='last')

latex_output = paper_df.to_latex(
    index=False,                # Meistens braucht man den Index in der Publikation nicht
    float_format="%.2f",        # Alle Floats auf 2 Nachkommastellen runden
    na_rep="--",                # Alle NaNs durch -- ersetzen
    column_format="l" + "c" * (len(paper_df.columns) - 1), # Erste Spalte links, Rest zentriert
    escape=False,               # Wichtig, falls du LaTeX-Commands wie \textbf in den Zellen hast
    caption="Detailed Performance Metrics per Model and Configuration.",
    label="tab:detailed_results_appendix"
)

print(latex_output)

\begin{table}
\centering
\caption{Detailed Performance Metrics per Model and Configuration.}
\label{tab:detailed_results_appendix}
\begin{tabular}{lccccccccccccccccc}
\toprule
                  ExpID &  FP &  FN &  Errors &   Acc &   TCE &  Score &  $Acc_{PV}$ &  $Acc_{IV}$ &  $Acc_{PI}$ &  $Acc_{II}$ &         Model &             Prompt & PromptLen & Input &               ExID & \#Ex &  $arnothing$ ExLen \\
\midrule
               Eng2FOL5 &   4 &   5 &       0 & 95.29 &  2.15 &  44.37 &       93.75 &       95.83 &       93.62 &       97.92 &    SmolLM3-3B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
           QwenEng2FOL3 &   5 &   7 &      12 & 93.72 &  2.08 &  44.08 &       91.67 &       93.75 &       93.62 &       95.83 &      Qwen3-4B &  Eng2FOLUltrashort &       320 &  syll &          Eng2FOLex &    3 &                3.00 \\
           QwenEng2FOL4 &   3 &   2 &       1 & 97.38 &  3.19 &  40.02 &       95.83 &      100.00 &       93.62 &      100.00 &      Qwen3-4B &    Eng2FOLimproved &      1634 &  syll &  Eng2FOLexImproved &    5 &                3.20 \\
               Eng2FOL7 &   4 &   2 &       2 & 96.86 &  3.19 &  39.81 &       95.83 &      100.00 &       93.62 &       97.92 &    SmolLM3-3B &            Eng2FOL &      1721 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
         Eng2FOL5Qwen4B &   3 &   3 &       1 & 96.86 &  3.19 &  39.81 &       93.75 &      100.00 &       93.62 &      100.00 &      Qwen3-4B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
       Eng2FOL5Qwen1.7B &   3 &   4 &       1 & 96.34 &  3.19 &  39.59 &       95.83 &       95.83 &       93.62 &      100.00 &    Qwen3-1.7B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
               Eng2FOL6 &   5 &   5 &       1 & 94.76 &  3.21 &  38.86 &       91.67 &       97.92 &       91.49 &       97.92 &    SmolLM3-3B &  Eng2FOLUltrashort &       320 &  syll &  Eng2FOLexImproved &    5 &                3.20 \\
           QwenEng2FOL5 &   3 &   5 &       1 & 95.81 &  4.17 &  36.26 &       91.67 &       97.92 &       93.62 &      100.00 &      Qwen3-4B &            Eng2FOL &      1721 &  syll &  Eng2FOLexImproved &    5 &                3.20 \\
        Eng2FOL10Qwen4B &   3 &   5 &       0 & 95.81 &  4.17 &  36.26 &       91.67 &       97.92 &       93.62 &      100.00 &      Qwen3-4B &    Eng2FOLimproved &      1634 &  syll &    Eng2FOLexVaried &    8 &                3.00 \\
           QwenEng2FOL2 &   3 &   6 &       5 & 95.29 &  4.17 &  36.06 &       91.67 &       95.83 &       93.62 &      100.00 &      Qwen3-4B &  Eng2FOLUltrashort &       320 &  syll &  Eng2FOLexImproved &    5 &                3.20 \\
           QwenEng2FOL1 &   3 &   7 &       3 & 94.76 &  4.17 &  35.87 &       91.67 &       93.75 &       93.62 &      100.00 &      Qwen3-4B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImproved2 &    8 &                3.62 \\
                Eng2FOL &   5 &  11 &       2 & 91.62 &  4.17 &  34.68 &       89.58 &       87.50 &       93.62 &       95.83 &    SmolLM3-3B &            Eng2FOL &      1721 &  syll &          Eng2FOLex &    3 &                3.00 \\
           QwenEng2FOL6 &   3 &   5 &       0 & 95.81 &  5.21 &  33.90 &       89.58 &      100.00 &       93.62 &      100.00 &      Qwen3-4B &    Eng2FOLimproved &      1634 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
               Eng2FOL8 &   5 &  12 &       1 & 91.10 &  5.21 &  32.24 &       87.50 &       87.50 &       91.49 &       97.92 &    SmolLM3-3B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImproved2 &    8 &                3.62 \\
               Eng2FOL4 &   5 &  11 &       1 & 91.62 &  6.25 &  30.74 &       85.42 &       91.67 &       91.49 &       97.92 &    SmolLM3-3B &    Eng2FOLimproved &      1634 &  syll &  Eng2FOLexImproved &    5 &                3.20 \\
         Eng2FOL9Qwen4B &   3 &   8 &      12 & 94.24 &  7.29 &  30.25 &       85.42 &       97.92 &       93.62 &      100.00 &      Qwen3-4B &  Eng2FOLUltrashort &       320 &  syll &    Eng2FOLexVaried &    8 &                3.00 \\
               Eng2FOL3 &   9 &  19 &       2 & 85.34 & 10.35 &  24.89 &       72.92 &       87.50 &       93.62 &       87.50 &  Llama-3.2-3B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
              Eng2FOL10 &   4 &  20 &       2 & 87.43 & 12.50 &  24.27 &       72.92 &       85.42 &       93.62 &       97.92 &    SmolLM3-3B &    Eng2FOLimproved &      1634 &  syll &    Eng2FOLexVaried &    8 &                3.00 \\
               Eng2FOL9 &   5 &  21 &       3 & 86.39 & 12.50 &  23.98 &       70.83 &       85.42 &       93.62 &       95.83 &    SmolLM3-3B &  Eng2FOLUltrashort &       320 &  syll &    Eng2FOLexVaried &    8 &                3.00 \\
           SimpEng2FOL1 &   5 &  22 &       2 & 85.86 & 12.50 &  23.83 &       70.83 &       83.33 &       93.62 &       95.83 &    SmolLM3-3B &            Eng2FOL &      1721 & Simp1 &          Eng2FOLex &    3 &                3.00 \\
     Simp1-Rule-TBI-FOL &   2 &  24 &       3 & 86.39 & 14.58 &  23.06 &       70.83 &       79.17 &       95.74 &      100.00 &    SmolLM3-3B &            LogSimp &      1572 &  syll &          LogSimpEx &    5 &                3.40 \\
     Simp2-Rule-TBI-FOL &   6 &  24 &       3 & 84.29 & 13.54 &  22.92 &       70.83 &       79.17 &       89.36 &       97.92 &    SmolLM3-3B & LogSimpShortPrompt &      1016 &  syll &          LogSimpEx &    5 &                3.40 \\
               Eng2FOL2 &  14 &  31 &       5 & 76.44 &  9.38 &  22.89 &       68.75 &       66.67 &       85.11 &       85.42 &  Llama-3.2-3B &    Eng2FOLimproved &      1634 &  syll &  Eng2FOLexImproved &    5 &                3.20 \\
           SimpEng2FOL2 &   6 &  25 &       1 & 83.77 & 14.58 &  22.36 &       68.75 &       79.17 &       89.36 &       97.92 &    SmolLM3-3B &            Eng2FOL &      1721 & Simp2 &          Eng2FOLex &    3 &                3.00 \\
     Simp1-Rule-TBI-Syl &   0 &  28 &       0 & 85.34 & 18.75 &  21.43 &       62.50 &       79.17 &      100.00 &      100.00 &    SmolLM3-3B &            LogSimp &      1572 &  syll &          LogSimpEx &    5 &                3.40 \\
SimpEng2SyllogismProlog &   9 &  35 &       0 & 76.96 & 14.49 &  20.58 &       64.58 &       62.50 &       91.49 &       89.58 &    SmolLM3-3B &           SyllTrip &      1254 & Simp1 &     SimpSyllTripEx &    4 &                3.75 \\
     Simp2-Rule-TBI-Syl &   4 &  29 &       0 & 82.72 & 19.79 &  20.50 &       58.33 &       81.25 &       93.62 &       97.92 &    SmolLM3-3B & LogSimpShortPrompt &      1016 &  syll &          LogSimpEx &    5 &                3.40 \\
        Eng2FOL5Gemma2B &  14 &  33 &       6 & 75.39 & 16.67 &  19.47 &       60.42 &       70.83 &       76.60 &       93.75 & gemma-2-2b-it &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
    Eng2SyllogismProlog &  13 &  40 &       0 & 72.25 & 18.66 &  18.16 &       54.17 &       62.50 &       91.49 &       81.25 &    SmolLM3-3B &           SyllTrip &      1254 &  syll &         SyllTripEx &    4 &                3.75 \\
          Eng2FOL5small &  23 &  41 &      10 & 66.49 & 14.58 &  17.75 &       62.50 &       52.08 &       70.21 &       81.25 &  SmolLM2-1.7B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
       Eng2FOL5Qwen0.6B &  17 &  43 &      19 & 68.59 & 17.58 &  17.49 &       52.08 &       58.33 &       87.23 &       77.08 &    Qwen3-0.6B &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
              Eng2FOL11 &   0 &  69 &     100 & 63.87 & 37.50 &  13.73 &       25.00 &       31.25 &      100.00 &      100.00 & gemma-3-4b-it &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
                    DNI &  45 &  38 &      25 & 56.54 & 24.51 &  13.34 &       79.17 &       41.67 &       46.81 &       58.33 &            -- &                 -- &        -- &    -- &                 -- &   -- &                  -- \\
           Eng2FOL5tiny &  62 &  29 &      10 & 52.36 & 23.96 &  12.41 &       70.83 &       68.75 &       46.81 &       22.92 &  SmolLM2-135M &  Eng2FOLUltrashort &       320 &  syll & Eng2FOLexImprovedX &    8 &                3.12 \\
           Rule-TBI-Syl &   0 &  96 &     126 & 49.74 & 50.00 &  10.09 &        0.00 &        0.00 &      100.00 &      100.00 &            -- &                 -- &        -- &    -- &                 -- &   -- &                  -- \\
           Rule-TBI-FOL &   0 &  96 &     121 & 49.74 & 50.00 &  10.09 &        0.00 &        0.00 &      100.00 &      100.00 &            -- &                 -- &        -- &    -- &                 -- &   -- &                  -- \\
\bottomrule
\end{tabular}
\end{table}

C:\Users\Wiebke Petersen\AppData\Local\Temp\ipykernel_49064\2624006766.py:3: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex_output = paper_df.to_latex(

In [42]:
# save paper_df as csv
paper_df.to_csv(data_type + "_paper_results.csv", index=False, sep=';')

In [43]:
# only rows with ExpID in ["Rule-TBI-FOL", "Rule-TBI-Syl", "Simp1-Rule-TBI-FOL", "Simp2-Rule-TBI-FOL", "Simp1-Rule-TBI-Syl", "Simp2-Rule-TBI-Syl", "DNI", "Eng2SyllogismProlog", SimpEng2SyllogismProlog, SimpEng2FOL1, Eng2FOL5, Eng2FOL]

paper_df_sel = paper_df[paper_df["ExpID"].isin(["Rule-TBI-FOL", "Rule-TBI-Syl", "Simp1-Rule-TBI-FOL",  "Simp1-Rule-TBI-Syl", "DNI", "Eng2SyllogismProlog", "SimpEng2SyllogismProlog", "SimpEng2FOL1", "Eng2FOL5", "Eng2FOL"])]
drop_columns = ['Experiment', 'Model', 'Prompt', 'Prompt_Length', 'input_key', 'Examples', '#Examples']
paper_df_sel = paper_df_sel.drop(columns=drop_columns)
# ExpID as index
paper_df_sel = paper_df_sel.set_index("ExpID")

round_columns = ["accuracy", 'content_effect', 'combined_score',  'acc_plausible_valid', 'acc_implausible_valid',
       'acc_plausible_invalid', 'acc_implausible_invalid']
for col in round_columns:
    paper_df_sel[col] = paper_df_sel[col].round(2)
new_order = ['DNI', 'Rule-TBI-FOL', 'Rule-TBI-Syl', 'Eng2FOL', 'Eng2FOL5', 'SimpEng2FOL1', 'Eng2SyllogismProlog',
       'Simp1-Rule-TBI-FOL',  
       'Simp1-Rule-TBI-Syl', ]
paper_df_sel = paper_df_sel.reindex(new_order)
paper_df_sel

,FP (False Proof),FN (Missed Proof),Errors,accuracy,content_effect,combined_score,acc_plausible_valid,acc_implausible_valid,acc_plausible_invalid,acc_implausible_invalid
ExpID,,,,,,,,,,
DNI,45,38,25,56.54,24.51,13.34,79.17,41.67,46.81,58.33
Rule-TBI-FOL,0,96,121,49.74,50.00,10.09,0.00,0.00,100.00,100.00
Rule-TBI-Syl,0,96,126,49.74,50.00,10.09,0.00,0.00,100.00,100.00
Eng2FOL,5,11,2,91.62,4.17,34.68,89.58,87.50,93.62,95.83
Eng2FOL5,4,5,0,95.29,2.15,44.37,93.75,95.83,93.62,97.92
SimpEng2FOL1,5,22,2,85.86,12.50,23.83,70.83,83.33,93.62,95.83
Eng2SyllogismProlog,13,40,0,72.25,18.66,18.16,54.17,62.50,91.49,81.25
Simp1-Rule-TBI-FOL,2,24,3,86.39,14.58,23.06,70.83,79.17,95.74,100.00
Simp1-Rule-TBI-Syl,0,28,0,85.34,18.75,21.43,62.50,79.17,100.00,100.00

In [44]:
paper_df_sel[["accuracy", 'content_effect', 'combined_score']].to_latex("paper_df_sel.tex", index=True)

C:\Users\Wiebke Petersen\AppData\Local\Temp\ipykernel_49064\1397007784.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  paper_df_sel[["accuracy", 'content_effect', 'combined_score']].to_latex("paper_df_sel.tex", index=True)

In [45]:
# csv save with semicolon as separator
paper_df_sel.to_csv(data_type + "_paper_results_selected.csv", sep=';')

#### Analyse der Ergebnisse

Welche Modelle sind besonders geeignet?

In [727]:
print("--- VERGLEICH: Einfluss der MODELLE ---")
for (p_val, e_val), group in df_results.groupby(["Prompt", "Examples"]):
    # Prüfe, ob mehr als ein einzigartiges Modell in dieser Konf enthalten ist
    if group["Model"].nunique() > 1:  
        print(f"\nKonfiguration: Prompt='{p_val}' length: {group['Prompt_Length'].iloc[0]},  Examples='{e_val}' number: {group['#Examples'].iloc[0]}")
        display(group[['Experiment', 'Model', 'accuracy', 'combined_score','content_effect']].sort_values(by='combined_score', ascending=False))

--- VERGLEICH: Einfluss der MODELLE ---

Konfiguration: Prompt='Eng2FOLUltrashort' length: 320,  Examples='Eng2FOLexImproved' number: 5

,Experiment,Model,accuracy,combined_score,content_effect
14,fol_otter_output_Eng2FOL6,SmolLM3-3B,94.7644,38.8645,3.2137
20,fol_otter_output_QwenEng2FOL2,Qwen3-4B-Instruct-2507,95.2880,36.0635,4.1667

Konfiguration: Prompt='Eng2FOLUltrashort' length: 320,  Examples='Eng2FOLexImproved2' number: 8

,Experiment,Model,accuracy,combined_score,content_effect
19,fol_otter_output_QwenEng2FOL1,Qwen3-4B-Instruct-2507,94.7644,35.8653,4.1667
16,fol_otter_output_Eng2FOL8,SmolLM3-3B,91.0995,32.2374,5.2083

Konfiguration: Prompt='Eng2FOLUltrashort' length: 320,  Examples='Eng2FOLexImprovedX' number: 8

,Experiment,Model,accuracy,combined_score,content_effect
11,fol_otter_output_Eng2FOL5,SmolLM3-3B,95.2880,44.3748,2.1498
10,fol_otter_output_Eng2FOL5Qwen4B,Qwen3-4B-Instruct-2507,96.8586,39.8095,3.1915
9,fol_otter_output_Eng2FOL5Qwen1.7B,Qwen3-1.7B,96.3351,39.5943,3.1915
5,fol_otter_output_Eng2FOL3,Llama-3.2-3B-Instruct,85.3403,24.8861,10.3502
7,fol_otter_output_Eng2FOL5Gemma2B,gemma-2-2b-it,75.3927,19.4729,16.6667
12,fol_otter_output_Eng2FOL5small,SmolLM2-1.7B-Instruct,66.4921,17.7492,14.5833
8,fol_otter_output_Eng2FOL5Qwen0.6B,Qwen3-0.6B,68.5864,17.4883,17.5754
3,fol_otter_output_Eng2FOL11,gemma-3-4b-it,63.8743,13.7345,37.5000
13,fol_otter_output_Eng2FOL5tiny,SmolLM2-135M-Instruct,52.3560,12.4149,23.9583

Konfiguration: Prompt='Eng2FOLUltrashort' length: 320,  Examples='Eng2FOLexVaried' number: 8

,Experiment,Model,accuracy,combined_score,content_effect
17,fol_otter_output_Eng2FOL9Qwen4B,Qwen3-4B-Instruct-2507,94.2408,30.2514,7.2917
18,fol_otter_output_Eng2FOL9,SmolLM3-3B,86.3874,23.9786,12.5000

Konfiguration: Prompt='Eng2FOLimproved' length: 1634,  Examples='Eng2FOLexImproved' number: 5

,Experiment,Model,accuracy,combined_score,content_effect
22,fol_otter_output_QwenEng2FOL4,Qwen3-4B-Instruct-2507,97.3822,40.0246,3.1915
6,fol_otter_output_Eng2FOL4,SmolLM3-3B,91.6230,30.7357,6.2500
4,fol_otter_output_Eng2FOL2,Llama-3.2-3B-Instruct,76.4398,22.8903,9.3750

Konfiguration: Prompt='Eng2FOLimproved' length: 1634,  Examples='Eng2FOLexVaried' number: 8

,Experiment,Model,accuracy,combined_score,content_effect
1,fol_otter_output_Eng2FOL10Qwen4B,Qwen3-4B-Instruct-2507,95.8115,36.2616,4.1667
2,fol_otter_output_Eng2FOL10,SmolLM3-3B,87.4346,24.2692,12.5000

 *  innerhalb einer Modellfamilie: je größer je besser
 *  Llama- Modelle sind am schlechtesten
 *  Qwen-Modelle sind am besten
 *  Gemma 2B wird geschlagen durch Qwen 1.7B 
 = > Qwen3-4B-Instruct-2507 Siegermodell
 * **ABER** smolLM kommt besser mit kurzem Prompt und wenigen Beispielen zurecht.

In [ ]:
print("#########################################")
print("--- VERGLEICH: Einfluss der PROMPTS ---")
for (m_val, e_val), group in df_results.groupby(["Model", "Examples"]):
    if group["Prompt"].nunique() > 1:  # Nur Gruppen mit mehr als einem Prompt zeigen
        print(f"\nKonfiguration: Model='{m_val}', Examples='{e_val}' number: {group['#Examples'].iloc[0]}")
        display(group[['Experiment', 'Prompt', 'Prompt_Length' ,'accuracy', 'combined_score','content_effect']].sort_values(by='combined_score', ascending=False))

#########################################
--- VERGLEICH: Einfluss der PROMPTS ---

Konfiguration: Model='Qwen3-4B-Instruct-2507', Examples='Eng2FOLexImproved' number: 5

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
22,fol_otter_output_QwenEng2FOL4,Eng2FOLimproved,1634,96.8586,36.4234,4.2553
23,fol_otter_output_QwenEng2FOL5,Eng2FOL,1721,95.8115,36.2616,4.1667
20,fol_otter_output_QwenEng2FOL2,Eng2FOLUltrashort,320,93.1937,29.7384,7.4468

Konfiguration: Model='Qwen3-4B-Instruct-2507', Examples='Eng2FOLexImprovedX' number: 8

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
10,fol_otter_output_Eng2FOL5Qwen4B,Eng2FOLUltrashort,320,96.3351,36.2265,4.2553
24,fol_otter_output_QwenEng2FOL6,Eng2FOLimproved,1634,95.8115,33.9049,5.2083

Konfiguration: Model='Qwen3-4B-Instruct-2507', Examples='Eng2FOLexVaried' number: 8

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
1,fol_otter_output_Eng2FOL10Qwen4B,Eng2FOLimproved,1634,95.8115,36.2616,4.1667
17,fol_otter_output_Eng2FOL9Qwen4B,Eng2FOLUltrashort,320,88.4817,28.2111,7.4690

Konfiguration: Model='SmolLM3-3B', Examples='Eng2FOLexImproved' number: 5

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
14,fol_otter_output_Eng2FOL6,Eng2FOLUltrashort,320,94.2408,35.3830,4.2775
6,fol_otter_output_Eng2FOL4,Eng2FOLimproved,1634,91.6230,30.7357,6.2500

Konfiguration: Model='SmolLM3-3B', Examples='Eng2FOLexImprovedX' number: 8

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
11,fol_otter_output_Eng2FOL5,Eng2FOLUltrashort,320,95.2880,44.3748,2.1498
15,fol_otter_output_Eng2FOL7,Eng2FOL,1721,96.3351,36.2265,4.2553

Konfiguration: Model='SmolLM3-3B', Examples='Eng2FOLexVaried' number: 8

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
2,fol_otter_output_Eng2FOL10,Eng2FOLimproved,1634,86.9110,24.1239,12.5
18,fol_otter_output_Eng2FOL9,Eng2FOLUltrashort,320,86.3874,23.9786,12.5

Konfiguration: Model='SmolLM3-3B', Examples='LogSimpEx' number: 5

,Experiment,Prompt,Prompt_Length,accuracy,combined_score,content_effect
28,fol_output_from_syllogism_simplified_Simp1,LogSimp,1572,85.8639,22.9202,14.5833
29,fol_output_from_syllogism_simplified_Simp2,LogSimpShortPrompt,1016,83.7696,22.7819,13.5417
32,from_syllogism_simplified_Simp1_aristotelian_t...,LogSimp,1572,85.3403,21.4253,18.7500
33,from_syllogism_simplified_Simp2_aristotelian_t...,LogSimpShortPrompt,1016,82.7225,20.5035,19.7917

In [ ]:



print("#########################################")
print("--- VERGLEICH: Einfluss der BEISPIELE ---")
for (m_val, p_val), group in df_results.groupby(["Model", "Prompt"]):
    if group["Examples"].nunique() > 1:  # Nur Gruppen mit mehr als einem Prompt zeigen
        print(f"\nKonfiguration: Model='{m_val}', Prompt='{p_val}' length: {group['Prompt_Length'].iloc[0]}'")
        display(group[['Experiment', 'Examples', '#Examples', 'accuracy', 'combined_score','content_effect']].sort_values(by='combined_score', ascending=False))

#########################################
--- VERGLEICH: Einfluss der BEISPIELE ---

Konfiguration: Model='Qwen3-4B-Instruct-2507', Prompt='Eng2FOLUltrashort' length: 320'

,Experiment,Examples,#Examples,accuracy,combined_score,content_effect
19,fol_otter_output_QwenEng2FOL1,Eng2FOLexImproved2,8,93.7173,38.4350,3.2137
10,fol_otter_output_Eng2FOL5Qwen4B,Eng2FOLexImprovedX,8,96.3351,36.2265,4.2553
20,fol_otter_output_QwenEng2FOL2,Eng2FOLexImproved,5,93.1937,29.7384,7.4468
21,fol_otter_output_QwenEng2FOL3,Eng2FOLex,3,89.0052,28.3309,7.5133
17,fol_otter_output_Eng2FOL9Qwen4B,Eng2FOLexVaried,8,88.4817,28.2111,7.4690

Konfiguration: Model='Qwen3-4B-Instruct-2507', Prompt='Eng2FOLimproved' length: 1634'

,Experiment,Examples,#Examples,accuracy,combined_score,content_effect
22,fol_otter_output_QwenEng2FOL4,Eng2FOLexImproved,5,96.8586,36.4234,4.2553
1,fol_otter_output_Eng2FOL10Qwen4B,Eng2FOLexVaried,8,95.8115,36.2616,4.1667
24,fol_otter_output_QwenEng2FOL6,Eng2FOLexImprovedX,8,95.8115,33.9049,5.2083

Konfiguration: Model='SmolLM3-3B', Prompt='Eng2FOL' length: 1721'

,Experiment,Examples,#Examples,accuracy,combined_score,content_effect
15,fol_otter_output_Eng2FOL7,Eng2FOLexImprovedX,8,96.3351,36.2265,4.2553
0,fol_otter_output_Eng2FOL,Eng2FOLex,3,91.0995,34.4783,4.1667
25,fol_otter_output_SimpEng2FOL1,Eng2FOLex,3,85.8639,23.8333,12.5000
26,fol_otter_output_SimpEng2FOL2,Eng2FOLex,3,83.7696,22.3612,14.5833

Konfiguration: Model='SmolLM3-3B', Prompt='Eng2FOLUltrashort' length: 320'

,Experiment,Examples,#Examples,accuracy,combined_score,content_effect
11,fol_otter_output_Eng2FOL5,Eng2FOLexImprovedX,8,95.2880,44.3748,2.1498
14,fol_otter_output_Eng2FOL6,Eng2FOLexImproved,5,94.2408,35.3830,4.2775
16,fol_otter_output_Eng2FOL8,Eng2FOLexImproved2,8,91.0995,32.2374,5.2083
18,fol_otter_output_Eng2FOL9,Eng2FOLexVaried,8,86.3874,23.9786,12.5000

Konfiguration: Model='SmolLM3-3B', Prompt='Eng2FOLimproved' length: 1634'

,Experiment,Examples,#Examples,accuracy,combined_score,content_effect
6,fol_otter_output_Eng2FOL4,Eng2FOLexImproved,5,91.623,30.7357,6.25
2,fol_otter_output_Eng2FOL10,Eng2FOLexVaried,8,86.911,24.1239,12.50

In [ ]:

print("#########################################")
print("--- Vergleich: Einfluss der Experimente ---")
for (m_val, p_val, e_val), group in df_results.groupby(["Model", "Prompt", "Examples"]):
    if group["Experiment"].nunique() > 1:  # Nur Gruppen mit mehr als einem Experiment zeigen
        print(f"\nKonfiguration: Model='{m_val}', Prompt='{p_val}' length: {group['Prompt_Length'].iloc[0]}, Examples='{e_val}' number: {group['#Examples'].iloc[0]}")
        display(group[['Experiment', 'accuracy', 'combined_score','content_effect']].sort_values(by='combined_score', ascending=False))

#########################################
--- Vergleich: Einfluss der Experimente ---

Konfiguration: Model='SmolLM3-3B', Prompt='Eng2FOL' length: 1721, Examples='Eng2FOLex' number: 3

                       Experiment  accuracy  combined_score  content_effect
0        fol_otter_output_Eng2FOL   91.0995         34.4783          4.1667
25  fol_otter_output_SimpEng2FOL1   85.8639         23.8333         12.5000
26  fol_otter_output_SimpEng2FOL2   83.7696         22.3612         14.5833

Konfiguration: Model='SmolLM3-3B', Prompt='LogSimp' length: 1572, Examples='LogSimpEx' number: 5

,Experiment,accuracy,combined_score,content_effect
28,fol_output_from_syllogism_simplified_Simp1,85.8639,22.9202,14.5833
32,from_syllogism_simplified_Simp1_aristotelian_t...,85.3403,21.4253,18.7500

Konfiguration: Model='SmolLM3-3B', Prompt='LogSimpShortPrompt' length: 1016, Examples='LogSimpEx' number: 5

,Experiment,accuracy,combined_score,content_effect
29,fol_output_from_syllogism_simplified_Simp2,83.7696,22.7819,13.5417
33,from_syllogism_simplified_Simp2_aristotelian_t...,82.7225,20.5035,19.7917

Konfiguration: Model='Unknown', Prompt='Unknown' length: 0, Examples='Unknown' number: 0

,Experiment,accuracy,combined_score,content_effect
27,fol_output_from_syllogism,16.2304,4.1309,17.7083
31,from_syllogism_aristotelian_truth,15.1832,3.9842,15.6250

### Fehleranalyse

In [ ]:

def analyze_otter_failures(df, experiment_key, failure_type='fp'):
    """
    Analyzes specific failure types for a given experiment key.
    failure_type options: 'fp' (false positive), 'fn' (false negative), 'error' (technical errors)
    """
    ans_col = f'otter_answer_{experiment_key}'
    err_col = f'otter_error_{experiment_key}'
    input_col = f'otter_input_cleaned_{experiment_key}'

    # Define filters
    if failure_type == 'fp':
        # Otter said True, but Ground Truth is False
        filtered_df = df[(df[ans_col] == True) & (df['validity'] == False)]
        title = "False Positives (Otter proved an invalid syllogism)"
    elif failure_type == 'fn':
        # Otter said False, but Ground Truth is True
        filtered_df = df[(df[ans_col] == False) & (df['validity'] == True)]
        title = "False Negatives (Otter failed to prove a valid syllogism)"
    elif failure_type == 'error':
        # Technical errors or timeouts (None values)
        filtered_df = df[df[ans_col].isna()]
        title = "Technical Errors / Timeouts"
    else:
        print("Invalid failure_type. Use 'fp', 'fn', or 'error'.")
        return

    print(f"{title} | Experiment: {experiment_key}")
    print(f"Found {len(filtered_df)} cases\n")
    print("-" * 50 + "\n")

    for index, row in filtered_df.iterrows():
        print(f"Index: {index} | ID: {row.get('id', 'N/A')}")

        # Syllogism display
        print("Syllogism:")
        for s in str(row.get('syllogism', '')).split("."):
            if s.strip(): print(f"  - {s.strip()}")

        # Flexible access to simplified syllogism if it exists
        simp_col = f'syllogism_simplified_{experiment_key.split("_")[-1]}'
        if simp_col in df.columns:
            print(f"Simplified ({simp_col}):")
            for s in str(row.get(simp_col, '')).split(","):
                if s.strip(): print(f"    {s.strip()}")

        print(f"\nValidity: {row.get('validity')}")
        print(f"Otter Answer: {row.get(ans_col)} | Error: {row.get(err_col, 'None')}")

        print(f"\nCleaned Input (FOL):\n{row.get(input_col, 'N/A')}")

        # Optionally print the proof if it was an FP
        if failure_type == 'fp' and f'otter_proof_{experiment_key}' in df.columns:
            print(f"\nOtter Proof Snippet:\n{str(row.get(f'otter_proof_{experiment_key}', ''))[:300]}...")

        print("\n" + "="*50 + "\n")

In [ ]:
df_results = pd.read_parquet(file_name_generations)
exp = "fol_otter_output_Eng2FOL5"
print(exp)
print("---------------------------------------")
analyze_otter_failures(df_results, exp, failure_type='fp')
analyze_otter_failures(df_results, exp, failure_type='fn')
analyze_otter_failures(df_results, exp, failure_type='error')

fol_otter_output_Eng2FOL5
---------------------------------------
False Positives (Otter proved an invalid syllogism) | Experiment: fol_otter_output_Eng2FOL5
Found 4 cases

--------------------------------------------------

Index: 3 | ID: bff2af61-d4b0-4147-8a5b-ff4fe1892559
Syllogism:
  - There are no bikes that can be called cars
  - It is also true that every bike is a type of vehicle
  - This has led to the conclusion that a portion of vehicles are bikes

Validity: False
Otter Answer: True | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Bike(a) -> -Car(a)).
all a (Bike(a) -> Vehicle(a)).
% separation marker: end of original premises.
exists a (Bike(a)).
exists a (Car(a)).
exists a (Vehicle(a)).
-(exists a (Vehicle(a) & Bike(a))).
end_of_list.


Otter Proof Snippet:
----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
Sat Feb 28 12:47:15 2026
The command was "otter".

set(auto).
   dependent: set(auto1).
   dependent: set(process_input).
   dependent: clear(print_kept).
   dependent: clear(print_new_demod)....

==================================================

Index: 52 | ID: 6725d344-7c13-4d44-a97d-a4a1b89f858d
Syllogism:
  - The category of celestial bodies and the category of planets are mutually exclusive
  - Not a single planet is a star
  - It must be the case that a portion of stars are not celestial bodies

Validity: False
Otter Answer: True | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Planet(a) -> -CelestialBody(a)).
all a (Star(a) -> -CelestialBody(a)).
% separation marker: end of original premises.
exists a (CelestialBody(a)).
exists a (Planet(a)).
exists a (Star(a)).
-(exists a (Star(a) & -CelestialBody(a))).
end_of_list.


Otter Proof Snippet:
----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
Sat Feb 28 12:47:16 2026
The command was "otter".

set(auto).
   dependent: set(auto1).
   dependent: set(process_input).
   dependent: clear(print_kept).
   dependent: clear(print_new_demod)....

==================================================

Index: 127 | ID: ad259739-10fe-472e-87bb-6a8d488acfeb
Syllogism:
  - Something that is a chair is a table
  - A thing that is a table cannot be a building
  - It follows that a building is never a chair

Validity: False
Otter Answer: True | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Chair(a) -> Table(a)).
all a (Table(a) -> -Building(a)).
% separation marker: end of original premises.
exists a (Building(a)).
exists a (Chair(a)).
exists a (Table(a)).
-(all a (Building(a) -> -Chair(a))).
end_of_list.


Otter Proof Snippet:
----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
Sat Feb 28 12:47:17 2026
The command was "otter".

set(auto).
   dependent: set(auto1).
   dependent: set(process_input).
   dependent: clear(print_kept).
   dependent: clear(print_new_demod)....

==================================================

Index: 137 | ID: 8e100be7-956f-46e7-a431-a884cc30b28c
Syllogism:
  - There are no cats that can be called dogs
  - It is also true that every cat is a type of animal
  - This has led to the conclusion that a portion of animals are cats

Validity: False
Otter Answer: True | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Cat(a) -> -Dog(a)).
all a (Cat(a) -> Animal(a)).
% separation marker: end of original premises.
exists a (Animal(a)).
exists a (Cat(a)).
exists a (Dog(a)).
-(exists a (Animal(a) & Cat(a))).
end_of_list.


Otter Proof Snippet:
----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
Sat Feb 28 12:47:17 2026
The command was "otter".

set(auto).
   dependent: set(auto1).
   dependent: set(process_input).
   dependent: clear(print_kept).
   dependent: clear(print_new_demod)....

==================================================

False Negatives (Otter failed to prove a valid syllogism) | Experiment: fol_otter_output_Eng2FOL5
Found 5 cases

--------------------------------------------------

Index: 7 | ID: fd552276-66bf-45da-8cea-67192fe99fc3
Syllogism:
  - There is no piece of furniture that can be called a planet
  - Each and every chair is a piece of furniture
  - Consequently, no chair is a planet

Validity: True
Otter Answer: False | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Chair(a) -> -Planet(a)).
% separation marker: end of original premises.
exists a (Chair(a)).
exists a (Planet(a)).
-(all a (Chair(a) -> Furniture(a))).
end_of_list.


==================================================

Index: 20 | ID: cc8b1d14-79aa-445e-929c-ec3043229103
Syllogism:
  - Not a single object that is a vehicle is a type of transportation
  - A number of vehicles are buses
  - The conclusion that some buses are not transportation necessarily follows

Validity: True
Otter Answer: False | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Vehicle(a) -> -Transportation(a)).
exists a (Bus(a)).
% separation marker: end of original premises.
exists a (Transportation(a)).
exists a (Vehicle(a)).
-(exists a (Bus(a) & -Transportation(a))).
end_of_list.


==================================================

Index: 90 | ID: 78a473a3-d129-4c4d-8434-a0fce13d0024
Syllogism:
  - Every single river is a thing that flows towards the sea
  - The Amazon River is a river
  - A number of parts of the Amazon River flow towards the sea

Validity: True
Otter Answer: False | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (River(a) -> FlowsToSea(a)).
River(AmazonRiver).
% separation marker: end of original premises.
exists a (FlowsToSea(a)).
exists a (River(a)).
-(exists a (PartOf(AmazonRiver, a) & FlowsToSea(a))).
end_of_list.


==================================================

Index: 94 | ID: 372bfeea-11fd-47ad-b489-0616b8d2cd30
Syllogism:
  - Any and all clouds are made of solid iron
  - There are clouds that are a type of cumulus
  - This implies that some cumulus clouds are solid iron

Validity: True
Otter Answer: False | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Cloud(a) -> SolidIron(a)).
exists a (Cumulus(a)).
% separation marker: end of original premises.
exists a (Cloud(a)).
exists a (SolidIron(a)).
-(exists a (Cumulus(a) & SolidIron(a))).
end_of_list.


==================================================

Index: 110 | ID: 3f18c212-16aa-4c72-bde9-d1bb4349ca50
Syllogism:
  - There are no animals that are non-aquatic and also fish
  - A portion of the animals that are mammals are also non-aquatic
  - It must be the case that some mammals are not fish

Validity: True
Otter Answer: False | Error: None

Cleaned Input (FOL):
set(auto).
set(formula_history).
assign(max_seconds, 15).

formula_list(usable).
all a (Fish(a) -> -NonAquatic(a)).
exists a (Mammal(a) & -NonAquatic(a)).
% separation marker: end of original premises.
exists a (Fish(a)).
-(exists a (Mammal(a) & -Fish(a))).
end_of_list.


==================================================

Technical Errors / Timeouts | Experiment: fol_otter_output_Eng2FOL5
Found 0 cases

--------------------------------------------------

In [ ]:
for d in dataset:
    if d["otter_answer_fol_output_from_syllogism_simplified_Simp2"] != d["validity"]:
        print(d["syllogism_simplified_Simp2"])
        print(d["otter_answer_fol_output_from_syllogism_simplified_Simp2"], d["validity"])
        print(d["fol_output_from_syllogism_simplified_Simp2"])
#        print(d["otter_input_cleaned_fol_output_from_syllogism_simplified_Simp1"])
        print(d["otter_error_fol_output_from_syllogism_simplified_Simp2"])

['all Object is Capable_of_Flight', 'some Boat is not Object']
False True
['all x (Object(x) -> Capable_of_Flight(x))', 'exists x (Boat(x) & -Object(x))']
None
['no Bike is Car', 'all Bike is Vehicle', 'some Vehicle is Bike']
True False
['all x (Bike(x) -> -Car(x))', 'all x (Bike(x) -> Vehicle(x))', 'exists x (Vehicle(x) & Bike(x))']
None
['all Piece_of_Fruit grows_from_Plants', 'some Apple is Fruit', 'some Apple grows_from_Plants']
None True
['ERROR_UNPARSABLE: all Piece_of_Fruit grows_from_Plants', 'exists x (Apple(x) & Fruit(x))', 'ERROR_UNPARSABLE: some Apple grows_from_Plants']
Exit code 101. Snippet: ----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
['all Dog is Thing_with_Fur', 'no Cat is Dog', 'some Cat has Fur']
None False
['all x (Dog(x) -> Thing_with_Fur(x))', 'all x (Cat(x) -> -Dog(x))', 'ERROR_UNPARSABLE: some Cat has Fur']
Exit code 101. Snippet: ----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
['no Cat is Dog', 'some Animal_that_is_Cat is Pet', 'some Pet is not Dog']
False True
['all x (Cat(x) -> -Dog(x))', 'exists x (Animal_that_is_Cat(x) & Pet(x))', 'exists x (Pet(x) & -Dog(x))']
None
['no Planet is Star', 'all Celestial_Body is Planet', 'some Star is not Celestial_Body']
True False
['all x (Planet(x) -> -Star(x))', 'all x (Celestial_Body(x) -> Planet(x))', 'exists x (Star(x) & -Celestial_Body(x))']
None
['some Building is Skyscraper', 'all Skyscraper is Very_Tall_Structure', 'some Tall_Structure is Building']
False True
['exists x (Building(x) & Skyscraper(x))', 'all x (Skyscraper(x) -> Very_Tall_Structure(x))', 'exists x (Tall_Structure(x) & Building(x))']
None
['all Person_who_is_Filmmaker is Someone_who_works_in_Production', 'all Director is Person_who_is_Filmmaker', 'all Director is Someone_who_works_in_Production']
True False
['all x (Filmmaker(x) -> Someone_who_works_in_Production(x))', 'all x (Director(x) -> Filmmaker(x))', 'all x (Director(x) -> Someone_who_works_in_Production(x))']
None
['all Cloud is Politician', 'all Politician is Made_of_Cotton_Candy', 'some Thing_Made_of_Cotton_Candy is Cloud']
False True
['all x (Cloud(x) -> Politician(x))', 'all x (Politician(x) -> Made_of_Cotton_Candy(x))', 'exists x (Thing_Made_of_Cotton_Candy(x) & Cloud(x))']
None
['no Living_Thing is Stone', 'all Stone is Human', 'some Human is not Composed_of_Living_Thing']
False True
['all x (Living_Thing(x) -> -Stone(x))', 'all x (Stone(x) -> Human(x))', 'exists x (Human(x) & -Composed_of_Living_Thing(x))']
None
['all Liquid is Composed_of_Rock', 'some Liquid is Water', 'some Water is Made_of_Rock']
False True
['all x (Liquid(x) -> Composed_of_Rock(x))', 'exists x (Liquid(x) & Water(x))', 'exists x (Water(x) & Made_of_Rock(x))']
None
['all River is Thing_that_Flows_towards_Sea', 'all Amazon_River is River', 'some Part_of_Amazon_River is Thing_that_Flows_towards_Sea']
False True
['all x (River(x) -> Thing_that_Flows_towards_Sea(x))', 'all x (Amazon_River(x) -> River(x))', 'exists x (Part_of_Amazon_River(x) & Thing_that_Flows_towards_Sea(x))']
None
['all Thing_that_is_Car is Fruit', 'no Fruit is Vehicle', 'no Vehicle is Car']
False True
['all x (Thing_that_is_Car(x) -> Fruit(x))', 'all x (Fruit(x) -> -Vehicle(x))', 'all x (Vehicle(x) -> -Car(x))']
None
['all Cloud is Solid_Iron', 'all Cloud is Made_of_Solid_Iron', 'some Cumulus is Solid_Iron']
False True
['all x (Cloud(x) -> Solid_Iron(x))', 'all x (Cloud(x) -> Made_of_Solid_Iron(x))', 'exists x (Cumulus(x) & Solid_Iron(x))']
None
['no Animal is Non_Aquatic_and_Fish', 'some Animal is Mammal', 'some Mammal is not Fish']
False True
['all x (Animal(x) -> -Non_Aquatic_and_Fish(x))', 'exists x (Animal(x) & Mammal(x))', 'exists x (Mammal(x) & -Fish(x))']
None
['no Pet is Animal', 'some Bird is Categorized_as_Pet', 'some Group_of_Birds is not Animal']
False True
['all x (Pet(x) -> -Animal(x))', 'exists x (Bird(x) & Categorized_as_Pet(x))', 'exists x (Group_of_Bird(x) & -Animal(x))']
None
['some Thing is Fruit_and_not_Apple', 'all Fruit is Food', 'some Food is not Apple']
False True
['exists x (Thing(x) & Fruit_and_not_Apple(x))', 'all x (Fruit(x) -> Food(x))', 'exists x (Food(x) & -Apple(x))']
None
['all Human is Primate', 'all Person_that_is_Man is Human', 'all Man is Primate']
False True
['all x (Human(x) -> Primate(x))', 'all x (Person_that_is_Man(x) -> Human(x))', 'all x (Man(x) -> Primate(x))']
None
['all Scientist is Person_and_Researcher', 'no Chemist is Researcher', 'no Chemist is Scientist']
False True
['all x (Scientist(x) -> Person_and_Researcher(x))', 'all x (Chemist(x) -> -Researcher(x))', 'all x (Chemist(x) -> -Scientist(x))']
None
['all Chair is Table', 'no Table is Building', 'all Building is not Chair']
True False
['all x (Chair(x) -> Table(x))', 'all x (Table(x) -> -Building(x))', 'all x (Building(x) -> -Chair(x))']
None
['no Liquid is Beverage', 'some Type_of_Milk is Liquid', 'some Milk is not Beverage']
False True
['all x (Liquid(x) -> -Beverage(x))', 'exists x (Type_of_Milk(x) & Liquid(x))', 'exists x (Milk(x) & -Beverage(x))']
None
['no Cat is Dog', 'all Cat is Animal', 'some Animal is Cat']
True False
['all x (Cat(x) -> -Dog(x))', 'all x (Cat(x) -> Animal(x))', 'exists x (Animal(x) & Cat(x))']
None
['all Prime_Minister is Politician', 'some Person is Prime_Minister', 'some Person is Politician']
True False
['all x (Prime_Minister(x) -> Politician(x))', 'exists x (Person(x) & Prime_Minister(x))', 'exists x (Person(x) & Politician(x))']
None
['no Percussion_Instrument is Stringed_Instrument', 'all Certain_Group_of_Percussion_Instruments is Musical_Instrument', 'some Musical_Instrument is not Stringed_Instrument']
False True
['all x (Percussion_Instrument(x) -> -Stringed_Instrument(x))', 'all x (Certain_Group_of_Percussion_Instrument(x) -> Musical_Instrument(x))', 'exists x (Musical_Instrument(x) & -Stringed_Instrument(x))']
None
['no Planet is Star', 'all Celestial_Body_named_Earth is Planet', 'some Earth is not Star']
False True
['all x (Planet(x) -> -Star(x))', 'all x (Celestial_Body_named_Earth(x) -> Planet(x))', 'exists x (Earth(x) & -Star(x))']
None
['no State is Canada', 'all Canada is Country', 'some Country is not State_in_USA']
False True
['all x (State(x) -> -Canada(x))', 'all x (Canada(x) -> Country(x))', 'exists x (Country(x) & -State_in_USA(x))']
None
['all Pencil is Item_of_Stationery', 'no Stationery_Item is Food', 'some Food is not Pencil']
False True
['all x (Pencil(x) -> Item_of_Stationery(x))', 'all x (Stationery_Item(x) -> -Food(x))', 'exists x (Food(x) & -Pencil(x))']
None
['no Fish is Mammal', 'all Whale is Creature', 'some Whale is not Fish']
False True
['all x (Fish(x) -> -Mammal(x))', 'all x (Whale(x) -> Creature(x))', 'exists x (Whale(x) & -Fish(x))']
None
['no Planet is Star', 'some Thing_is_Planet', 'no Gas_Giant is Star']
None True
['all x (Planet(x) -> -Star(x))', 'ERROR_UNPARSABLE: some Thing_is_Planet', 'all x (Gas_Giant(x) -> -Star(x))']
Exit code 101. Snippet: ----- Otter 3.3, August 2003 -----
The process was started by a Windows user on a Windows machine,
['all Student is Person', 'all Person is Person', 'no Robot is Student']
False True
['all x (Student(x) -> Person(x))', 'all x (Person(x) -> Person(x))', 'all x (Robot(x) -> -Student(x))']
None
['all Dog is Star', 'all Dog is Made_of_Cheese', 'some Thing_Made_of_Cheese is Star']
False True
['all x (Dog(x) -> Star(x))', 'all x (Dog(x) -> Made_of_Cheese(x))', 'exists x (Thing_Made_of_Cheese(x) & Star(x))']
None

### manuelle Inspektion von Ergebnissen

In [ ]:
[x for x in dataset.features if "answer" in x]

['otter_answer_fol_otter_output_Eng2FOL',
 'otter_answer_fol_otter_output_Eng2FOL10Qwen4B',
 'otter_answer_fol_otter_output_Eng2FOL10',
 'otter_answer_fol_otter_output_Eng2FOL11',
 'otter_answer_fol_otter_output_Eng2FOL2',
 'otter_answer_fol_otter_output_Eng2FOL3',
 'otter_answer_fol_otter_output_Eng2FOL4',
 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B',
 'otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B',
 'otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B',
 'otter_answer_fol_otter_output_Eng2FOL5Qwen4B',
 'otter_answer_fol_otter_output_Eng2FOL5',
 'otter_answer_fol_otter_output_Eng2FOL5small',
 'otter_answer_fol_otter_output_Eng2FOL5tiny',
 'otter_answer_fol_otter_output_Eng2FOL6',
 'otter_answer_fol_otter_output_Eng2FOL7',
 'otter_answer_fol_otter_output_Eng2FOL8',
 'otter_answer_fol_otter_output_Eng2FOL9Qwen4B',
 'otter_answer_fol_otter_output_Eng2FOL9',
 'otter_answer_fol_otter_output_QwenEng2FOL1',
 'otter_answer_fol_otter_output_QwenEng2FOL2',
 'otter_answer_fol_otter_output_QwenEng2FOL3',
 'otter_answer_fol_otter_output_QwenEng2FOL4',
 'otter_answer_fol_otter_output_QwenEng2FOL5',
 'otter_answer_fol_otter_output_QwenEng2FOL6',
 'otter_answer_fol_otter_output_SimpEng2FOL1',
 'otter_answer_fol_otter_output_SimpEng2FOL2',
 'otter_answer_fol_output_from_syllogism',
 'otter_answer_fol_output_from_syllogism_simplified_Simp1',
 'otter_answer_fol_output_from_syllogism_simplified_Simp2']

In [ ]:
#experiment_id = "QwenEng2FOL5multilingualNewShort"
experiment_id = "Eng2FOL5"

for i in range(20):
#    s = dataset[i]['original_syllogism']
    s = dataset[i]['syllogism']
    print(s)
    print(len(s.split('.'))-1)
    fol = dataset[i]['fol_otter_output_'+ experiment_id]
    print(fol)
    print(len(fol))
    used_clauses = [x for x in dataset[i]["otter_used_clauses_fol_otter_output_"+ experiment_id]]
    print([s.split('.')[k] for k in used_clauses])
    #print("=>", s.split('.')[-2])
    print([fol[k] for k in used_clauses])
    print("=>", fol[-1])
    print(used_clauses)
    print("-"*40)

Every single object can fly. It is known that some boats cannot fly. It follows that some boats are not objects.
3
['all x ( Object(x) -> Fly(x) )', 'exists x ( Boat(x) & -Fly(x) )', 'exists x ( Boat(x) & -Object(x) )']
3
['Every single object can fly', ' It is known that some boats cannot fly']
['all x ( Object(x) -> Fly(x) )', 'exists x ( Boat(x) & -Fly(x) )']
=> exists x ( Boat(x) & -Object(x) )
[0, 1]
----------------------------------------
There exist some objects that are books which are not digital files. Every single book is an item with pages. Consequently, some items with pages are digital files.
3
['exists x ( Book(x) & -DigitalFile(x) )', 'all x ( Book(x) -> HasPages(x) )', 'exists x ( HasPages(x) & DigitalFile(x) )']
3
[]
[]
=> exists x ( HasPages(x) & DigitalFile(x) )
[]
----------------------------------------
There are no individuals who are elephants that are also people enrolled in kindergarten. All five-year-olds are people enrolled in kindergarten. It can be deduced that some five-year-olds are not elephants.
3
['all x ( Elephant(x) & -Kindergarten(x) )', 'all x ( FiveYearOld(x) -> Person(x) & Kindergarten(x) )', 'exists x ( FiveYearOld(x) & -Elephant(x) )']
3
['There are no individuals who are elephants that are also people enrolled in kindergarten']
['all x ( Elephant(x) & -Kindergarten(x) )']
=> exists x ( FiveYearOld(x) & -Elephant(x) )
[0]
----------------------------------------
There are no bikes that can be called cars. It is also true that every bike is a type of vehicle. This has led to the conclusion that a portion of vehicles are bikes.
3
['all x ( Bike(x) -> -Car(x) )', 'all x ( Bike(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Bike(x) )']
3
[' It is also true that every bike is a type of vehicle']
['all x ( Bike(x) -> Vehicle(x) )']
=> exists x ( Vehicle(x) & Bike(x) )
[1]
----------------------------------------
No animal is a rock. Some rocks are plants. From this, it can be concluded that some animals are plants.
3
['all x ( Animal(x) -> -Rock(x) )', 'exists x ( Rock(x) & Plant(x) )', 'exists x ( Animal(x) & Plant(x) )']
3
[]
[]
=> exists x ( Animal(x) & Plant(x) )
[]
----------------------------------------
The entire set of fruits is composed of round objects with a citrus peel. At least one orange is not a round object with a citrus peel. Every single fruit is an orange.
3
['all x ( Fruit(x) -> Round(x) & CitrusPeel(x) )', 'exists x ( Orange(x) & -Round(x) & -CitrusPeel(x) )', 'all x ( Fruit(x) -> Orange(x) )']
3
[]
[]
=> all x ( Fruit(x) -> Orange(x) )
[]
----------------------------------------
No animal is a tree. All trees are plants without exception. A number of plants are animals.
3
['all x ( Animal(x) -> -Tree(x) )', 'all x ( Tree(x) -> Plant(x) )', 'exists x ( Plant(x) & Animal(x) )']
3
[]
[]
=> exists x ( Plant(x) & Animal(x) )
[]
----------------------------------------
There is no piece of furniture that can be called a planet. Each and every chair is a piece of furniture. Consequently, no chair is a planet.
3
['all x ( Chair(x) -> -Planet(x) )', 'all x ( Chair(x) -> Furniture(x) )']
2
[]
[]
=> all x ( Chair(x) -> Furniture(x) )
[]
----------------------------------------
There exist some things that are books which do not have pages. Every single book is a living thing. Consequently, some living things have pages.
3
['exists x ( Book(x) & -HasPages(x) )', 'all x ( Book(x) -> Living(x) )', 'exists x ( Living(x) & HasPages(x) )']
3
[]
[]
=> exists x ( Living(x) & HasPages(x) )
[]
----------------------------------------
Every single fruit is a food. Nothing that is a vegetable is a food. It follows from this that every vegetable is a fruit.
3
['all x ( Fruit(x) -> Food(x) )', 'all x ( Vegetable(x) -> -Food(x) )', 'all x ( Vegetable(x) -> Fruit(x) )']
3
[]
[]
=> all x ( Vegetable(x) -> Fruit(x) )
[]
----------------------------------------
There are no cars that are not alive. It is the case that no horse is alive. At least some horses are cars.
3
['all x ( Car(x) -> Alive(x) )', 'all x ( Horse(x) -> -Alive(x) )', 'exists x ( Horse(x) & Car(x) )']
3
[]
[]
=> exists x ( Horse(x) & Car(x) )
[]
----------------------------------------
Every single four-sided-shape is a rectangle. All four-sided-shapes are squares. It follows from this that some squares are not rectangles.
3
['all x ( FourSidedShape(x) -> Rectangle(x) )', 'all x ( FourSidedShape(x) -> Square(x) )', 'exists x ( Square(x) & -Rectangle(x) )']
3
[]
[]
=> exists x ( Square(x) & -Rectangle(x) )
[]
----------------------------------------
Every single item that is a writing instrument is a tool. There are some pens which are writing instruments. Thus, some pens are tools.
3
['all x ( WritingInstrument(x) -> Tool(x) )', 'exists x ( Pen(x) & WritingInstrument(x) )', 'exists x ( Pen(x) & Tool(x) )']
3
['Every single item that is a writing instrument is a tool', ' There are some pens which are writing instruments']
['all x ( WritingInstrument(x) -> Tool(x) )', 'exists x ( Pen(x) & WritingInstrument(x) )']
=> exists x ( Pen(x) & Tool(x) )
[0, 1]
----------------------------------------
Every single vehicle can be considered an object. There are no cars that are objects. Therefore, no car is a vehicle.
3
['all x ( Vehicle(x) -> Object(x) )', 'all x ( Car(x) -> -Object(x) )', 'all x ( Car(x) -> -Vehicle(x) )']
3
['Every single vehicle can be considered an object', ' There are no cars that are objects']
['all x ( Vehicle(x) -> Object(x) )', 'all x ( Car(x) -> -Object(x) )']
=> all x ( Car(x) -> -Vehicle(x) )
[0, 1]
----------------------------------------
There are no fish that do not live on the moon. It is the case that no cat is a fish. At least some cats live on the moon.
3
['all x ( Fish(x) -> LivesOnMoon(x) )', 'all x ( Cat(x) -> -Fish(x) )', 'exists x ( Cat(x) & LivesOnMoon(x) )']
3
[]
[]
=> exists x ( Cat(x) & LivesOnMoon(x) )
[]
----------------------------------------
There are no birds that are triangles. Every triangle is, by definition, a shape. Thus, some shapes are birds.
3
['all x ( Bird(x) -> -Triangle(x) )', 'all x ( Triangle(x) -> Shape(x) )', 'exists x ( Shape(x) & Bird(x) )']
3
[]
[]
=> exists x ( Shape(x) & Bird(x) )
[]
----------------------------------------
There are no cars that are airplanes. Everything that is a dog is a car. Thus, every dog is an airplane.
3
['all x ( Car(x) -> -Airplane(x) )', 'all x ( Dog(x) -> Car(x) )', 'all x ( Dog(x) -> Airplane(x) )']
3
[]
[]
=> all x ( Dog(x) -> Airplane(x) )
[]
----------------------------------------
A stone is never inanimate. Everything that is a statue is a stone. Therefore, this implies that no statue is inanimate.
3
['all x ( Stone(x) -> -Inanimate(x) )', 'all x ( Statue(x) -> Stone(x) )', 'all x ( Statue(x) -> -Inanimate(x) )']
3
['A stone is never inanimate', ' Everything that is a statue is a stone']
['all x ( Stone(x) -> -Inanimate(x) )', 'all x ( Statue(x) -> Stone(x) )']
=> all x ( Statue(x) -> -Inanimate(x) )
[0, 1]
----------------------------------------
There is no canine that is a feline. Everything that is a canine is also a dog. This makes it true that all dogs are cats.
3
['all x ( Canine(x) -> -Feline(x) )', 'all x ( Canine(x) -> Dog(x) )', 'all x ( Dog(x) -> Cat(x) )']
3
[]
[]
=> all x ( Dog(x) -> Cat(x) )
[]
----------------------------------------
Anything that is a bird is a building. Anything that is a bird is a vehicle. Consequently, some vehicles are buildings.
3
['all x ( Bird(x) -> Building(x) )', 'all x ( Bird(x) -> Vehicle(x) )', 'exists x ( Vehicle(x) & Building(x) )']
3
['Anything that is a bird is a building', ' Anything that is a bird is a vehicle']
['all x ( Bird(x) -> Building(x) )', 'all x ( Bird(x) -> Vehicle(x) )']
=> exists x ( Vehicle(x) & Building(x) )
[0, 1]
----------------------------------------

In [ ]:
print([x for x in dataset.features if experiment_id in x])

['fol_otter_output_Eng2FOL5Gemma2B', 'fol_otter_output_Eng2FOL5Qwen0.6B', 'fol_otter_output_Eng2FOL5Qwen1.7B', 'fol_otter_output_Eng2FOL5Qwen4B', 'fol_otter_output_Eng2FOL5', 'fol_otter_output_Eng2FOL5small', 'fol_otter_output_Eng2FOL5tiny', 'fol_otter_output_QwenEng2FOL5', 'otter_used_clauses_fol_otter_output_Eng2FOL5Gemma2B', 'otter_answer_fol_otter_output_Eng2FOL5Gemma2B', 'otter_error_fol_otter_output_Eng2FOL5Gemma2B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Gemma2B', 'otter_proof_fol_otter_output_Eng2FOL5Gemma2B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_error_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen0.6B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_error_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen1.7B', 'otter_used_clauses_fol_otter_output_Eng2FOL5Qwen4B', 'otter_answer_fol_otter_output_Eng2FOL5Qwen4B', 'otter_error_fol_otter_output_Eng2FOL5Qwen4B', 'otter_input_cleaned_fol_otter_output_Eng2FOL5Qwen4B', 'otter_proof_fol_otter_output_Eng2FOL5Qwen4B', 'otter_used_clauses_fol_otter_output_Eng2FOL5', 'otter_answer_fol_otter_output_Eng2FOL5', 'otter_error_fol_otter_output_Eng2FOL5', 'otter_input_cleaned_fol_otter_output_Eng2FOL5', 'otter_proof_fol_otter_output_Eng2FOL5', 'otter_used_clauses_fol_otter_output_Eng2FOL5small', 'otter_answer_fol_otter_output_Eng2FOL5small', 'otter_error_fol_otter_output_Eng2FOL5small', 'otter_input_cleaned_fol_otter_output_Eng2FOL5small', 'otter_proof_fol_otter_output_Eng2FOL5small', 'otter_used_clauses_fol_otter_output_Eng2FOL5tiny', 'otter_answer_fol_otter_output_Eng2FOL5tiny', 'otter_error_fol_otter_output_Eng2FOL5tiny', 'otter_input_cleaned_fol_otter_output_Eng2FOL5tiny', 'otter_proof_fol_otter_output_Eng2FOL5tiny', 'otter_used_clauses_fol_otter_output_QwenEng2FOL5', 'otter_answer_fol_otter_output_QwenEng2FOL5', 'otter_error_fol_otter_output_QwenEng2FOL5', 'otter_input_cleaned_fol_otter_output_QwenEng2FOL5', 'otter_proof_fol_otter_output_QwenEng2FOL5']

### Error Analysis syllogism prover

In [ ]:
dataset_df = pd.DataFrame(dataset)
dataset_df.head(3)

,id,syllogism,fol_otter_output_Eng2FOL,fol_otter_output_Eng2FOL10Qwen4B,fol_otter_output_Eng2FOL10,fol_otter_output_Eng2FOL11,fol_otter_output_Eng2FOL2,fol_otter_output_Eng2FOL3,fol_otter_output_Eng2FOL4,fol_otter_output_Eng2FOL5Gemma2B,...,SimpEng2SyllogismProlog_aristotelian_truth,SimpEng2SyllogismProlog_aristotelian_type,from_syllogism_aristotelian_truth,from_syllogism_aristotelian_type,from_syllogism_simplified_Simp1_aristotelian_truth,from_syllogism_simplified_Simp1_aristotelian_type,from_syllogism_simplified_Simp2_aristotelian_truth,from_syllogism_simplified_Simp2_aristotelian_type,validity,plausibility
0,e773bd8c-fa53-4e9c-8ec6-7d978e0601ac,Every single object can fly. It is known that ...,"[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> CanFly(x) ), exists x ( ...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...","[all x ( Object(x) -> Fly(x) ), exists x ( Boa...",...,False,error,False,error,False,error,False,error,True,False
1,f36a4ca3-3b69-4869-a152-deaa7e0fdad4,There exist some objects that are books which ...,"[exists x ( Book(x) & -DigitalFile(x) ), all x...",[exists x ( (Object(x) & Book(x)) & -DigitalFi...,[exists x ( (Object(x) & Book(x)) & -DigitalFi...,"[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...","[exists x ( Book(x) & -DigitalFile(x) ), all x...",...,False,unknown,None,none,False,unknown,False,unknown,False,True
2,6e5f055f-06e4-40f3-a45b-52b7d9292d60,There are no individuals who are elephants tha...,"[all x ( Elephant(x) & -Person(x) ), all x ( F...",[all x ( (Elephant(x) & Person(x)) -> -Enrolle...,[all x ( (Elephant(x) & Person(x)) -> -Kinderg...,['all x ( Elephant(x) & Person(x) & Kindergart...,[all x ( Elephant(x) -> -Person(x) & Kindergar...,[exists x ( Elephant(x) & Person(x) & Kinderga...,[all x ( Elephant(x) & Kindergarten(x) -> -Per...,[all x ( Elephant(x) & Person(x) -> -Kindergar...,...,True,cesaro,None,none,True,cesaro,True,cesaro,True,True

In [ ]:
truth_keys = [x for x in dataset.features if "truth" in x]

In [ ]:
def calculate_experiment_metrics(df, input_keys):
    """
    Calculates proof statistics and confusion matrix for each experiment
    compared to the ground truth 'validity' column.
    """
    metrics_list = []

    for key in input_keys:
        if key not in df.columns:
            print(f"⚠️ Column {key} not found in dataset. Skipping.")
            continue

        # Ground Truth: 'validity' (True/False)
        # Prediction: key (True/False/None)

        total = len(df)
        # We handle None/Error as False for the sake of the confusion matrix
        # or treat them as separate 'Errors'
        preds = df[key].fillna(False)
        actual = df['validity']

        # Logic for Confusion Matrix
        tp = ((preds == True) & (actual == True)).sum()
        tn = ((preds == False) & (actual == False)).sum()
        fp = ((preds == True) & (actual == False)).sum()
        fn = ((preds == False) & (actual == True)).sum()

        # Count technical errors (None values)
        errors = df[key].isna().sum()

        metrics_list.append({
            'Experiment': key.split("_aristotelian_truth")[0],
            'Total': total,
            'TP (Correct Proof)': tp,
            'TN (Correct Disproof)': tn,
            'FP (False Proof)': fp,
            'FN (Missed Proof)': fn,
            'Errors': errors,
            'Accuracy': (tp + tn) / total if total > 0 else 0
        })

    return pd.DataFrame(metrics_list)

# Usage:
df_results = pd.DataFrame(dataset)
summary_table = calculate_experiment_metrics(df_results, truth_keys)

# Display the table
print(summary_table.to_string(index=False))

                     Experiment  Total  TP (Correct Proof)  TN (Correct Disproof)  FP (False Proof)  FN (Missed Proof)  Errors  Accuracy
            Eng2SyllogismProlog    191                  56                     82                13                 40       0  0.722513
        SimpEng2SyllogismProlog    191                  61                     86                 9                 35       0  0.769634
                 from_syllogism    191                   0                     95                 0                 96     126  0.497382
from_syllogism_simplified_Simp1    191                  68                     95                 0                 28       0  0.853403
from_syllogism_simplified_Simp2    191                  67                     91                 4                 29       0  0.827225

In [ ]:
truth_keys

['Eng2SyllogismProlog_aristotelian_truth',
 'SimpEng2SyllogismProlog_aristotelian_truth',
 'from_syllogism_aristotelian_truth',
 'from_syllogism_simplified_Simp1_aristotelian_truth',
 'from_syllogism_simplified_Simp2_aristotelian_truth']

In [ ]:
print(df_results["from_syllogism_simplified_Simp1_aristotelian_truth"].value_counts())
df_results["from_syllogism_simplified_Simp1_aristotelian_type"].value_counts()

False    123
True      68
Name: from_syllogism_simplified_Simp1_aristotelian_truth, dtype: int64

unknown      109
error         14
dimaris        6
felapton       6
cesaro         5
darapti        4
celarent       4
darii          3
ferio          3
fresison       3
camenes        3
celaront       3
baroco         3
camestres      3
barbara        3
camenop        3
camestros      2
datisi         2
barbari        2
bramantip      2
disamis        2
cesare         2
fesapo         1
ferison        1
bocardo        1
festino        1
Name: from_syllogism_simplified_Simp1_aristotelian_type, dtype: int64

In [ ]:
# List of output keys for merging and analysis
list1 = [
    "fol_otter_output_Eng2FOL",
    "fol_otter_output_Eng2FOL10Qwen4B",
    "fol_otter_output_Eng2FOL10",
    "fol_otter_output_Eng2FOL2",
    "fol_otter_output_Eng2FOL3",
    "fol_otter_output_Eng2FOL4",
    "fol_otter_output_Eng2FOL5Gemma2B",
    "fol_otter_output_Eng2FOL5Qwen0.6B",
    "fol_otter_output_Eng2FOL5Qwen1.7B",
    "fol_otter_output_Eng2FOL5Qwen4B",
    "fol_otter_output_Eng2FOL5",
    "fol_otter_output_Eng2FOL5small",
    "fol_otter_output_Eng2FOL5tiny",
    "fol_otter_output_Eng2FOL6",
    "fol_otter_output_Eng2FOL7",
    "fol_otter_output_Eng2FOL8",
    "fol_otter_output_Eng2FOL9Qwen4B",
    "fol_otter_output_Eng2FOL9",
    "fol_otter_output_QwenEng2FOL1",
    "fol_otter_output_QwenEng2FOL2",
    "fol_otter_output_QwenEng2FOL3",
    "fol_otter_output_QwenEng2FOL4",
    "fol_otter_output_QwenEng2FOL5",
    "fol_otter_output_QwenEng2FOL6",
    "fol_otter_output_SimpEng2FOL1",
    "fol_otter_output_SimpEng2FOL2",
    "fol_output_from_syllogism_simplified_Simp1",
    "fol_output_from_syllogism_simplified_Simp2",
    "Eng2SyllogismProlog_aristotelian_truth",
    "from_syllogism_simplified_Simp1_aristotelian_truth",
    "from_syllogism_simplified_Simp2_aristotelian_truth"
]

list2 = [
    "fol_otter_output_Eng2FOL5",
    "fol_otter_output_QwenEng2FOL1",
    "fol_otter_output_Eng2FOL10Qwen4B",
    "fol_otter_output_QwenEng2FOL5",
    "fol_otter_output_Eng2FOL5Qwen4B",
    "fol_otter_output_Eng2FOL7",
    "fol_otter_output_Eng2FOL6",
    "fol_otter_output_Eng2FOL",
    "fol_otter_output_QwenEng2FOL6",
    "fol_otter_output_Eng2FOL8",
    "fol_otter_output_Eng2FOL4",
    "fol_otter_output_QwenEng2FOL2",
    "fol_otter_output_QwenEng2FOL3",
    "fol_otter_output_Eng2FOL9Qwen4B",
    "fol_otter_output_Eng2FOL3",
    "fol_otter_output_Eng2FOL10",
    "fol_otter_output_Eng2FOL9",
    "fol_otter_output_SimpEng2FOL1",
    "fol_output_from_syllogism_simplified_Simp1",
    "fol_output_from_syllogism_simplified_Simp2",
    "fol_otter_output_Eng2FOL2",
    "fol_otter_output_SimpEng2FOL2",
    "from_syllogism_simplified_Simp1_aristotelian_truth",
    "from_syllogism_simplified_Simp2_aristotelian_truth",
    "fol_otter_output_Eng2FOL5Gemma2B",
    "Eng2SyllogismProlog_aristotelian_truth",
    "fol_otter_output_Eng2FOL5small"
]

In [ ]:
len(list1), len(list2)

(31, 27)

In [ ]:
[key for key in list1 if key not in list2]

['fol_otter_output_Eng2FOL5Qwen0.6B',
 'fol_otter_output_Eng2FOL5Qwen1.7B',
 'fol_otter_output_Eng2FOL5tiny',
 'fol_otter_output_QwenEng2FOL4']